<?php
$content = [
     "HomePage" => [
        'Toggle navigation',
        'Skillroads',
        'Contact →',
        'Game Changing',
        'AI Resume',
        'Making Services',
        'Empower the employment process with Artificial Intelligence. Let algorithms run career counselling, investigate your professional interests, instantly create a resume and provide a perfect job match',
        'Boost My Career',
        'AI Resume Generator',
        'Smart resume review',
        'Cover Letter Generator',
        'TOP Jobs',
        'Our resume creator will generate custom documents to impress recruiters in just a few clicks. With the integration of progressive technologies, to make a resume and get hired is not rocket science anymore.',
        'Try resume maker for free',
        'Our resume checker gives instant feedback on your resume, identifying whether it is qualified enough and passes ATS. Check your resume score and follow the guidelines to fix any imperfections.',
        'Try our cover letter generator, and you will see that success can be easily reached. You will get a compelling cover letter created for you that will set you apart from other candidates.',
        'Explore job openings from TOP companies. Simplify the whole application process by having access to the personalized approach, digital job fair, lists of jobs tailored to your interests and experience.',
        'AI Resume Generator',
        'Smart Resume Review',
        'Cover Letter Generator',
        'Fortune 500 Jobs',
        'How AI Online Resume Maker Works',
        'Enter your preferred job title',
        'Take a brief 5 min questionnaire to describe your experience',
        'Identify strengths and skills that suit you best by using smart data sourcing and Natural Language Processing (NLP)',
        'Let Skillroads’ AI Robo make a resume for you!',
        'How Smart Resume Check Works?',
        'Upload your resume',
        'Let AI analyze: search for keywords and scan resume sections and outlines',
        'Unlock access to career services and check chances to get a job',
        'Get feedback if your resume needs to be fixed and move ahead',
        'How AI Cover Letter Builder Works?',
        'Enter your resume details',
        'Let AI Robo analyze your resume and select proper key competences to be highlighted',
        'Wait a while till AI Robo creates your customized Cover Letter',
        'Enjoy a Cover Letter as a perfect alternative to impress employment professionals',
        'How Fortune 500 job opportunity Works?',
        'Explore job openings from Fortune 500 companies',
        'Get accurate results and let us show positions that match your skills, experience and education',
        'Go through job application process smoothly',
        'Enhance your experience and go for further career development',
        'Want it all Now',
        'Our Customers Work For',
        ' I find this free resume maker awesome. It does a lot of things, makes a good match for a job, finds skills and knowledge missing according to my background and desired position. It gives you full access to all career services like resume creation, personalized cover letter writing based on your profile information and it connects potential candidates to the best job offer. I`ve been working as Sales Manager for 2 years, and honestly, I never paid attention to my resume and how to grow my career. However, when I started looking for a new opportunity, I found this Career Builder. I went through the whole process of job application from resume to job search, interview help, and career development plan. Now I know what I need to study to grow my career, how to achieve goals and, if needed, how to edit a resume once again to pass ATS.',
        'Mathew Vallo',
        'Sales Manager',
        'As a fresh grad, I was about to enter the job market. Obviously, I lost my bearings. I had a poor idea of what needs to be done, how to conduct my resume with basically no practical experience in the desired work-field, how to get a job and craved profound career guidance. Moreover, I also needed some help in finding a job that could suit my skills and would be challenging enough for a junior job-seeker. Skillroads career development service is a good kick-start of my career. I found here all necessary info including articles, guides, resume samples, interview help and a list of job openings that suited my knowledge most. Resume conducted by AI maker also worked well, and it landed me a job in two weeks. To create a resume online with Skillroads was one of my best ideas ever.',
        'Francisco Jackson',
        'Construction Engineer',
        ' Once, I had to update my resume as soon as possible, since I was offered an outstanding high-paid job. That’s crazy, the last time I made a resume was 8 years ago so creating a resume from scratch seemed an almost insurmountable obstacle. I needed to polish an old resume, highlight specific skills that were required most, and to check if the whole paper was mistake-free and organized properly for an executive position. I had only 12 hours to send my application, and a career advisor couldn’t review a resume on time. So the moment I came across Smart Resume Review, I felt blessed. I got fast feedback about my resume and AI created a cover letter for me. I just had to edit my resume a little and make a cover letter be addressed to a certain HR department. Well, now I must say, my new position is definitely worth that efforts!',
        'Olia Jacky Roady',
        'Nurse Assistant',
        'Get Access to More Services',
        'Free Resume Checker',
        'AI makes sure your resume is striking and error-free to land a job you want',
        'LinkedIn Profile Editing',
        'Get recruited and become connected with the opportunities inside',
        'Resume Writing Services',
        'US-based accredited writers from our best CV writing service make your resume catchy',
        'Resume Samples',
        'Make sure hiring managers see the best version of you',
        'Online Resume Builder',
        'Turn your resume into a powerful marketing tool and impress employers',
        'Career Tips',
        'Craft a compelling career story to sell yourself and get hired',
        'Fortune 500 Job Offers',
        'Explore job openings from 500 Fortune companies',
        'Cover Letter Builder',
        'Get your Cover Letter and have more chances to win the interview',
        'Hi there, I`m looking for an employment opportunity with your AI Career Service. Is there anything u can help me with?',
        'AI&nbsp;Robo',
        'Sure, you can try AI Resume Builder or use our career services that will help you to climb to the top heights of a career ladder.',
        'Wow, sounds interesting, what do I have to do then? Tell me a bit more about it.',
        'AI&nbsp;Robo',
        'My pleasure, you can get personalized job offers matched with your skills and get interview help based on a personal development plan.',
        'Sounds exactly what I`m looking for, thanks a lot! Could you tell me more about these opportunities?',
        'AI&nbsp;Robo',
        'Absolutely, I`m here to make the best of your knowledge and experience helping you to get the job you have always wanted.',
        ' We Lead You to Success',
        'Boost Your Resume',
        'Let Artificial Intelligence discover your strong suits and get you hired',
        'Grow with Career Advisor',
        'Include both personal and career goals in a single plan and guide yourself to the job destination',
        'Early Access to New Career Features',
        'Develop your career with an exclusive feature set as the best step you’ll ever make',
        'Sign up & Benefit now',
        'Everything You Wanted to Know about Our Career and Resume Making Service',
        ' Here you can find answers to the most frequently asked questions. In case you have any other question or issue, do not hesitate to contact us via chat, email or by phone.',
        'What Is Skillroads?',
        'We are a professional resume writing service with 96.4% success rate that hires skilled resume writers to help job seekers get high-quality resume or CV writing assistance. Our goal is to ensure that every client lands their dream job either with our AI resume builder or personalized services our professionals provide.',
        'What Type of Application Documents Do We Create?',
        'We offer a wide range of application documents starting with simple',
        'Resume/CV Editing',
        'to',
        'All Inclusive Application Job Package',
        ', which comprises',
        'CV/Resume Writing',
        '+',
        'Cover Letter Writing',
        '+',
        'LinkedIn Profile Editing',
        '+',
        'CV/Resume custom design',
        '. In case you need two or more services, you can order them in packages such as',
        'CV + Cover Letter',
        ',',
        'Resume Writing + Design',
        ',',
        'Resume Writing',
        '+',
        'LinkedIn',
        '+',
        'Cover Letter',
        ', etc. Also we have two free options to let you try us first without breaking the bank. In such a way you may create a free resume using our AI resume maker or check your existed one with Resume Review service. Skillroads is the all in one website you need to get invited to the interview and thus, get hired.',
        'What Makes Our Online Resume Maker the Best?',
        'First and foremost, with the best resume maker on the market, you create a FREE resume. Just imagine that all you have to do to create resume online is choose the desired position from the list, have a quick questionnaire and - BOOM! – you have your resume ready by Artificial Intelligence that processed all the data provided and tailored it to make a free resume polished and attractive to pass ATS. Isn’t it a miracle?',
        'What Is the Difference Between the Free Resume Creator and Resume Writing Service?',
        'Our online resume creator is powered by Artificial Intelligence. It helps to create a professional resume that passes an ATS and grabs the attention of fastidious Hiring Managers. When asking for a Resume Writing service, you get a custom resume crafted by one of our skilled professionals. Resume writers will create a resume from scratch, tailoring it to your desired position and including all extra information needed.',
        'How Safe and Secure Are You Using Our Site?',
        'At',
        ', your security and privacy are vital to us. We are mindful of the personal details we ask you to provide us with and personal data that we gather through the operation of our resume services. We guarantee no personal data will ever be shared with third parties. When making a resume with us, you get access to a password-protected personal account with all the data controlled by you.',
        'What Can You Do If You’re Not Satisfied with Our Resume Making Services?',
        '96.8% of our orders are done without any issues or questions arisen. Our responsibility is to ensure that all clients who have faced any issues are satisfied with the final results. In case of discontent, we offer 3 free revisions within 14 days. Dissatisfied with the professional assigned? No problem, we will reassign them. If there are issues that cannot be amended by a revision or a new resume writer, we’ve got you covered with a money-back guarantee. Whatever the problem, we are here to assist you.',
        'What Is the Procedure of Placing the Order?',
        'Speaking of the overall process, let’s go step by step.',
        'Step 1:',
        'Initially, you have to choose the service you need, add your personal details and submit payment.',
        'By doing so, you provide us with basic info about you and get access tо your personal account (the dashboard, an independent system where you can communicate with a writer directly on the message board) and upload instructions.',
        'Step 2:',
        'Our Support Department will check your order and assign a writer who is proficient in your industry/area of professional expertise.',
        'Step 3:',
        'You receive your tailored application document(s). Please mind that the design of the writers dashboard will differ from that on our website. It is all right. If needed, you can contact our support team by phone 1-917-900-1189.',
        'In case you have some suggestions for improvement after receiving your documents, you can send the files to the writer with your comments to make resume online better.',
        'Is There Any Refund in Case I Am Dissatisfied with the Service Provided or Do Not Need Your Service Anymore?',
        'Yes, in case your issue cannot be resolved by a revision or by the reassignment of resume writer, you have the right to get a refund. The refund process depends on a particular issue. Let’s take a look at all of them.',
        ' You do not need our service anymore.',
        'In this case, you can cancel the order. If a writer has not started working on it, you get a full refund. The procedure is as follows:',
        'You ask the Support Team to cancel the order.',
        'The Support Team cancels it and sends a request to the Billing Department.',
        'The Billing Department sends a refund request to PayPal (our payment system).',
        'PayPal refunds money to your account.',
        'You do not like the materials provided.',
        'If after revisions you are still dissatisfied, the following procedure is set in place:',
        'You address the Support Team with a refund request.',
        'Our Support Team activates a dispute form, which you have to fill out indicating the reasons for the refund.',
        'Our Quality Assurance Department checks the papers, comparing the issues you’ve indicated and the result, and issues a resolution. If your request is justified, they will advise on the sum of the refund recommended.',
        'The resolution is sent to the Billing Department. They send a refund request to PayPal (our payment system).',
        'PayPal refunds money to your account.',
        'According to our Terms of Use and PayPal policy, the refund procedure in any of the above-mentioned cases takes up to 72 hours (3 business days).',
        'What Does All Inclusive Application Job Package Include?',
        'All Inclusive Application Job Package',
        'actually means ALL-inclusive. It comprises',
        'CV/Resume Writing',
        '+ ',
        'Cover Letter Writing',
        '+',
        'LinkedIn Profile Editing',
        '+ ',
        'CV/Resume custom design',
        'pages',
        'Terms Of Service',
        'Privacy Policy',
        'Refund policy',
        'delivery policy',
        'about us',
        'About us',
        'Facebook',
        'Twitter',
        'Linked',
        'In',
        'Youtube',
        ' 2023 © ',
        '. All Rights Reserved. | Call us at: 1 917 900 1189',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',


 



                ]
];

$media =[
     "HomePage" => [
        'images/ic/magician-hat.svg',
        'images/ic/review.svg',
        'images/ic/quill-drawing-a-line.svg',
        'images/ic/interview.svg',
        'images/svg/logos/bcg.png',
        'images/svg/logos/amazonn.svg',
        'images/svg/logos/paypal.svg',
        'images/svg/logos/hp.svg',
        'images/svg/logos/pg.svg',
        'images/svg/logos/veritas.svg',
        'images/svg/logos/adidas.svg',
        'images/svg/logos/boeing.svg',
        'images/person/med_2.jpg',
        'images/person/med_3.jpg',
        'images/person/med_1.jpg',
        'images/ic/review.svg',
        'images/ic/linkedin.svg',
        'images/ic/notepad.svg',
        'images/ic/documents.svg',
        'images/ic/cv-file-interface-symbol.svg',
        'images/ic/light-bulb.svg',
        'images/ic/highest-earners-in-business.svg',
        'images/ic/edit.svg',
        'images/person/olia-mini.jpg',
        'images/ic/head_robic.svg',
        'images/person/olia-mini.jpg',
        'images/ic/head_robic.svg',
        'images/person/olia-mini.jpg',
        'images/ic/head_robic.svg'
       
       
 



        ]

];
