<?php
$content = [
     "HomePage" => [
        'Home',
        'Features',
        'Pricing',
        'Contact Us',
        'SEO Agency That&nbsp;',
        'Ranks&nbsp;',
        'Clients Around the World',
        'SEO is ALL we do, so you know we’re good at it!',
        'Rank Your Site',
        'A Few of the Companies We’ve Helped Grow...',
        'SEO Services We Rock At',
        'We only offer SEO services that we kill it at. Therefore, the following are services that we kill it at.',
        'Search Engine Optimization',
        'Rank on the top of Google results through our market driven approach to finding the best opportunities for your business.',
        'Content',
        'Development',
        'Instead of brainstorming on whiteboards and post its, we use hard-nosed data to drive the content we develop for your site.&nbsp;',
        'Website',
        'Analytics',
        'Gain an understanding of where the new incoming traffic is coming from so your team can convert visitors into new business',
        'Digital PR',
        'Thought Leadership',
        'Build your company’s clout and thought leadership through byline contributor articles on leading industry publications',
        'Our Client Case Studies',
        '10-8 SYSTEMS',
        '256% Lift in Organic Traffic',
        'for a Public Safety &amp;',
        'Law Enforcement SaaS Startup',
        'AMPLIHIGHER',
        '1st Page Rankings',
        'and',
        '300% Sales Increase',
        ' for a',
        'Copywriting Agency',
        'SPARKHOUSE',
        'Doubled Revenue',
        'and&nbsp;',
        'Tripled Web Leads',
        'for a',
        'Video Production agency',
        'View More Case Studies',
        'SEO Awards',
        'FINALIST',
        'BEST LOW BUDGET CAMPAIGN',
        'SILVER ADDY AWARD',
        'HUBSPOT THOUGHT LEADERSHIP BLOG POST',
        'Online/Interactive Media',
        'BRONZE ADDY AWARD',
        'SOCIAL MEDIA EXAMINER THOUGHT LEADERSHIP BLOG POST',
        'Online/Interactive Media',
        'SEO&nbsp;',
        'Signature Solution',
        'Every client we work with goes through all seven steps of our signature process, ensuring that they receive a proper SEO plan that aligns with their business’s goals.&nbsp;',
        'SEO Signature Solution is an in-depth seven-step process that we use with all the clients and businesses we interact with.',
        'The',
        'SEO Signature Solution is an in-depth seven-step process that we use with all the clients and businesses we interact with.',
        'Read About Our Signature Solution',
        'About',
        'is an Orange County SEO consulting agency helping construct powerful long term SEO strategies for our clients. We develop close relationships with our clients to leverage their industry experience with our own intimate knowledge of the search landscape to create truly competitive SEO strategies.&nbsp;',
        'Our SEO Knowledge Has Been Featured In',
        'Don’t believe us?',
        'Maybe these guys will convince you!',
        'Sidney Karanja',
        'CEO, Savostore',
        '’s understanding of SEO is amazing. They understand what they are doing and help develop strategies revolving around our unique business.',
        'Mikko Salokangas',
        'Head of Development, Vincit',
        'They really understand the culture and business of our company and are always looking for new ways to improve and get even better results. Overall, we’ve received a really high quality and professional service from',
        '.',
        'SPENCER SHAHIDZADEH',
        'President,',
        'Catalytic Consulting',
        'I find their ability to start a foundation, maintain that foundation, then scale that foundation extremely impressive. Their holistic approach to the SEO space is what sets',
        'apart.',
        'Kevin Ruef',
        'Director of Business Ops, 10-8 Systems',
        'Very agile company. Not only do they move quickly, but they’re very adaptable for any changes. We’ve really appreciated the constant updates and presentations to track our progress.',
        'Nick&nbsp;',
        'LEIGHTON',
        'Owner, TAB Socal',
        'Since the partnership began, the rankings are significantly higher on Google.',
        '’s modern tactics and smooth workflow has fostered a positive partnership.&nbsp;',
        'Michael&nbsp;',
        'Marketing, International Embedded Computing Company&nbsp;',
        'IMX8M Plus',
        '&nbsp;and&nbsp;',
        'the nxp imx.8 family',
        '. These are our big ticket items and have really helped us get the product out there.&nbsp;',
        'Are you ready to finally figure out',
        'Search Engine Optimization?',
        'Work With',
        'Address',
        '2852 W. Bridgeport Ave&nbsp;',
        'Anaheim, CA 92804',
        'Phone Number',
        '714 872-8890',
        'Email Address',
        'info@',
        'Terms Of Service',
        'Privacy Policy',
        'Refund policy',
        'delivery policy',
        'about us',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',












 



                ]
];

$media =[
     "HomePage" => [
        '/wp-content/uploads/2022/04/White.png',
        '/wp-content/uploads/2019/10/Vincit_logo_red_Large.png',
        '/wp-content/uploads/2022/08/gigasavvy-logo.jpeg',
        '/wp-content/uploads/2022/08/sparkhouse-black.png',
        '/wp-content/uploads/2022/08/saratech_logo_2x.png',
        '/wp-content/uploads/2022/08/ebm-logo.png',
        '/wp-content/uploads/2022/04/60efd1ce3ab7112f21596e6c_Brandlogo-p-500.png',
        '/wp-content/uploads/2022/08/10-8-systems-on-black.png',
        '/wp-content/uploads/2022/07/ee61a78e2de9e4d1d33e2bb9631a8e51-768x576.jpeg',
        '/wp-content/uploads/2022/07/pexels-vlada-karpovich-4050290-768x512.jpeg',
        '/wp-content/uploads/2022/04/o-2-768x511.jpg',
        '/wp-content/uploads/2022/08/pexels-anna-shvets-6250940-scaled.jpeg',
        '/wp-content/uploads/2022/08/US-Search-Awards-2022-Finalist-Badge-300x95.png',
        '/wp-content/uploads/2020/04/American_Advertising_Federation.svg-1-212x100.png',
        '/wp-content/uploads/2020/04/American_Advertising_Federation.svg-1-212x100.png',
        '/wp-content/uploads/2020/02/zupokhoo-e1581129589471.jpg',
        '/wp-content/uploads/2019/10/Mark-White.png',
        '/wp-content/uploads/2022/07/Screen-Shot-2022-07-05-at-7.45.25-PM.png',
        '/wp-content/uploads/2022/07/Screen-Shot-2022-07-05-at-7.47.02-PM.png',
        '/wp-content/uploads/2022/09/Google_2015_logo.svg_-300x101.png',
        '/wp-content/uploads/2022/09/Screen-Shot-2022-09-07-at-6.26.12-PM-300x88.png',
        '/wp-content/uploads/2022/03/Forbes_logo.svg_.png',
        '/wp-content/uploads/2022/03/download-1-150x33.png',
        '/wp-content/uploads/2022/03/download-150x26.png',
        '/wp-content/uploads/2022/03/download-2-150x25.png',
        '/wp-content/uploads/2022/03/AAF-american-advertising-federation-768x210-1-150x41.webp',
        '/wp-content/uploads/2022/03/6f703da80e7751d830254b2c2c6efe7c-150x38.png',
        '/wp-content/uploads/2022/03/Single-Grain-logo-for-company-shirts-150x40.png',
        '/wp-content/uploads/2022/03/expertise-com-best-siding-contractors-2020-150x47.png',
        '/wp-content/uploads/2019/11/sid-prev-1-1-e1573084002630.jpg',
        '/wp-content/uploads/2020/09/1_7rSjPPOkHhrGbYMs8OXLvg.png',
        '/wp-content/uploads/2019/12/0.jpeg',
        '/wp-content/uploads/2020/09/0.jpeg',
        '/wp-content/uploads/2019/12/0-1.jpeg',
        '/wp-content/uploads/2020/09/610-6104451_image-placeholder-png-user-profile-placeholder-image-png.jpg',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',








       
       
 



        ]

];
