<?php
$content = [
     "HomePage" => [
        'Features',
        'Pricing',
        'Contact →',
        'Product',
        'Use cases',
        'Qualitative research',
        'Film &amp; production',
        'Legal &amp; criminal justice',
        'Marketing &amp; content',
        'Education &amp; training',
        'Pricing',
        'Work with video',
        'as easily as text',
        'Reduct is a collaborative transcript-based video and audio platform for reviewing, searching, highlighting, and editing content of people talking, at scale.',
        'Get a free trial →',
        'Book a demo →',
        'Maybe you’ve heard of our users at',
        'They love us at',
        'Reduct is a big part of work for',
        'Trusted by',
        'They love sharing clips from recordings at',
        'They choose the best tools at',
        'Working with video is easy at',
        'Maybe you’ve heard of our users at',
        'They love us at',
        'Reduct is a big part of work for',
        'Trusted by',
        'They love sharing clips from recordings at',
        'They choose the best tools at',
        'Working with video is easy at',
        'Maybe you’ve heard of our users at',
        'They love us at',
        'Reduct is a big part of work for',
        'Trusted by',
        'They love sharing clips from recordings at',
        'They choose the best tools at',
        'Working with video is easy at',
        'Maybe you’ve heard of our users at',
        'They love us at',
        'Reduct is a big part of work for',
        'Trusted by',
        'They love sharing clips from recordings at',
        'They choose the best tools at',
        'Working with video is easy at',
        'Powerful tools for sharing',
        'A single searchable repository',
        'Secure and accessible',
        'Powerful tools for sharing',
        'A single searchable repository',
        'Secure and accessible',
        'Powerful tools for sharing',
        'A single searchable repository',
        'Secure and accessible',
        'Powerful tools for sharing',
        'A single searchable repository',
        'Secure and accessible',
        'Powerful tools for sharing',
        'A single searchable repository',
        'Secure and accessible',
        'Powerful tools for sharing',
        'A single searchable repository',
        'Secure and accessible',
        'Powerful tools for sharing',
        'A single searchable repository',
        'Secure and accessible',
        'Powerful tools for sharing',
        'A single searchable repository',
        'Secure and accessible',
        'Interactive transcript',
        'Click on a word in the transcript—we’ll jump you right to that moment in that video. Selecting the text lets you select video. It’s like magic, but easier to use.',
        'Audio and video support',
        'We support audio and video in almost any format you can imagine. mp4, mp3, mov, wav, aac, and beyond… we’re ready for it. Hundreds of recordings? Huge files? Footage that goes for weeks? Not a problem.',
        'Up to 75GB filesize support on Advanced or Enterprise plans; 4GB on Standard.',
        'Multi-language support',
        'Reduct supports over 30 different languages, including French, Spanish, Japanese and Arabic.',
        'Zoom and web import',
        'Import directly from Google Drive, Dropbox, Usertesting, Youtube, Vimeo, and more, with just a link. Log in with your Zoom account to import your Zoom cloud recordings, without having to juggle downloads or links.',
        'Live Capture',
        'Live Capture lets you bring Zoom, Google Meet and Teams calls into Reduct, as they happen. Your entire team can highlight and comment on the live transcript, and you can share clips and assemble reels as soon as the call ends.',
        'Powerful search',
        'With everything in Reduct transcribed, search lets you dig deep into your repository. Search in one recording, or all of them. Search for exact matches using quote marks, or use our powerful, NLP-powered fuzzy-search to find relevant ideas and phrases.',
        'Transcript correction',
        'We do our best to make transcripts accurate—but sometimes we miss. Select the error, hit “correct transcript,” and make a fix. Need to correct something that’s repeated throughout a recording? Just “replace all”!.',
        'Tagging',
        'Use tags to categorize your highlights, making it easy to find key themes across your recordings.',
        'Redaction *',
        'Footage often includes sensitive information—names, faces, and that notification that popped up on a screen-share. Reduct lets you securely redact PII, and be a responsible custodian of your subjects’ information.',
        '* Advanced and Enterprise feature',
        'Strikethrough',
        'When editing a Reel, you can more quickly get to the point by cutting digressions and filler. Just select text, and press “cut,” and it’ll be skipped in the video.',
        'Realtime collaboration',
        'Everything in Reduct happens in the browser, so everything is always in sync. Follow a colleague as they review a recording, or sort themes as a group in the videoboard. It all happens in real-time, so you’re always on the same page.',
        'One-click sharing',
        'When there’s a moment you want to share, just select some transcript text and click on "Link to selection.” A sharable link to the exact location in your recording is now on your clipboard, ready to drop into Slack, Teams, Notion, email, or anywhere else.',
        'Premiere Pro plugin',
        'When you’re done assembling a rough cut in Reduct, turn it into Premiere Pro sequences with our extension, and keep working on your timeline. We use your original high quality source files, including multi-camera source sequences, letting you create polished results faster than ever.',
        'Videoboard',
        'The Videoboard is a 2d digital canvas for your highlights. You can arrange your highlights and recordings, find patterns, add notes, and create sequences—and it’s all collaborative. Build on existing frameworks like Venn diagrams or narrative structures, or work freeform. It’s the best way to do storyboarding. Or affinity mapping. Or just to see what’s in your data.',
        'More features →',
        'It’s for all sorts of teams',
        'Qualitative research →',
        'Your research will benefit from powerful tagging tools, search, and effortless editing to tell impactful stories.',
        'Filmmaking and production →',
        'Assemble a rough cut in a tenth of the time—and spend your effort telling the best story.',
        'Legal and criminal justice →',
        'Achieve better outcomes for your clients when you use Reduct to transcribe and manage video and audio evidence.',
        'Standard',
        '$',
        '24',
        '/editor, per month',
        'Access to powerful Reduct',
        'platform features.',
        '120hrs of included',
        'Every editor in your workspace adds 10hrs of monthly transcription, which is shared. So if you have 5 editors, you will have a shared pool of 50hrs of transcription to work with each month. Any overages beyond your quota are charged a-la-carte.',
        'pooled',
        'transcription',
        'If you select monthly billing, your transcription quota will refresh each month. If you choose to be billed annually, each editor will add 120hrs of transcription to your quota, which can be used at any point during the year.',
        'per year',
        ', per editor.',
        'Up to 10',
        'Commenters can view recordings and other content in a Reduct workspace, and can highlight and comment, but they can’t upload or edit.',
        'commenters',
        ', free.',
        '1080p exports.',
        'Unlimited storage; individual media file-size up to 4GB.',
        'Advanced',
        '$',
        '40',
        '/editor, per month',
        'Everything in Standard, plus...',
        'Up to 50',
        'Commenters can view recordings and other content in a Reduct workspace, and can highlight and comment, but they can’t upload or edit.',
        'commenters',
        ', free.',
        'Video and audio',
        'Our video and audio redaction allows you to remove PII from your footage, protecting it from being shared.',
        'redaction',
        'Search across projects, and combine highlights from multiple projects in your videoboards and reels.',
        'Cross-project',
        'functionality.',
        'Additional transcription export',
        'Including legal-formatted transcripts as TXT and PDF, that are compatible with most federal and state courts.',
        'formats',
        'Automate your workflows by connecting Reduct to hundreds of other services, including Airtable, Notion, Confluence, ChatGPT, Slack, and more.',
        'Zapier',
        'integrations.',
        'High resolution 4K exports.',
        'Individual media file-size support up to 75GB.',
        'Sign up for a free 14 day trial with all Advanced features, with',
        '2 hours',
        'of AI transcription included.',
        'Start a free trial →',
        'Enterprise',
        'starting at',
        '$',
        '75',
        '/editor, per month',
        'Everything in Advanced, and...',
        'SSO integration (SAML or Google-based).',
        'Advanced',
        'This includes restricting access by domain, and having unlisted projects that are invisible to other members of the workspace.',
        'access controls',
        'and',
        'Including domain- and SSO- gated links for shared reels.',
        'sharing options.',
        'SOC2 Type II and annual pentest reports.',
        'Data processing agreement accounting for',
        'The EU’s General Data Protection Regulation.',
        'GDPR',
        'California Consumer Privacy Act of 2018.',
        'CCPA.',
        'Signed MSA with a SLA, with invoiced, annual billing.',
        'Priority support.',
        'We offer several flexible models, to meet and grow with your needs.',
        'Contact sales →',
        'Try it now →',
        'Terms Of Service',
        'Privacy Policy',
        'Refund policy',
        'delivery policy',
        'about us',
        '',
        '',
        '',
        '',
        '',
        '',
        '',







  

   














                ]
];

$media =[
     "HomePage" => [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',

       
       
 



        ]

];
