<?php
$content = [
     "HomePage" => [
        'Home',
        'Pricing',
        'Contact',
        'Home',
        'Pricing',
        'Contact',
        'Enterprise resource planning',
        'The system covers the main business processes and helps to automate daily work',
        'Sign up',
        '14 d. free trial',
        'Logins in 1 min.',
        'Integration of accounting systems',
        'Invoices issued in the',
        'system are transferred to the accounting system. Warehouse balances are also synchronized with the accounting system.',
        'Rivale integration',
        'Robolabs integration',
        'Email integration',
        'system allows you to fully synchronize your email. Also link emails using BCC and CC.',
        'Email templates',
        'Inbox and send mail',
        'Access management',
        'Assign by sales',
        'Direct connection with your bank',
        'Linking Bank Accounts to',
        '. Invoices are automatically cover based on the payments received.',
        'Automatic statement import and cover',
        'The most popular banks: Swedbank, SEB, Luminor and others.',
        'Commercial offers, contracts and other documents',
        'Simple preparation of commercial offers and other documents. Automatic filling of documents according to the data in the system.',
        'PDF, Word offer formats',
        'Photo support',
        'Customization to suit your business style',
        'Warehouse stock management',
        'Stock balances are visible in real time. Planning and placing orders with suppliers directly from the system.',
        'Synchronization of balances with the accounting system',
        'Assembly of goods',
        'Inventory',
        'Orders to suppliers',
        'Signing of contracts',
        'Document signing Smart ID and m. signature in',
        'system. Possibility to send an invitation to customers - sign documents.',
        'Smart ID',
        'M. Signature',
        'Sales management and time planning',
        'Ability to track which stage of sales you are with a particular customer. Simple task planning, sales-related communication and traffic tracking.',
        'Time management',
        'Calendar',
        'Commercial offers',
        'Delegation of tasks',
        'KPIs',
        'IP telephony integration',
        'Real-time call transfer to',
        '. Ability to monitor call statistics and listen to conversations.',
        'Tele2 Station',
        'Kalbu.lt',
        'Process',
        'System implementation steps',
        'Step by step how to start using',
        '!',
        'Step 1',
        'Registration and free trial',
        'We are planning a remote meeting to discuss your needs.',
        'Step 2',
        'Needs analysis and system presentation',
        'We explain your needs, answer your questions and introduce the system.',
        'Step 3',
        'Customization of the system',
        'We adapt the functionality of the system to your needs.',
        'Step 2',
        'System usage training',
        'We train you and your team to use the system.',
        '14-days free trial',
        'Logins in 1 min.',
        'Cancel anytime',
        'Basic',
        '8',
        '€/month',
        'per user per month (price without VAT)',
        'Calendar',
        'Events and activity',
        'Companies and contact management',
        'Lithuanian companies database',
        'History of communication with the client',
        'Sales planning tools',
        'Sending emails via BCC',
        'Email templates',
        'Cold contacts',
        'Help via email',
        'Try it',
        'Professional',
        '22',
        '€/month',
        'per user per month (price without VAT)',
        'Everything from Free plan',
        'Google Calendar integration',
        'Google Email(Gmail integration)',
        'Office 365 integration',
        'Payment management',
        'Automatic document generation',
        'Reports',
        'Service',
        'Product catalog',
        'Support via phone and email',
        'Try it',
        'Premium',
        '29',
        '€/month',
        'per user per month (price without VAT)',
        'Everything from Professional plan',
        'Order management for suppliers',
        'Recommended orders',
        'Goods receiving',
        'Warehouse position management',
        'Issuance of goods',
        'Stock balances',
        'Write-offs of goods',
        'Inventory',
        'Try it',
        '*14% discount for annual payments',
        'Wide possibilities',
        'Integrations make your job easier',
        'View all integration',
        'Let’s Try! Get Free demo version',
        'Start Your 14-Day Free Trial',
        'Start Your 14-Day Free Trial',
        'Sign up',
        'Sign up for our newsletter and be the first to know about the news.',
        'Subscribe',
        'Contact',
        'Tel.:',
        '+370 663 52000',
        'Email:',
        'info@',
        'Mon. - Fri.:',
        '8:00 - 17:00',
        'pages',
        'Terms Of Service',
        'Privacy Policy',
        'Refund policy',
        'delivery policy',
        'about us',
        '&copy; 2023',
        '| Empera LT, UAB',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',




 



                ]
];

$media =[
     "HomePage" => [
        '/wp-content/themes/spincrm-v4/img/logo-white.svg',
        '/wp-content/themes/spincrm-v4/img/logo.svg',
        '/wp-content/themes/spincrm-v4/img/logo.svg',
        '/wp-content/themes/spincrm-v4/img/hero-dot-bg.png',
        '/wp-content/themes/spincrm-v4/img/sistema-3.png',
        '/wp-content/themes/spincrm-v4/img/sistema-5.png',
        '/wp-content/themes/spincrm-v4/img/sistema-1.png',
        '/wp-content/themes/spincrm-v4/img/clients/nando.svg',
        '/wp-content/themes/spincrm-v4/img/clients/topo-centras.svg',
        '/wp-content/themes/spincrm-v4/img/clients/mai-cee.svg',
        '/wp-content/themes/spincrm-v4/img/clients/treka.svg',
        '/wp-content/themes/spincrm-v4/img/clients/kauno-kolegija.svg',
        '/wp-content/themes/spincrm-v4/img/clients/megrame-international.svg',
        '/wp-content/themes/spincrm-v4/img/clients/svaros-broliai.png',
        '/wp-content/themes/spincrm-v4/img/clients/foros.svg',
        '/wp-content/themes/spincrm-v4/img/shape/dot-big-square.svg',
        '/wp-content/themes/spincrm-v4/img/shape/dot-big-square.svg',
        '/wp-content/themes/spincrm-v4/img/shape/dot-big-square.svg',
        '/wp-content/themes/spincrm-v4/img/shape/dot-dot-wave-shape.svg',
        '/wp-content/themes/spincrm-v4/img/integations/siauliu_bankas.png',
        '/wp-content/themes/spincrm-v4/img/integations/swedbank.png',
        '/wp-content/themes/spincrm-v4/img/integations/revolut.png',
        '/wp-content/themes/spincrm-v4/img/integations/rivile.png',
        '/wp-content/themes/spincrm-v4/img/integations/luminor.svg',
        '/wp-content/themes/spincrm-v4/img/integations/robolabs.png',
        '/wp-content/themes/spincrm-v4/img/integations/power-bi.svg',
        '/wp-content/themes/spincrm-v4/img/integations/seb.png',
        '/wp-content/themes/spincrm-v4/img/integations/zapier-full.svg',
        '/wp-content/themes/spincrm-v4/img/integations/marksign.svg',
        '/wp-content/themes/spincrm-v4/img/integations/outlook.svg',
        '/wp-content/themes/spincrm-v4/img/integations/gmail.svg',
        'assets/img/page-header-bg.svg',
        '/wp-content/themes/spincrm-v4/img/logo-white.svg',
        '/wp-content/themes/spincrm-v4/img/logo.svg',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',


       
       
 



        ]

];
