<?php
$content = [
     "HomePage" => [
      'Home',
      'Contact',
      'STRATEGIC GROWTH',
      'is an art form.',
      'SEO',
      'Facebook Ads',
      'Content Marketing',
      'Google Ads',
      'PPC Campaigns',
      'Recruitment Marketing',
      'Name it. We’re on it.',
      'Wouldn’t you like to get up bright and breezy every morning without fretting about your company’s growth?',
      'Choose the worry-free option.',
      'You’re just a click away from that reality.',
      'Get my growth strategy',
      'Follow in the footsteps of our satisfied partners: ',
      'Follow in the footsteps of our satisfied partners:',
      'Why',
      'Digiffic is not your regular agency. It’s a digital traffic agency capable of driving your online presence through the roof! Our results stem from skill and passion, so you can be confident you’re in the best hands. And, to make sure that your brand can grow effectively, you’ll be treated with a tailored approach to suit your individual needs, and you’ll have access to a blow-by-blow account at every step of the way.',
      'But don’t just take our word for it.',
      'Marvin',
      'Marketing &amp; Sales Lead, Excubate Corporate Startups',
      '"',
      'showcases a solid understanding of the client’s business model. Dynamic and dedicated, they are not afraid to think outside the box and put in extra effort to help the client achieve their goals. They are flexible, pragmatic, and knowledgeable in marketing best practices."',
      'Piotr',
      'Managing Director at Motty Polska',
      '"',
      'leads a solid process, increasing the client’s sales and traffic to its website. The client also noted a significant increase in their conversion rate. The team provided easy communication throughout the engagement."',
      'Mack',
      'CEO at Apollo Scooters',
      '"',
      'has delivered praiseworthy results month over month. They had a flexible and seamless way of cooperating with the client, remaining responsive throughout the process. Most of all, they’ve had a solution-oriented process that has earned the client’s trust."',
      'Debbie',
      'CEO at Narver Management',
      '"They’re very insightful and truly experts on Google Ads. They understood our needs, provided a customized strategy and implemented it. They provided excellent communication throughout the project, and were always analyzing and improving the ads."',
      'Our approach to strategic growth!',
      'A step-by-step process for you to discover.',
      'Comprehensive Analysis',
      'You’ll get a comprehensive analysis of user behavior, market visibility, estimated conversion cost, and campaign scalability. We’ll make every effort to ensure that both parties understand how we will reach your prospects and the cost of each conversion.',
      'Concerted Strategy',
      'We may understand the digital marketing area, but you know your customers. So, you can only get the most efficient and scalable selling strategy when we work hand in hand.',
      'Campaign Draft',
      'We’ll guide you through every step to ensure that all parties are on the same page. From the strategy, copy, and visuals to estimated KPIs or optimization methods. Only when you fully understand our master plan can we proceed.',
      'On-Going Support',
      'Launching the campaign is only the beginning. Then the real fun begins. We’ll work on your project daily to fully realize your potential. And we’ll develop new methods to get ahead of your competition.',
      'Transparent Communication',
      'We’re here to answer every question you may have and give a detailed account of everything we’ve done on your project. Our goal is not only to increase your revenue but also to make sure that you know how it happens.',
      'Contact us!',
      'To learn how we can help you reach your goals. World domination? Not a problem. But we also deal with mundane stuff, like marketing. So, let’s talk and see what we can do for you.',
      'Contact us!',
      'Name',
      'Email',
      'Your message:',
      '“Life is change.',
      'Growth is optional. Choose Digiffic.”',
      'Home',
      'Terms Of Service',
      'Privacy Policy',
      'Refund policy',
      'delivery policy',
      'about us',
      'Linked In',
      'Facebook',
      '',
      '',
      
                ]
];

$media =[
     "HomePage" => [
   '/hubfs/Digiffic%202022/logo.svg',
   '/hs-fs/hubfs/Group%20253%20(1).png?width=1501&amp;height=1312&amp;name=Group%20253%20(1).png',
   '/hs-fs/hubfs/Digiffic%202022/logo-clutch-white@2x.png?width=238&amp;height=238&amp;name=logo-clutch-white@2x.png',
   '/hs-fs/hubfs/Digiffic%202022/logo-bitclude@2x.png?width=138&amp;height=54&amp;name=logo-bitclude@2x.png',
   '/hs-fs/hubfs/Digiffic%202022/logo-zalaris@2x.png?width=208&amp;height=41&amp;name=logo-zalaris@2x.png',
   '/hs-fs/hubfs/Digiffic%202022/logo-microsoft@2x.png?width=254&amp;height=55&amp;name=logo-microsoft@2x.png',
   '/hs-fs/hubfs/Digiffic%202022/logo-zalando@2x.png?width=212&amp;height=41&amp;name=logo-zalando@2x.png',
   '/hs-fs/hubfs/Digiffic%202022/logo-netguru@2x.png?width=134&amp;height=25&amp;name=logo-netguru@2x.png',
   '/hs-fs/hubfs/Mask%20group%20(11).png?width=476&amp;height=218&amp;name=Mask%20group%20(11).png',
   '/hs-fs/hubfs/Mask%20group%20(10).png?width=546&amp;height=182&amp;name=Mask%20group%20(10).png',
   '/hs-fs/hubfs/Mask%20group%20(9).png?width=496&amp;height=97&amp;name=Mask%20group%20(9).png',
   '/hs-fs/hubfs/Mask%20group%20(8).png?width=510&amp;height=167&amp;name=Mask%20group%20(8).png',
   '/hs-fs/hubfs/Mask%20group%20(7).png?width=516&amp;height=271&amp;name=Mask%20group%20(7).png',
   '/hs-fs/hubfs/Digiffic%202022/white-bg-element.jpg?width=1636&amp;height=1323&amp;name=white-bg-element.jpg',
   '/hubfs/Digiffic%202022/logo-sign-dark.svg',
   '/hs-fs/hubfs/Marvin-Eberhard%20(1).jpeg?width=400&amp;height=400&amp;name=Marvin-Eberhard%20(1).jpeg',
   '/hs-fs/hubfs/Digiffic%202022/article3@2x.png?width=358&amp;height=358&amp;name=article3@2x.png',
   '/hs-fs/hubfs/Digiffic%202022/article1@2x.png?width=358&amp;height=358&amp;name=article1@2x.png',
   '/hubfs/Digiffic%202022/arrow-left.svg',
   '/hubfs/Digiffic%202022/arrow-right.svg',
   '/hs-fs/hubfs/Digiffic%202022/card1@2x.png?width=237&amp;height=181&amp;name=card1@2x.png',
   '/hs-fs/hubfs/Digiffic%202022/card2@2x.png?width=195&amp;height=196&amp;name=card2@2x.png',
   '/hs-fs/hubfs/Digiffic%202022/card3@2x.png?width=186&amp;height=173&amp;name=card3@2x.png',
   '/hs-fs/hubfs/Digiffic%202022/card4@2x.png?width=138&amp;height=156&amp;name=card4@2x.png',
   '/hs-fs/hubfs/Digiffic%202022/card5@2x.png?width=223&amp;height=202&amp;name=card5@2x.png',
   '/hubfs/Digiffic%202022/logo-sign-light.svg',
   '/hubfs/Digiffic%202022/icon-linkedin.svg',
   '/hs-fs/hubfs/Clutch%20(1).png?width=70&amp;height=70&amp;name=Clutch%20(1).png',
   '/hubfs/Digiffic%202022/icon-facebook.svg',
   '',
   '',
   ''


     ]

];
