<?php
$content = [
     "HomePage" => [
      'Features',
      'Pricing',
      'Contact',
      'Get the results you need',
      'without the nonsense.',
      'Digital marketing is murky, confusing, and frustrating. We’re entrepreneurs (like you) focused on value, transparency, and authenticity.&nbsp;',
      'We’re on a mission to make marketing more effective.&nbsp;',
      'We had a bunch of buzzwords we wanted to put here about what we do and how we work.',
      'How about this? You bring your own buzzwords and our team of good people will work our asses off to help grow your business. 🚀',
      'Ready to dive in? 💯',
      '"They really care. They put a lot of effort into know my company and getting to know the staff and using that to help build our brand. We would not be where we are today as a company without their help."',
      '- Ryan Lermitte, Umbrella Property Services',
      'I want to:',
      'Increase Transactions & Revenue',
      'GET CASH FLOWING',
      'Build Traffic & Increase',
      ' Leads',
      'FILL YOUR PIPELINE',
      'Rank Higher on Google',
      'INCREASE WEBSITE TRAFFIC',
      'Grow My Donation Base',
      'DO MORE GOOD',
      'We call BS.',
      'Can we level with you?',
      '(We’re going to. Because that’s how we roll.)',
      'As an industry, digital marketing is a bit of a mess.',
      'The acronyms.',
      'The algorithms.',
      'The absurd invoices.',
      'The arrogance!',
      'It’s allllllmost like digital marketers don’t want you to understand what’s going on, because then they’d have to, well, do what they said they’d do.',
      'You deserve better.',
      'Tell us what you need, we work our tails off to make it happen, and we keep you in the loop the whole way',
      'Trusted by:',
      'When our clients win, we win.',
      'We&rsquo;re a bit like proud parents, really.',
      'Our Work',
      'Everipe',
      'E-Commerce',
      'Not only did we help validate Everipe’s product and messaging, but also their rapid success attracted interest from multiple distribution and shopping channels, including Walmart.',
      '10 Thousand Windows',
      'Nonprofit',
      'Digital Hot Sauce developed paid marketing campaigns on Facebook and Instagram to drive brand awareness. We also set up remarketing* campaigns and email marketing to help nurture leads to become new donors.',
      'Birch Tree Care',
      'Local Service',
      'Birch Tree Care now has a steady flow of leads, with customers experiencing a five-week booking window.',
      'We’re obsessed with ROI*.',
      'It’s a good process. But what happens inside those four steps is where the spice hits the salsa. So to speak.',
      'OUR APPROACH',
      '*We’re generally allergic to alphabet soup, but we do love this particular acronym.',
      'Popular blog posts',
      'How Amazon Reviews can Increase Your Conversion Rate',
      'Read more',
      'Kyle Harms',
      'A Beginner’s Guide to Google Tag Manager for Small Businesses',
      'Read more',
      'Kyle Harms',
      'Google Analytics for Businesses: Here’s What You Really Need to Know',
      'Read more',
      'Kyle Harms',
      'ALL POSTS',
      'Our partners',
      'Location',
      '2 &ndash; 228 West 5th Ave, Vancouver, BC V5Y 1J4',
      'Contact',
      'spicy@',
      'Terms Of Service',
      'Privacy Policy',
      'Refund policy',
      'delivery policy',
      'about us',
      'Terms Of Service',
      'Privacy Policy',
      'Refund policy',
      'delivery policy',
      'about us',
      '&copy;2021 Digital Hot Sauce. All rights reserved.',
      'Privacy Policy',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
      
                ]
];

$media =[
     "HomePage" => [
   '/wp-content/uploads/2023/03/DHS-SEO-Services-Testimonial-Quotation-Marks-01-1.png',
   '/wp-content/uploads/2023/03/DHS-SEO-Services-Testimonial-Quotation-Marks-02-1.png',
   '/wp-content/uploads/2021/10/Red-DHS-Logo.svg',
   '/wp-content/uploads/2021/09/E-commerce-Sales.jpg',
   '/wp-content/uploads/2021/09/Increase-Traffic.jpg',
   '/wp-content/uploads/2021/09/Increase-Google.jpg',
   '/wp-content/uploads/2021/09/Increase-Donations.jpg',
   '/wp-content/uploads/2021/10/samantha-sophia-C9CM5g0mEbc-unsplash-scaled.jpg',
   '/wp-content/uploads/2021/11/images-1.png',
   '/wp-content/uploads/2021/11/8472717-logo-1.png',
   '/wp-content/uploads/2021/11/dailyhive-color.svg',
   '/wp-content/uploads/2021/11/NALogoHoriz.png',
   '/wp-content/uploads/2021/11/sbbc-logo.svg',
   '/wp-content/uploads/2021/11/SPBShopify_fa33efa1-edbf-4c90-8085-0fc176a34f15_600x.png',
   '/wp-content/uploads/2021/11/1519887175006.jpeg',
   '/wp-content/uploads/2021/11/RMHBC-Logo.jpeg',
   '/wp-content/uploads/2021/09/Unbelievaberry.png',
   '/wp-content/uploads/2021/09/girl-img.jpg',
   '/wp-content/uploads/2021/09/image-0353.jpeg',
   '/wp-content/uploads/2022/05/Amazon-Reviews-YT-Video.jpg',
   '/wp-content/uploads/2021/10/iStock-1270054169.jpg',
   '/wp-content/uploads/2021/10/iStock-1304750150.jpg',
   '/wp-content/uploads/2021/09/callrail-logotype.png',
   '/wp-content/uploads/2021/09/fb-1.png',
   '/wp-content/uploads/2021/09/google-partner.png',
   '/wp-content/uploads/2021/10/iconmonstr-linkedin-4-32.png',
   '/wp-content/uploads/2021/10/iconmonstr-instagram-14-32.png',
   '/wp-content/uploads/2021/10/iconmonstr-twitter-4-32.png',
   '',
   ''


     ]

];
