<?php
$content = [
     "HomePage" => [
      '+1 (408) 320-0380',
      'Toggle navigation',
      'Features',
      'Pricing',
      'Free Self Hosted and',
      'Cloud CRM Software!',
      'DEMO',
      'What is this?',
      'is a web application that allows users to see, enter and evaluate all your company relationships regardless of the type. People, companies, projects or opportunities &mdash; all in an easy and intuitive interface.',
      '50,000+',
      'companies using',
      '163',
      'countries of the world',
      '9',
      'years since first release',
      'Where is it used?',
      'Wholesale and retail trade',
      'E-commerce',
      'Banking',
      'Call-centers',
      'Manufacturing',
      'Education',
      'Travel & Tourism',
      'Real Estate',
      'Healthcare',
      'Insurance',
      'How to Start',
      'Seize the moment and take a step forward to empower your business. Find out the advantages of cloud-hosted and on-premise solutions and choose the right one for your business.',
      'Learn more',
      'Explore the benefits',
      'Skyrocket your sales, transform marketing strategy and deliver an exceptional customer experience with',
      '.',
      'Read more',
      'Get Started Now!',
      'Terms of Service',        
      'Privacy Policy',
      'Refund Policy',
      'delivery policy',
      'About Us',
      'Follow us',
      '© 2023',
      '. All Rights Reserved.',
      '',






                ]
];

$media =[
     "HomePage" => [
        '/images/espocrm-logo.svg',
        '/images/espocrm-preview.jpg',
        '/images/espocrm-preview.mp4',
        'images/grey-section-footer-shadow.png',
        'images/sales.png',
        'images/e-commerce.png',
        'images/bank.png',
        'images/call-center.png',
        'images/manufacturing.png',
        'images/education.png',
        'images/travel-agencies.png',
        'images/real-estate.png',
        'images/medicine.png',
        'images/insurance.png',
        'images/grey-section-header-shadow.png',
        'images/grey-section-footer-shadow.png',
        'images/represented.jpg',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',



        ]

];
