<?php
$content = [
     "HomePage" => [
        'Features',
        'Pricing',
        'Contact Us',
        'See why global brands',
        'love',
        '4.6',
        '4.5',
        'Before using',
        ', I would spend a whole day preparing a detailed report.',
        'Now with',
        ', it takes me 15 minutes tops.',
        'Sena Arısoy',
        ', Engage Istanbul',
        'We’ve been using',
        ' for 5 years, and there has not been a day we didn’t get a reply within 10–15 minutes.',
        'Their response rate is simply the best in the market.',
        'Osman Zeren',
        ', Havas Group',
        'You can be a part of people’s lives as long as you make their lives easier.',
        'Thus,',
        'became our digital solution partner.',
        'Duygu Inci Alkan',
        ', Eczacıbaşı',
        'We increased efficiency by integrating',
        '’s API and made it easy to engage with our customers. ',
        'Their support showed us that we had chosen the right partner for the job.',
        'Yusuf Kocaer',
        ', Felece',
        'helped me to automate routine and manual tasks',
        ', so I could focus on strategic and creative planning.',
        'Zeynep Serra Avan',
        ', AnnounceKit',
        'With the help of',
        ',',
        'we increased our engagement rates by 2.5 times',
        'within a 6 months period.',
        'Mehmet Kecili',
        ', VMLY&amp;R',
        'We’ve been using',
        'for 5 years, and there has not been a day we didn’t get a reply within 10–15 minutes.',
        'Their response rate is simply the best in the market.',
        'Osman Zeren',
        ', Havas Group',
        'Empower your team',
        'Bring success across social media channels',
        'No credit card required',
        '14-day free trial',
        'Cancel anytime',
        'Thousands of users love managing social media with',
        'All plans cover all modules, with room to grow',
        'Our pricing plans include everything social media marketers need to publish, engage, analyze, listen, and monitor competitors.',
        'Pro',
        '$',
        '99',
        '/mo',
        'when billed monthly',
        'Create account',
        '1 user',
        '10 pages',
        'See details',
        'All modules',
        '— Publish, Engage, Analytics, Competitor Analysis, Listen',
        '1-1 Onboarding and training',
        'Live chat support',
        'Data retention:',
        '&nbsp;6 months',
        'Optional add-ons',
        'Users:',
        'Not available',
        'Pages:',
        '&nbsp;Not available',
        'Business',
        '$',
        '199',
        '/mo',
        'when billed monthly',
        'Create account',
        'Unlimited users',
        '15 pages',
        'See details',
        'Everything in Pro',
        ', plus:',
        'Data retention:',
        '12 months',
        'Assignment and approval workflows',
        'Team performance reports',
        'Multilevel user roles',
        'Optional add-ons',
        'Users:',
        'Free and unlimited',
        'Pages:',
        '&nbsp;$15/mo',
        'Mentions:',
        '&nbsp;Custom',
        'Enterprise',
        'Contact sales for pricing',
        'Contact sales',
        'Unlimited users',
        'Unlimited pages',
        'See details',
        'Everything in Business',
        ', plus:',
        'Data retention:',
        '&nbsp;24 months',
        'Dedicated account manager',
        'Enhanced API',
        'Audit logs',
        'Password security policy',
        'Custom contract and invoicing',
        'Optional add-ons',
        'Users:',
        'Free and unlimited',
        'Pages:',
        '&nbsp;Custom',
        'Mentions:',
        '&nbsp;Custom',
        'features',
        'Compare plans',
        'Pro',
        'Business',
        'Enterprise',
        'Compare plans',
        'Pro',
        'Business',
        'Enterprise',
        'Key features',
        'Users',
        'Connect up to the number of users with full or limited access to contribute content to your',
        'profile.',
        '1',
        'Unlimited users',
        'Unlimited users',
        'Social pages',
        'Connect up to the number of social media pages (including competitors’ pages for monitoring), which you can distribute according to your needs.',
        '10',
        '15',
        'Custom',
        'Optional add-ons',
        'Create a plan that suits your needs. Add additional pages and users while still staying on the same pricing plan.',
        'Users: not available',
        'Pages: not available',
        'Users: Free and unlimited',
        'Pages: $15/mo',
        'Users: Free and unlimited',
        'Pages: Custom',
        'Other benefits',
        'Support',
        'Our team is always here to help you via one-to-one video calls, self-service knowledge bases, email, and live chat.',
        '1-1 Onboarding',
        'and training',
        'Live chat',
        'Email',
        'Help center',
        '1-1 Onboarding',
        ' and training',
        'Live chat',
        'Email',
        'Help center',
        '1-1 Onboarding',
        'and training',
        'Live chat',
        'Email',
        'Help center',
        'Account manager',
        'Data retention',
        'The amount of time we retain your social media data for reporting.',
        '6 Months',
        '12 Months',
        '24 Months',
        'Integrations',
        '(Coming Soon)',
        'Empower your',
        ' account with Zapier + Intercom + Slack integration for an effortless workflow.',
        'Zapier',
        'Slack',
        'Zapier',
        'Slack',
        'Zapier',
        'Slack',
        'Enhanced API',
        'Integrate up-to-date social media data into your internal tools and workflows.',
        'Not available',
        'Not available',
        'Social networks',
        'Facebook',
        'We support Facebook Business Pages.',
        'Instagram',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',




 



                ]
];

$media =[
     "HomePage" => [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',


       
       
 



        ]

];
