<?php
$content = [
     "HomePage" => [
      'Pricing',
      'About us',
      'Pricing',
      'About us',
      'Workspace Builder',
      'for every team',
      'Projects',
      'Suppliers',
      'HR',
      'Contractors',
      'CRM',
      'Task Management',
      'Mailapp',
      'Chat',
      '+',
      'Simple, Flexible and Powerful.',
      'Create anything you need without coding knowledge.',
      'Try',
      'free',
      'Request a demo',
      'Great solution for:',
      'The best solution for team management',
      'Create your own software for all business processes in minutes. You can rapidly go from idea to realization and even making changes does not require a lot of effort.',
      'Create workspace',
      'for every team',
      'Our builder allows the user to create new sections and objects in just a few seconds.',
      'Links',
      'between team',
      'Set up the rules for working with them and links between objects and sections.',
      'Add',
      'functionality',
      'Add only the necessary functionality to the objects.',
      'Integrations',
      'Integrate with us easily by utilizing our Marketplace and adding your tools.',
      'will remain your go-to source for everything, with your team as the beneficiary of the integration.',
      'And many others',
      'Build the',
      'with us!',
      'Would you like additional functionality',
      'or integration for your team?',
      'Order the development of the functionality or integrations you need and build an',
      'with us.',
      'Discuss',
      'Pricing',
      'Basic',
      '$5',
      'per user/month',
      'billed annually',
      '$8 billed monthly',
      'Try it free',
      'Up to 5 users',
      '5 sections in the builder',
      '2 pipeline or board in one section',
      '15 custom fields',
      'Integration with Salesforce',
      'Automation',
      'See all plan features',
      'Business',
      '$9',
      'per user/month',
      'billed annually',
      '$15 billed monthly',
      'Try it free',
      'Up to 30 users',
      '10 sections in the builder',
      '5 pipeline or board in one section',
      '100 custom fields',
      'Integration with Salesforce',
      'Automation',
      'See all plan features',
      'Premium',
      '$19',
      'per user/month',
      'billed annually',
      '$25 billed monthly',
      'Try it free',
      'Up to 50 users',
      '30 sections in the builder',
      '20 pipeline or board in one section',
      '300 custom fields',
      'Integration with Salesforce',
      'Automation',
      'See all plan features',
      'Enterprise',
      'Contact us to discuss a customized solution for your business',
      'Contact us',
      'Unlimited users',
      '100 sections in the builder',
      '100 pipeline or board in one section',
      '600 custom fields',
      'Integration with Salesforce',
      'Automation',
      'See all plan features',
      '100GB',
      'Disk storage',
      '$7',
      '/month',
      '1000GB',
      'Disk storage',
      '$20',
      '/month',
      '3000GB',
      ' Disk storage',
      '$50',
      '/month',
      'Need more storage?',
      'Contact us',
      'Start with a ready-made solution &amp; modify it however you need',
      'See all solutions',
      'Need a unique solution for your business? Let us create it for you.',
      'Contact us',
      'Try',
      'today',
      'Get started for free.',
      'Add your whole team as your needs grow.',
      'Try',
      'free',
      'On a big team?',
      'Contact sales',
      'Terms Of Service',
      'Privacy Policy',
      'Refund policy',
      'delivery policy',
      'about us',
      '© 2022',
      '© 2022',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',

                ]
];

$media =[
     "HomePage" => [
   '/images/Sections/Common/keep_calm_small.svg',
   '/images/Sections/Common/keep_calm_large.svg',
   'images/Sections/MainPage/schemas.webp',
   '/images/Sections/MainPage/CreateWorkspace/create_workspace.svg',
   '/images/Sections/MainPage/LinksBetweenTeam/links_between_team.svg',
   '/images/Sections/MainPage/AddFunctionality/functionality.svg',
   '/images/Sections/MainPage/Integrations/salesforce.svg',
   '/images/Sections/MainPage/Integrations/hubspot.svg',
   '/images/Sections/MainPage/Integrations/pipedrive.svg',
   '/images/Sections/MainPage/Integrations/whatsapp.svg',
   '/images/Sections/MainPage/Integrations/facebook_messenger.svg',
   '/images/Sections/MainPage/Integrations/instagram.svg',
   '/images/Sections/MainPage/Integrations/gmail.svg',
   '/images/Sections/MainPage/Integrations/zoom.svg',
   '/images/Sections/MainPage/Integrations/mailchimp.svg',
   '/images/Sections/MainPage/Integrations/twilio.svg',
   '/images/Sections/MainPage/Integrations/telegram.svg',
   '/images/Sections/MainPage/Integrations/viber.svg',
   '/images/Sections/MainPage/Integrations/skype.svg',
   '/images/Sections/MainPage/Integrations/twitter.svg',
   '/images/Sections/MainPage/Integrations/wordpress.svg',
   '/images/Sections/MainPage/Integrations/asana.svg',
   '/images/Sections/MainPage/Integrations/facebook.svg',
   '/images/Sections/MainPage/Integrations/wechat.svg',
   '/images/Sections/MainPage/Integrations/pandadoc.svg',
   '/images/Sections/MainPage/Integrations/dropbox.svg',
   '/images/Sections/MainPage/Integrations/slack.svg',
   '/images/Sections/MainPage/Integrations/jira.svg',
   '/images/Sections/Common/BuildWithUs/build_with_us.svg',
   '/images/common/logo.svg',
   '/images/Sections/MainPage/ReadyMadeSolutions/salesforce_schema.svg',
   '/images/Sections/MainPage/ReadyMadeSolutions/leads_schema.svg',
   '/images/Sections/MainPage/ReadyMadeSolutions/marketing_agency_schema.svg',
   '/images/Sections/MainPage/ReadyMadeSolutions/design_studio_schema.svg',
   '/images/Sections/MainPage/ReadyMadeSolutions/advertising_agency_schema.svg',
   '/images/Sections/MainPage/ReadyMadeSolutions/manufacture_schema.svg',
   '/images/Sections/MainPage/ReadyMadeSolutions/wholesales_schema.svg',
   '/images/Sections/MainPage/ReadyMadeSolutions/consulting_schema.svg',
   '/images/Sections/MainPage/ReadyMadeSolutions/legal_services_schema.svg',
   '/images/common/logo.svg',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',


     ]

];
