<?php
$content = [
     "HomePage" => [
        'top of page',
        'Skip to Main Content',
        'Features',
        'Pricing',
        'Contact',
        'Use tab to navigate through the menu items.',
        'Anchor 1',
        'About You',
        'Name',
        'First',
        'Last',
        'Email Address (write this carefully so we can reply)',
        'Phone Number (include country code)',
        'Organization',
        'What country are you writing from?',
        'United States of America',
        'Canada',
        'United Kingdom',
        'Australia',
        'Afghanistan',
        'Albania',
        'Algeria',
        'Andorra',
        'Angola',
        'Antigua and Barbuda',
        'Argentina',
        'Armenia',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahamas',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belgium',
        'Belize',
        'Benin',
        'Bhutan',
        'Bolivia',
        ' Bosnia and Herzegovina',
        'Botswana',
        'Brazil',
        'Brunei Darussalam',
        'Bulgaria',
        'Burkina Faso',
        'Burundi',
        'Cabo Verde',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Central African Republic',
        'Chad',
        'Chile',
        'China',
        'Colombia',
        'Comoros',
        'Congo',
        'Costa Rica',
        'Côte D’Ivoire (Ivory Coast)',
        'Croatia',
        'Cuba',
        'Cyprus',
        'Czech Republic (Czechia)',
        'Democratic People’s Republic of Korea (North Korea)',
        'Democratic Republic of the Congo',
        'Denmark',
        'Djibouti',
        'Dominica',
        'Dominican Republic',
        'Ecuador',
        'Egypt',
        ' El Salvador',
        'Equatorial Guinea',
        'Eritrea',
        'Estonia',
        'Ethiopia',
        'Fiji',
        'Finland',
        'France',
        'Gabon',
        'Gambia',
        ' Georgia',
        'Germany',
        'Ghana',
        'Greece',
        'Grenada',
        'Guatemala',
        'Guinea',
        'Guinea Bissau',
        'Guyana',
        'Haiti',
        'Holy See (Vatican City)',
        'Honduras',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland',
        'Israel',
        'Italy',
        'Ivory Coast',
        'Jamaica',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kiribati',
        'Kuwait',
        'Kyrgyzstan',
        'Laos',
        'Latvia',
        'Lebanon',
        'Lesotho',
        'Liberia',
        'Libya',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Macedonia',
        'Madagascar',
        'Malawi',
        'Malaysia',
        'Maldives',
        'Mali',
        'Malta',
        'Marshall Islands',
        'Mauritania',
        'Mauritius',
        'Mexico',
        'Micronesia (Federated States of)',
        'Moldova',
        'Monaco ',
        ' Mongolia',
        'Montenegro',
        'Morocco',
        'Mozambique',
        'Myanmar',
        'Namibia',
        'Nauru',
        'Nepal',
        'Netherlands',
        'New Zealand',
        'Nicaragua',
        'Niger',
        ' Nigeria',
        'North Korea',
        'North Macedonia',
        'Norway',
        'Oman',
        'Pakistan',
        'Palau',
        'Palestine',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Philippines',
        'Poland',
        'Portugal',
        'Qatar',
        'Republic of Korea (South Korea)',
        ' Romania',
        'Russia',
        'Rwanda',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Vincent and the Grenadines',
        'Samoa',
        'San Marino',
        'São Tomé and Príncipe',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Sierra Leone',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'Solomon Islands ',
        'Somalia',
        'South Africa',
        'South Korea',
        'South &lrm;Sudan ',
        'Spain',
        'Sri Lanka',
        'Sudan',
        'Suriname',
        'Swaziland',
        'Sweden',
        'Switzerland',
        'Syria',
        'Tajikistan',
        ' Tanzania',
        ' Thailand',
        'Timor-Leste',
        'Togo',
        ' Tonga',
        ' Trinidad and Tobago',
        ' Tunisia',
        'Turkey',
        'Turkmenistan',
        'Tuvalu',
        'Uganda ',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'United States of America',
        'Uruguay',
        'Uzbekistan',
        'Vanuatu',
        'Venezuela',
        'Vietnam',        
        'Yemen',
        ' Zambia',
        'Zimbabwe',
        'About Your Transcription Needs',
        'Write "NA" if you don’t know. We’ll work with you to fill in the details.',
        ' What do you need help with?',
        '*',
        'General/Academic/Business Transcription',
        'Legal/Certified Transcription',
        'Subtitles/Captions',
        'Text to Text Transcription',
        'Medical Transcription',
        'Nothing; you are applying for a job',
        'Other; please tell us below',
        'How many audio hours do you need transcribed?',
        'What language(s) is your audio in now?',
        ' What language do you want your audio file to be transcribed into? ',
        'Do you have any questions or notes to provide?',
        'How did you hear about us?',
        'Do Not Fill This Out',
        'Join the Ranks of Our Great Clients',
        '&copy;',
        ', LLC',
        'Terms Of Service',
        'Privacy Policy',
        'Refund policy',
        'delivery policy',
        'about us',
        'bottom of page',
        '',
        '',
        '',
        '',
        '',
        '',
        '',

        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',




 



                ]
];

$media =[
     "HomePage" => [
        'https://static.wixstatic.com/media/738c96_fea37dea56dc40638b725ee0d6118592~mv2.png/v1/fill/w_305,h_52,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/TranscriptionServices_com%20logo%20for%20site%20.png',
        'https://static.wixstatic.com/media/f08888_07adf05fb54148baa746faccf827b853~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/1%20-%20Office%20of%20the%20Vice%20President.jpg',
        'https://static.wixstatic.com/media/f08888_d470d5b6716c4c99ba0a31433dba507e~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/2%20-%20Health%20and%20Human%20Resources.jpg',
        'https://static.wixstatic.com/media/f08888_936625b879f346738226ef798e671182~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/3%20-%20National%20Park%20Service.jpg',
        'https://static.wixstatic.com/media/f08888_cd8515c5cf524aacbac381c7ca34a73e~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/4%20-%20CNET.jpg',
        'https://static.wixstatic.com/media/f08888_c532ccb1100445b48695e1328c23319e~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/5%20-%20KPMG.jpg',
        'https://static.wixstatic.com/media/f08888_9fd3509ad035414e9fcbadbbf78f6a11~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/6%20-%20University%20of%20Chicago.jpg',
        'https://static.wixstatic.com/media/f08888_7869c43c7d7b420eadd0b42ba119e47b~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/7%20-%20Berkeley.jpg',
        'https://static.wixstatic.com/media/f08888_b973a6b9c12c4a4ab48687c58e262c75~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/8%20-%20NIKKEI.jpg',
        'https://static.wixstatic.com/media/f08888_5094c09e42794f5bba3f7644f682a659~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/9%20-%20University%20of%20Toronto.jpg',
        'https://static.wixstatic.com/media/f08888_665e223c2c88452bb9a09cd5340117b9~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/10%20-%20George%20Mason%20University.jpg',
        'https://static.wixstatic.com/media/f08888_9643ec82927b4a1592b2a2c46ed57b53~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/11%20-%20Rypple.jpg',
        'https://static.wixstatic.com/media/f08888_4c3f1fdf92f0451896d38a58e3a2e5c3~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/12%20-%20Childrens%20Mercy%20Hospitals%20and%20Clini.jpg',
        'https://static.wixstatic.com/media/f08888_8c875693c0a74b32975c44e244acc87e~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/13%20-%20Stockholm%20University.jpg',
        'https://static.wixstatic.com/media/f08888_a22a91b59b1f4ba593889b2f995ba9e5~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/14%20-%20Uni%20Basel.jpg',
        'https://static.wixstatic.com/media/f08888_5dcaddcc2e124101a5a6b537a5633e07~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/15%20-%20Gwinnett%20County%20Public%20Schools.jpg',
        'https://static.wixstatic.com/media/f08888_0748aebf256649eda78eaf0a151ade08~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/16%20-%20RBF%20Consulting.jpg',
        'https://static.wixstatic.com/media/f08888_a66ff557e0ba4c4ab162cd2f38aae85f~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/17%20-%20Woods%20Hole%20Oceanographic%20Institute_.jpg',
        'https://static.wixstatic.com/media/f08888_4e11d4ff2c7d4487b6dc931b8d91e3ae~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/18%20-%20Nuvo.jpg',
        'https://static.wixstatic.com/media/f08888_fb22ee93b4c84d4a96aa0a2d82a61d48~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/19%20-%20Zinch.jpg',
        'https://static.wixstatic.com/media/f08888_4d47affa7b5c46f799898e7691974c2a~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/20%20-%20Insurance%20Designers.jpg',
        'https://static.wixstatic.com/media/f08888_6a30eb23f730485fa4e9a7bcb0205057~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/21%20-%20TV%20House.jpg',
        'https://static.wixstatic.com/media/f08888_a6ae561934644b598aacfab260c5218e~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/22%20-%20MCLE.jpg',
        'https://static.wixstatic.com/media/f08888_e6d798b0d6c54449aa2c510903fab6d9~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/23%20-%20Language%20Services.jpg',
        'https://static.wixstatic.com/media/f08888_c12ae0d33a6446e59387cb5fe7c24b42~mv2.jpg/v1/fill/w_100,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/24%20-%20University%20of%20California.jpg',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',


       
       
 



        ]

];
