<?php
$content = [
     "HomePage" => [
      'Pricing',
      'Features',
      'Contact',
      'Take Control',
      'of Your Social Media',
      'Stay organized, save time, and easily manage your social media with',
      '’s inbox, publishing, reporting, monitoring, and team collaboration tools.',
      'Supported Networks',
      'Connect your Google Analytics 4 account to',
      '!',
      'Learn more',
      'Over 31,000 social media managers use our tool daily',
      'One easy-to-use solution, loaded with powerful features.',
      'Everything you need to dominate social media—fortified with the industry’s #1 rated customer support.',
      'Our features',
      'Unified Social Inbox',
      'Easily manage all your incoming social media messages, comments, and reviews in one place.',
      'Learn more',
      'Intuitive Publishing',
      'Plan, collaborate, and schedule content for all your social channels.',
      'Learn more',
      'Social Listening',
      'Discover trends and insights about your brand—and your competitors.',
      'Learn more',
      'Insightful Analytics',
      'Create beautiful and actionable reports that reveal what’s working—and what isn’t.',
      'Learn more',
      'Social Media ROI',
      'Easily see what posts and conversations are driving sales, leads, and traffic. Without being a Google Analytics expert.',
      'Learn more',
      'Best Support in the Business',
      'You always get fast, friendly support in record time (much faster than the competition).',
      '30-minute',
      'response time',
      'We reply at record-breaking speed. Most companies take an average of 12 hours to reply.',
      'Not ours!',
      '96% user',
      'satisfaction score',
      ' customers are happy customers. Our customers give us a 96% user satisfaction score.',
      '#1 rated',
      'support on G2Crowd',
      'scores 93% on the largest review site in the world, far above Hootsuite and Sprout Social.',
      '#1 on Capterra <small>﻿& TrustRadius',
      'Users rate our support higher than Hootsuite and Sprout Social on these leading review sites.',
      'Voted the #1',
      'social media management solution',
      'Thousands of users rank',
      'above Hootsuite and Sprout Social for its features, ease of use, and value for money.',
      'The Best Value For Money',
      'Our mission is to deliver the best value while giving our individual users and teams more flexibility in their budgets.',
      'Check our pricing',
      ' has really changed our ability to follow up with customers and make sure we&#39;re being responsive and interacting with them when they want.&quot;',
      'Jaime Mendelsohn - Director of Customer Happiness, Lovepop',
      'Watch video',
      'Standard',
      'US',
      '$',
      '49',
      'per user/month',
      '(Billed annually)',
      'US',
      '$',
      '69',
      'per user/month',
      '(Billed monthly)',
      '10 social profiles',
      'US$15/mo per additional social profile',
      '10 social profiles',
      'US$10/mo per additional social profile',
      'Try for free now',
      'Try for free now',
      'Free for 30 days. No card required.',
      'All features',
      'you need to get started:',
      'Posts scheduling',
      'Unlimited posts',
      'Draft posts',
      'Unified Publishing Calendar',
      'View all your past and upcoming posts for all your social profiles in one, convenient Publishing Calendar',
      'Standard Social Inbox',
      'Up to 5000 messages or comments per month, ideal for moderately engaged audiences',
      'Instant translations',
      'Instantly translate your messages and comments into any language',
      'Report export',
      'Basic Social Media ROI',
      'Simplified Google Analytics reports that highlight how networks and campaigns are contributing to ROI',
      'Custom Report date range',
      'Choose a custom date range for your reports',
      'White-label reporting',
      'Add your own logo to your reports',
      'Google Chrome extension',
      'Mobile application (iOS &amp; Android)',
      'Google Analytics Integration',
      'Professional',
      'US',
      '$',
      '79',
      'per user/month',
      ' (Billed annually)',
      'US',
      '$',
      '99',
      'per user/month',
      '(Billed monthly)',
      '10 social profiles',
      'US$15/mo per additional social profile',
      '10 social profiles',
      'US$10/mo per additional social profile',
      'Try for free now',
      'Try for free now',
      'Free for 30 days. No card required.',
      'All features available',
      'on the Standard plan, plus:',
      'Instagram Product Tagging',
      'PulseLink in bio',
      'Instagram grid view',
      'First comment scheduling',
      '(Instagram, Facebook, LinkedIn)',
      'Twitter threads scheduling',
      'Team workflow',
      'Assign posts to be approved by other team members. Ideal solution to speed up your internal approval process',
      'Canva integration',
      'Calendar notes',
      'Add notes in your Publishing Calendar to organize your publishing calendar, as a team, ahead of time',
      'Basic Ad Comment Monitoring',
      'Up to 300 active ads. Monitor comments on Facebook and Instagram for moderately active ad accounts',
      'Social Listening',
      '(Instagram, YouTube)',
      'Team performance reports',
      'Priority email &amp; chat support',
      'Advanced',
      'US',
      '$',
      '119',
      'per user/month',
      '(Billed annually)',
      'US',
      '$',
      '149',
      'per user/month',
      '(Billed monthly)',
      '10 social profiles',
      'US$15/mo per additional social profile',
      '10 social profiles',
      'US$10/mo per additional social profile',
      'Try for free now',
      'Try for free now',
      'Free for 30 days. No card required.',
      'All features available <br> on the Professional plan, plus:',
      'Content Library',
      '5 Shared Calendars',
      'Easily gather feedback from external stakeholders with Shared Calendars',
      'Bulk publish content',
      'Content queues',
      'Schedule posts in bulk',
      'Advanced spam management',
      'Hide or delete messages and comments in bulk',
      'Advanced Ad comments monitoring',
      'Monitor comments on Facebook and Instagram for very active ad accounts up to 2500 live ads creatives',
      'Automated Inbox Assistant',
      'Saved replies',
      'Inbox bulk actions',
      'Assign, label, review, hide and delete messages and comments in bulk',
      'Publishing content labels',
      'Assign labels to your Inbox items',
      'Advanced Social Media ROI reports',
      'Advanced reports with unlimited Google Analytics view',
      'Power reports (customized)',
      'Customized, presentation-ready reports',
      'Custom',
      'Custom solutions tailored to your business needs.',
      'Custom solutions tailored to your business needs.',
      'Get a quote',
      'Get a quote ',
      'Book a demo',
      'All features available',
      'on the Advanced plan, plus:',
      'Unlimited social profiles',
      'Unlimited Shared Calendars',
      'Priority email, chat, &amp; phone support',
      'Dedicated Account Manager',
      'Quarterly Business Reviews',
      'Free Social Media Manager School Access',
      'Free',
      'US$0/Mo',
      '3',
      'social profiles,',
      '1',
      'user',
      '10 scheduled posts',
      'Basic social Inbox*',
      'Basic reporting',
      'Limited Social Media ROI report',
      'Top performing post ROI',
      'Mobile app',
      'Android and iOs',
      'Create a free account',
      'Terms',
      'Privacy Policy',
      'Refund policy',
      'about us',
      'delivery policy',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      ''
      
                ]
];

$media =[
     "HomePage" => [
   'http://localhost/agorapulse.com/assets/logo.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/facebook.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/facebook.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/instagram.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/instagram.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/linkedin.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/linkedin.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/twitter.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/twitter.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/youtube.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/youtube.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/google-my-business.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/google-my-business.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/tiktok-new.svg',
   'http://localhost/agorapulse.com/assets/supported-networks/tiktok-new.svg',
   'http://localhost/agorapulse.com/assets/home-hero-image-desktop-large.png',
   'http://localhost/agorapulse.com/assets/banner.svg',
   'http://localhost/agorapulse.com/assets/home/balloons-celebration-social.svg',
   'http://localhost/agorapulse.com/assets/home/star.svg',
   'http://localhost/agorapulse.com/assets/home/balloons-celebration-social.svg',
   'http://localhost/agorapulse.com/assets/logos/ogilvy.svg',
   'http://localhost/agorapulse.com/assets/logos/digitalbutter.svg',
   'http://localhost/agorapulse.com/assets/logos/west-virginia-university.svg',
   'http://localhost/agorapulse.com/assets/logos/mesa-de-trabajo-5.svg',
   'http://localhost/agorapulse.com/assets/logos/shipt.svg',
   'http://localhost/agorapulse.com/assets/logos/butterbox.svg',
   'http://localhost/agorapulse.com/assets/logos/fourteenfoods.svg',
   'http://localhost/agorapulse.com/assets/home-screen-inbox_6.png',
   'http://localhost/agorapulse.com/assets/home-screen-inbox_6.png',
   'http://localhost/agorapulse.com/assets/home-screen-publishing_6.png',
   'http://localhost/agorapulse.com/assets/home-screen-monitoring_6.png',
   'http://localhost/agorapulse.com/assets/home-screen-reporting_6.png',
   'http://localhost/agorapulse.com/assets/home-screen-roi_6.png',
   'http://localhost/agorapulse.com/assets/home-screen-inbox_6.png',
   'http://localhost/agorapulse.com/assets/home-inbox-buddy.png',
   'http://localhost/agorapulse.com/assets/home-support-gfx.png',
   'http://localhost/agorapulse.com/assets/home-best-support.mp4',
   'http://localhost/agorapulse.com/assets/home-support-response.png',
   'http://localhost/agorapulse.com/assets/home-support-score.png',
   'http://localhost/agorapulse.com/assets/home-support-g2crowd.png',
   'http://localhost/agorapulse.com/assets/home-support-capterra.png',
   'http://localhost/agorapulse.com/assets/home-comparison.png',
   'http://localhost/agorapulse.com/assets/home-ranking.mp4',
   'http://localhost/agorapulse.com/assets/home-growth.png',
   'http://localhost/agorapulse.com/assets/home-growing-business.mp4',
   'http://localhost/agorapulse.com/assets/home-lovepop.mp4',
   'http://localhost/agorapulse.com/assets/pricing/Cogs_reporting.svg',
   'http://localhost/agorapulse.com/assets/footer-fb.png',
   'http://localhost/agorapulse.com/assets/footer-ig.png',
   'http://localhost/agorapulse.com/assets/footer-tw.png',
   'http://localhost/agorapulse.com/assets/footer-yt.png',
   'http://localhost/agorapulse.com/assets/footer-linkedin.png',
   'http://localhost/agorapulse.com/assets/footer-tt.svg',
   '',
   '',
   '',
   '',
   '',
   ''


     ]

];
