<?php
$content = [
     "HomePage" => [
        'Pricing',
        'Contact us',
        'Less Annoying CRM',
        'promises 3 things',
        'no other CRM',
        'can',
        '(In addition to being U.S. News &amp; World Report&#x27;s',
        '#1 CRM of 2020, 2021, 2022, and 2023.)',
        'Start your free trial',
        'See how it works',
        '30-days. Full access. No credit card needed.',
        '#1. 💖',
        'Veteran customer service',
        'The average CRM Coach has been working with LACRM customers for',
        'over 5 years',
        '— this means no matter who you talk to, you&#x27;re talking to a seasoned pro.',
        'That&#x27;s because we pay every employee a',
        'thriving wage',
        '. When we hire someone, they stay long enough to become an actual expert. No chatbots ever.',
        '#2. 🤝',
        'One low price, and no upcharges',
        'We have no investors demanding that we squeeze every dollar out of our users, so',
        'we&#x27;ll always price LACRM as low as we can afford to',
        'We&#x27;ve only raised our price once in the past 14 years (thanks a lot, inflation), but we offered legacy pricing for all existing customers — because loyalty matters.',
        '# 3. 🏌️',
        'Utter commitment to small businesses',
        'Less Annoying CRM isn&#x27;t a neglected spin-off of another big CRM, nor are we the &quot;lite&quot; version of a more expensive system.',
        'Our goal 14 years ago was to build the best CRM for small businesses, and',
        'today we&#x27;re still the',
        '#1 easiest-to-use CRM',
        'for small businesses',
        '. We have no plans to change course.',
        'If a software engineer can&#x27;t set up a CRM,',
        'we have a problem.',
        'Tyler, an experienced software engineer, struggled to get A Very Popular CRM 👀 set up for his boss. It ended up being so difficult to use that he built his own app instead.',
        'Yep, that app became Less Annoying CRM, and Tyler, our CEO.',
        'That was over a decade ago, so why are CRMs',
        'still',
        'so hard to use for small businesses?',
        'This happens because most CRMs are still funded by investors.',
        'An investor&#x27;s only goal is to make more money than last year, and you do that by attracting high-value customers.',
        'Unfortunately, small businesses ≠ high-value customers.',
        '👉 This means that for most investor-funded CRM companies,',
        'it makes no financial sense to serve small businesses',
        '.',
        'That&#x27;s why so many CRMs that start off as &quot;small business CRMs&quot; end up becoming, well,',
        'those',
        'CRMs.',
        '👸 Once upon a time,',
        'You fell in love with a new tech product. It’s fast, simple, and does',
        'exactly what you need',
        '. The price is reasonable, and customer service is friendly and helpful. You’re relieved to have',
        'finally',
        'found a company you can trust.',
        '😈 But things started to change...',
        'They',
        'raise your prices',
        'and add expensive pricing tiers you can’t afford. Your support person suddenly sounds a lot like chatbot. All the new features seem to be built for bigger customers, and with every update, the product is less and less of a fit for you. But maybe you can still make it work?',
        '👋 Finally, you receive an email.',
        '&quot;Thank you for being a part of our incredible journey!&quot;, they say. They&#x27;ve been bought by a massive company, and',
        'they&#x27;re shutting down the version of their software that you&#x27;ve come to depend upon.',
        'Less Annoying CRM is completely self-funded.',
        'This lets us do things that most investors would balk at, just because that’s how we want to do business.',
        'That&#x27;s why',
        'we’ve been running the small business playbook since 2009',
       ' . ❤️',
       'Never raising any money from investors has meant that LACRM has had a much longer, slower journey to growth, and no one here is going to become a billionaire.',
       'That’s just fine with us',
       '👸 Once upon a time,',
       'You fell in love with a new tech product. It’s fast, simple, and does ',
       'exactly what you need',
       '. The price is reasonable, and customer service is friendly and helpful. You’re relieved to have <em>finally</em> found a company you can trust.',
       '😈 But things started to change...',
       'They',
       'raise your prices',
       'and add expensive pricing tiers you can’t afford. Your support person suddenly sounds a lot like chatbot. All the new features seem to be built for bigger customers, and with every update, the product is less and less of a fit for you. But maybe you can still make it work?',
       '👋 Finally, you receive an email.',
       '&quot;Thank you for being a part of our incredible journey!&quot;, they say. They&#x27;ve been bought by a massive company, and',
       'they&#x27;re shutting down the version of their software that you&#x27;ve come to depend upon.',
       'This is what that Less Annoying playbook looks like:',
       '💸 Funded by investors',
       'Investors, not customers, get to decide how the product develops',
       'Goal is to make a lot of money each year; not to keep building a better product.',
       '👪 Funded by customers',
       'No pressure to screw over our customers to turn a profit (we&#x27;re already profitable!).',
       'Freedom to build only features small businesses need.',
       'Family-owned since 2009 — we&#x27;re in it for the long haul.',
       'Meet our customers',
       '🤑 Predatory pricing',
       'Ever-increasing prices',
       'Forced to &quot;upgrade&quot; just to use the same features you had before',
       '🤝 Honest pricing',
       'One single price tier with no contracts',
       'No upgrade fees or hidden costs',
       'Our lowest price while still providing a',
       'thriving wage',
       'to all employees.',
       'See full pricing details',
       '😫 Frustrating support',
       'Chatbot that gives you the wrong answers',
       'Must pay extra to speak to real person',
       'Every issue needs to get escalated to someone else before you get the help you need',
       '🔥 Empowered support',
       'Coaches collaborate with you for long-term success; not just answer one-off tickets',
       'Every teammate discusses your feedback with the entire product team every week',
       'We hire the',
       'best people',
       ', who stay with us for a',
       'very',
       'long time.',
       'Ask us anything',
       '🏛️ Enterprise-focused',
       'Complicated features designed to appeal to large companies with deep pockets',
       'Pricing models that offer discounts only to enterprises that can afford to pay a lot upfront.',
       '🏠 Small biz-focused',
       'The average LACRM account has 2.5 users, and that&#x27;s how we like it',
       'Every new feature is designed with ease-of-use for the solo user in mind',
       'You will never need to hire a consultant to set up your CRM.',
       'Put our live demo to the test',
       'And it&#x27;s a playbook our customers trust.',
       'Pricing',
       'Our Less Annoying Guarantee',
       'Brilliant (and free!) customer service',
       'Our lowest possible price',
       'Uncomplicated software',
       '$15',
       '/user/month',
       'Try it risk-free for 30 days',
       'What’s includeD',
       'Unlimited contacts and companies',
       'Unlimited custom fields',
       'Unlimited pipelines',
       '25GB of file storage per user',
       'Email logging',
       'Task management',
       'User permissions',
       'Mobile access',
       '...and',
       'every single feature',
       '(plus free upgrades!)',
       '.',
       'For the first time, I have a CRM that I completely understand and can navigate.',
       'William Hammett',
       'Hammett Marketing Group LLC',
       'Any sales team can figure this one out without lengthy training. Pipelines can be built within minutes.',
       'Mike Barclay',
       'SHIPHAUS',
       'View more customer testimonials',
       'So why not work with a CRM company that does business the way you would?',
       'Join 10,000+ small businesses already using a',
       'CRM that is playing on their team.',
       'Start your free trial',
       'See how LACRM works',
       'Pages',
       'Terms Of Service',
       'Privacy Policy',
       'Refund policy',
       'delivery policy',
       'Company Info',
       'About us',
       'Contact us',
       'Spread the word',
       'Come say hi!',
       'Less Annoying Software, LLC',
       '1017 Olive St. #300',
       'St. Louis, MO 63101',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',

  

   














                ]
];

$media =[
     "HomePage" => [
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/632b83dccac2da6da76c15bc_logo%20%2B%20text%20-%20blue%20-%20transparent%20bg.svg',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/6351f717f7b7a3c7c42ff5c8_untitled-ui-logo.png',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/641b7502819fd57ea543cc1a_1.png',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/642b0f62cccaa7067b4f6629_workflow%20(3).png',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/6425a4968d91cefd56dc30ef_checklist%20(5).png',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/63fe398f67892d50b45e87c1_Down%20Arrow.png',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/641b9172200c823dc136e86a_testimonials%201.png',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/60956394037f9997245be46c_icons8-checkmark.svg',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/60956394037f9997245be46c_icons8-checkmark.svg',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/60956394037f9997245be46c_icons8-checkmark.svg',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/60956394037f9997245be46c_icons8-checkmark.svg',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/60956394037f9997245be46c_icons8-checkmark.svg',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/60956394037f9997245be46c_icons8-checkmark.svg',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/60956394037f9997245be46c_icons8-checkmark.svg',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/60956394037f9997245be46c_icons8-checkmark.svg',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/60956394037f9997245be46c_icons8-checkmark.svg',     
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/60956394037f9997245be46c_icons8-checkmark.svg',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/60956394037f9997245be46c_icons8-checkmark.svg',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/5efd062b4e274016231bcd4b_william_hammett.jpg',
        'https://assets-global.website-files.com/5eb25de94cee6c29635fe867/5efd2a3df0651c1490c44286_mike_barclay.jpg',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',    
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
 



        ]

];
