<?php
$content = [
     "HomePage" => [
       'Toggle navigation',
       'Features',
       'Pricing',
       'Contact Us',
       'The All-In-One LinkedIn Automation Tool',
       'We help thousands of LinkedIn users simplify prospecting efforts, grow their business with our advanced LinkedIn automation software.',
       'Free trial',
       '4.6/5',
       '107 reviews',
       '4.6/5',
       '263 reviews',
       'Excellent',
       '96 reviews',
       '135 reviews',
       '50 000+ users',
       'Watch tutorial',
       '4.6/5',
       '107 reviews',
       '4.6/5',
       '263 reviews',
       'Excellent',
       '96 reviews',
       '135 reviews',
       '50 000+ users',
       'Automate and simplify your work on LinkedIn',
       'Octopus is a powerful yet super simple autopilot for LinkedIn that automates your work and has a wide range of awesome features.',
       'Send automated (personalized) connection requests on LinkedIn',
       'Send connection requests by email to bypass the weekly invite limit on LinkedIn',
       'Message hundreds of 1st level connections in bulk',
       'Automatically endorse up to 7 skills on profiles of your LinkedIn contacts',
       'Visit hundreds of profiles automatically',
       'Build your',
       'marketing funnel',
       'on LinkedIn',
       'Imagine you could automatically connect with your target audience, then send a “thank you” message once the connection requests are accepted, endorse a few skills to warm these prospects up and convert them into clients by sending follow-ups.',
       'The software allows you to create your personal LinkedIn lead generation funnel. Add, remove and combine features quickly and easily, save all your prospects in your personal dashboard and start getting awesome results with Octopus CRM LinkedIn automation.',
       'Watch your stats',
       'and evaluate',
       'performance',
       'You cannot assess your marketing efforts without watching stats, which are so important these days.',
       'Octopus CRM LinkedIn automation lets you observe various important metrics including the number of profile views &amp; search appearances, your social selling index and evaluate the performance of your campaigns.',
       'And',
       'a few more',
       'amazing',
       'features',
       'Connect by Email',
       'Worried about the weekly invite limit on LinkedIn? Octopus CRM allows you to bypass this limitation and send 500+ connection requests per week by email without any risk to your LinkedIn account',
       'Import / Export',
       'Upload your own list of LinkedIn profiles to the Octopus CRM campaigns for further actions or export data from LinkedIn to CSV file.',
       'Zapier and Hubspot integration',
       'Want to push data and actions from LinkedIn to Zapier, Google Docs, Hubspot or other apps? Integrate your Octopus CRM campaigns with Zapier in just a few clicks!',
       'Compatibility with all LinkedIn account types',
       'Octopus CRM LinkedIn automation tools can be used on LinkedIn Free, Premium, Sales Navigator and even Recruiter Lite accounts.',
       'Activity Control',
       'Allow Octopus CRM LinkedIn automation tool track your LinkedIn performance and send you immediate notifications right after our system detects the excessive activity on LinkedIn for extra safety.',
       'How It Works',
       'Find Your Target Audience',
       'Look for your target audience on LinkedIn by filtering profiles in the LinkedIn Search or prepare a CSV file with LinkedIn profile URLs',
       '01',
       'Add Leads to Campaign',
       'Add these leads to your "connecting", "messaging", "visiting" or "endorsing" campaigns depending on what action you would like to perform with these leads.',
       '02',
       'Launch Your Campaign',
       'Now launch the campaign to start performing automated actions with these leads.',
       '03',
       'Octopus CRM is the Safest LinkedIn Automation Tool on the Market',
       'Octopus CRM is a reliable automation software',
       'safely used by businesses',
       'of all sizes all over the globe. Due to the huge number of safety measures, you can be confident your LinkedIn outreach is completely genuine and cannot cause any risk to your LinkedIn account.',
       'Our clients',
       'Our LinkedIn automation tool works best for:',
       'Business Owners',
       'Marketing Agencies',
       'Recruiters',
       'Sales Teams',
       'Start free trial',
       'Compatible with',
       'Octopus CRM',
       'is 100% compatible with Free LinkedIn, LinkedIn Premium, Sales Navigator and Recruiter (including Recruiter Lite)',
       'LinkedIn',
       'Basic',
       'LinkedIn',
       'Premium',
       'LinkedIn',
       'Sales Navigator',
       ' LinkedIn',
       'Recruiter',
       'Pricing plans',
       'Monthly',
       'Annually',
       '-35%',
       'Agency',
       'Pricing plans',
       'Personal CRM with stats',
       'Auto invite (personalized)',
       'Ability to connect with premium LinkedIn users only',
       'Send automated messages in bulk',
       'Auto view profiles',
       'Auto endorse skills',
       'Create campaigns',
       'Export / import data',
       'Build funnels',
       'The software allows you to create your personal LinkedIn lead generation funnel',
       'Integration with Zapier / Hubspot',
       'Push actions from LinkedIn to Zapier and then forward them to hundreds of apps including Hubspot CRM, Zoho, Asana, Google Sheets and others',
       'Activity control',
       'This feature allows you to stay extra safe on LinkedIn and receive immediate alerts right after our system detects the excessive activity on your LinkedIn account',
       'Bypass weekly invite limit',
       'Get around LinkedIn’s weekly invitation limit by sending connection requests by email once the limit is reached. This feature allows you to get back to sending 500+ connection requests per week again',
       'Starter',
       '$9.99',
       'per month',
       'Free trial',
       'Compatible with',
       '+',
       'Sales Navigator',
       'Pro',
       '$14.99',
       'per month',
       'Free trial',
       'Compatible with ',
       '+',
       'Sales Navigator',
       'Advanced',
       '$21.99',
       'per month',
       'Free trial',
       'Compatible with',
       '+',
       'Sales Navigator',
       'Recommended',
       'Unlimited',
       '$39.99',
       'per month',
       'Free trial',
       'Compatible with',
       '+',
       'Premium',
       '+',
       'Sales Navigator',
       '+',
       'Recruiter',
       'Starter',
       '$6.99',
       'per month',
       'Free trial',
       'Compatible with',
       '+',
       'Sales Navigator',
       'Pro',
       '$9.99',
       'per month',
       'Free trial',
       'Compatible with',
       '+',
       'Sales Navigator',
       'Advanced',
       '$14.99',
       'per month',
       'Free trial',
       'Compatible with',
       '+',
       'Sales Navigator',
       'Recommended',
       'Unlimited',
       '$24.99',
       'per month',
       'Free trial',
       'Compatible with',
       '+',
       'Premium',
       '+',
       'Sales Navigator',
       '+',
       'Recruiter',
       'Are you a marketing agency managing 20+ accounts?',
       'Reach out to our team for special pricing',
       'Contact us',
       'All plans come with a 7-day obligation-free trial. No credit card required, unsubscribe anytime.',
       'What our users say',
       'Trusted by more than 40,000 users in almost every industry and country.',
       'An essential tool for anyone with a LinkedIn Premium account who is serious about building their business. I would thoroughly recommend it. The cost is minimal to the level of business it can generate or provide.',
       'Lee Werell',
       'Really good software that works amazingly well. The videos are helpful. I think it takes a little getting used to but works really well and I’m growing my connections on LinkedIn in a very targeted way day by day. Thanks for this!',
       'Andy Storch',
       'I have been using it for a while now and love it! Another great thing about it is the customer support',
       'Al Eddy',
       'I’m sooo happy with Octopus. The arsenal of features is simply incredible. Undoubtedly, it’s much better than a full time assistant.',
       'Audrey Bryant',
       'This is such a great tool. I’ve literally added over 100 connections in a single week. Octopus will give me close to 400 opportunities a month to speak to business professionals consistently and really automate my outreach! So pleased and you absolutely cannot beat the price! If you’re not using this system you need to really consider it. Take the free trial and go boost your business. You have zero to lose because they don’t require a credit card or commitment. Go crush it with, Octopus!',
       'Justin Carbaugh',
       'Fantastic tool for LinkedIn! Makes messaging and new connections so much faster and easier, plus it’s simple to use. Still getting my head around setting up the funnels but the videos are very helpful. Highly recommend.',
       'Kali Gray',
       'Was skeptical at first, but after trying the software out then testing competitors, there’s really no equal. Learning curve is a little steep, but it’s robust once you get the hang of creating marketing funnels. I’m SUPER impressed with the assistance I receive from my account manager as a premium subscriber. Very quick and very thorough. Love this app!',
       'Greg Gerosky',
       'Common Questions about Automation on LinkedIn with',
       'Octopus CRM',
       'Do I need a LinkedIn Sales Navigator account to use',
       'Octopus CRM',
       '?',
       'Even though it&#8217;s highly recommended to have a premium profile on LinkedIn, it’s not a mandatory condition.',
       'Octopus CRM LinkedIn automation works perfectly well with free LinkedIn accounts.',
       'How many connection requests and messages can I send with',
       'Octopus CRM',
       '? ',
       'Due to the new LinkedIn limitation, you’re allowed to send up to 100 connection requests per week. With Octopus CRM, you can bypass this limit and continue sending 500+ invitations per week (100-120 connection requests per DAY) without any risk to your LinkedIn account.',
       'One of the most effective strategies here is to send 100 regular connection requests / week and once you reach the weekly limit, switch to sending connection requests by email.',
       'As for the messages, you can send up to 100-150 messages on LinkedIn (depending on the type of your LinkedIn account).',
       'If I start using your LinkedIn automation software, how can I cancel my subscription?',
       'You can cancel your subscription with us anytime by going to your Billing page in your dashboard and pressing on the  &#8220;Cancel subscription',
       'Is your automation tool suitable for agencies?',
       'Absolutely. There is a big number of agencies that use Octopus CRM on LinkedIn accounts of their clients. And we do keep confidentiality.',
       'In addition, we have special offers for marketing agencies depending on the number of licenses you would like to receive.',
       'What differentiates you from other LinkedIn marketing tools?',
       'Octopus CRM grants access to your personal multi-functional CRM page, in which you can store leads, perform automated actions, create campaigns and build marketing funnels on LinkedIn. And you can observe the performance of your LinkedIn campaigns in our LinkedIn analytics tool that shows your average acceptance and response rates, social selling index and more.',
       'Unlike other LinkedIn automation tools, we’ll never ask for your LinkedIn credentials, so you could keep complete control over your LinkedIn account. Moreover, we pay huge attention to safety and make sure your LinkedIn lead generation and prospecting journey with Octopus CRM LinkedIn automation is 100% secure. Learn more about why Octopus CRM software is much safer than others.',
       'Therefore, if you’re using LinkedIn for sales or recruiting, then it’s probably the best LinkedIn prospecting software on the market.',
       'The all-in-one marketing automation for marketers, owners and recruiters',
       'Product',
       'Features',
       'Pricing',
       'contact',
       'About',
       'pages',
       'Terms Of Service',
       'Privacy Policy',
       'delivery policy',
       'Refund policy',
       '2018-2023 Octopus CRM All rights reserved.',
       ''
 


  

   














                ]
];

$media =[
     "HomePage" => [
        '/wp-content/uploads/2018/06/cropped-icon-blue-32x32.png',
        '/wp-content/uploads/2018/06/cropped-icon-blue-192x192.png',
        '/wp-content/uploads/2018/06/cropped-icon-blue-180x180.png',
        '/wp-content/uploads/2018/06/cropped-icon-blue-270x270.png',
        '/wp-content/uploads/2020/11/LOGO_OCTOPUS.svg',
        '/wp-content/uploads/2020/11/LOGO_OCTOPUS.svg',
        '/wp-content/uploads/2020/08/award1-small.svg',
        '/wp-content/uploads/2020/08/award1-small.svg',
        '/wp-content/uploads/2020/08/award1-small.svg',
        '/wp-content/uploads/2020/08/award2-small.svg',
        '/wp-content/uploads/2020/08/award2-small.svg',
        '/wp-content/uploads/2020/08/award2-small.svg',
        '/wp-content/uploads/2020/08/award3-small.svg',
        '/wp-content/uploads/2020/08/award3-small.svg',
        '/wp-content/uploads/2020/08/award3-small.svg',
        '/wp-content/uploads/2020/08/award4-small.svg',
        '/wp-content/uploads/2020/08/award4-small.svg',
        '/wp-content/uploads/2020/08/award4-small.svg',
        '/wp-content/uploads/2021/10/OctopusCRM1.png',
        '/wp-content/uploads/2020/08/award1-small.svg',
        '/wp-content/uploads/2020/08/award1-small.svg',
        '/wp-content/uploads/2020/08/award1-small.svg',
        '/wp-content/uploads/2020/08/award2-small.svg',
        '/wp-content/uploads/2020/08/award2-small.svg',
        '/wp-content/uploads/2020/08/award2-small.svg',
        '/wp-content/uploads/2020/08/award3-small.svg',
        '/wp-content/uploads/2020/08/award3-small.svg',
        '/wp-content/uploads/2020/08/award3-small.svg',
        '/wp-content/uploads/2020/08/award4-small.svg',
        '/wp-content/uploads/2020/08/award4-small.svg',
        '/wp-content/uploads/2020/08/award4-small.svg',
        '/wp-content/uploads/2021/09/pic-1.png',
        '/wp-content/uploads/2021/09/pic-1.png',
        '/wp-content/uploads/2019/10/Group.png',
        '/wp-content/uploads/2019/10/Group.png',
        '/wp-content/uploads/2019/12/is.png',
        '/wp-content/uploads/2019/12/is.png',
        '/wp-content/uploads/2021/08/octopus-limit.svg',
        '/wp-content/uploads/2021/08/octopus-limit.svg',
        '/wp-content/uploads/2020/04/csv.svg',
        '/wp-content/uploads/2020/04/csv.svg',
        '/wp-content/uploads/2020/04/zapier.svg',
        '/wp-content/uploads/2020/04/zapier.svg',
        '/wp-content/uploads/2020/04/compatibility.svg',
        '/wp-content/uploads/2020/04/compatibility.svg',
        '/wp-content/uploads/2020/04/activity.svg',
        '/wp-content/uploads/2020/04/activity.svg',
        '/wp-content/uploads/2021/11/how1.svg',
        '/wp-content/uploads/2021/11/how1.svg',
        '/wp-content/uploads/2021/11/how2.svg',
        '/wp-content/uploads/2021/11/how2.svg',
        '/wp-content/uploads/2021/11/how3.svg',
        '/wp-content/uploads/2021/11/how3.svg',
        '/wp-content/uploads/2021/11/shield.png',
        '/wp-content/uploads/2021/11/shield.png',
        '/wp-content/uploads/2021/11/clients1.svg',
        '/wp-content/uploads/2021/11/clients1.svg',
        '/wp-content/uploads/2021/11/clients2.svg',
        '/wp-content/uploads/2021/11/clients2.svg',
        '/wp-content/uploads/2021/11/clients3.svg',
        '/wp-content/uploads/2021/11/clients3.svg',
        '/wp-content/uploads/2021/11/clients4.svg',
        '/wp-content/uploads/2021/11/clients4.svg',
        '/wp-content/uploads/2019/07/testi1.png',
        '/wp-content/uploads/2019/07/testi1.png',
        '/wp-content/uploads/2019/07/testti2.png',
        '/wp-content/uploads/2019/07/testti2.png',
        '/wp-content/uploads/2019/07/testi3.png',
        '/wp-content/uploads/2019/07/testi3.png',
        '/wp-content/uploads/2019/08/Audrey-min.jpg',
        '/wp-content/uploads/2019/08/Audrey-min.jpg',
        '/wp-content/uploads/2019/07/testti5.png',
        '/wp-content/uploads/2019/07/testti5.png',
        '/wp-content/uploads/2019/07/testi6.png',
        '/wp-content/uploads/2019/07/testi6.png',
        '/wp-content/uploads/2019/07/testi7.png',
        '/wp-content/uploads/2019/07/testi7.png',
        '/wp-content/uploads/2020/10/LOGO_OCTOPUS-1.svg',
        '/wp-content/uploads/2020/10/LOGO_OCTOPUS-1.svg',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
       
       
 



        ]

];
