<?php
$content = [
     "HomePage" => [
        'Pricing',
        'One suite for all types of',
        'customer',
        'feedback',
        'ruttl helps product, marketing, sales, and support teams work efficiently to grow revenues.',
        'Get started for free',
        'Book a Demo',
        'Our Products',
        'Website Feedback Tool',
        'Comment, edit, and track bugs on live websites',
        'Mobile App Feedback',
        'Report bugs on your mobile app using our plugin',
        'Video Annotation Tool',
        'Review and collaborate on videos',
        'PDF/Image Review',
        'Share feedback and leave comment on PDFs and image files.',
        'Customer Feedback Tool',
        'Chat with your website visitors and solve their issues',
        '&quot;We loved using ruttl. The entire process right from sign-up to commenting &amp; managing feedback is so smooth.&quot;',
        '- Josh Shepherd,',
        'Event Tech Strategy at Atlassian',
        'Website Feedback Tool',
        'View Product',
        'Add Comment',
        'Edit Content',
        'Bug Tracking',
        'Share with Guests',
        'Review Web Apps',
        'Annotate PDFs &amp; Images',
        'Add design feedback by leaving text and video comments on live websites to give contextual feedback, and add attachment files as well.',
        'Make real-time CSS edits to visualise the final output. Edit content, change fonts, spacing, margins and many more!',
        'Report issues directly on live product without the need of screenshots and track all your tickets in Kanban style in one place',
        'Collect feedback from your external guests/clients with just a link which doesn&#x27;t need a signup',
        'Review and streamline your feedback process by adding comments and edits on your web app.',
        'Collect feedback as comments on your PDFs &amp; images. Add the updated files as versions to show the changes instantly!',
        'Mobile App Feedback',
        'View Product',
        'Report Bug',
        'Workflow',
        'Assign Members',
        'Assign Due Dates',
        'Android App',
        'Report issues directly from a mobile device without the need for screenshots.',
        'Track all your mobile app bugs in Kanban style, without any additional integration steps needed.',
        'Assign the tickets to your team members and track the progress.',
        'Set deadlines for your ticket and get notified when you miss the dates.',
        'Review your Android app with ruttl. The iOS is coming soon.',
        'Customer Feedback',
        'View Product',
        'Report Issues',
        'Live chat',
        'Feature Request',
        'Support Dashboard',
        'Customisation',
        'Collect annotated issues from users in real-time with all the device details, like browser, browser version, OS, viewport resolution, etc',
        'Add a site widget, chat live with your (customer support) agents and gather real-time insights.',
        'Collect and manage feature requests. Get your next best feature from your users.',
        'Manage all your conversation with users in a single place. Convert a conversation to a ticket if needed.',
        'Customise the look and feel of your chat widget. Replace the icon or set its custom size, use your brand colours, etc.',
        'Website Feedback',
        '&nbsp;Plans',
        'Mobile App Feedback',
        '&nbsp;Plans',
        'Customer Feedback',
        '&nbsp;Plans',
        'Monthly',
        'Yearly',
        'Free',
        '$0',
        '$0',
        '$0',
        '/month/user&nbsp;billed yearly',
        'Get Started',
        'Upto 5 Users',
        '1 project',
        'Unlimited Guests',
        'All Integrations',
        'Pro',
        '$3',
        '$3',
        '$3',
        '/month/user&nbsp;billed yearly',
        'Get Started',
        'All in Free',
        '1 admin + upto 50 users',
        'Unlimited Projects',
        'Unlimited Guests',
        '10 mins of Video Commenting',
        'Dedicated Success Manager',
        'Team',
        '$10',
        '$10',
        '$10',
        '/month/user&nbsp;billed yearly',
        'Get Started',
        'All in Pro',
        'Admin users with project management abilities',
        'Centralised Project Management',
        'Dedicated Team Workspace',
        'Custom Branding and CNAME',
        'SAML Support',
        'Coming Soon',
        'Explore all features',
        'Customers love ruttl for a reason',
        'I now spend less time trying to understand all the changes my clients want, passing on those comments and it’s super easy for my clients to share visual feedback.',
        'Francisco Oliden',
        'Client Relationship manager at Agencia Eremo',
        'If you know Project Huddle, you shouldn’t let it go! ruttl is fast at collecting, managing, and previewing design feedback on live websites. This is a gem, I really love it.',
        'Christiano Hans',
        'Founder at Hans Republic',
        'I really liked ruttl, easy to use, and I will be using it in the future, either for further developing the page or for other projects. Great product!',
        'Eric Halada',
        'Founder at Eric Halada',
        'ruttl is miles ahead in terms of features, ease of use, speed, and product innovation! It’s my go-to for collecting client feedback.',
        'Joe Fletcher',
        'Founder of Fletcher Digital',
        'Afton Negrea',
        'Digital Business Strategist, Aftonnegrea.com',
        'ruttl cut down my meetings with front-end devs, to explain to them all the issues on the website and made it simple to make changes as well as keep track of them. 10/10!',
        'Amit Arora',
        'UI/UX Designer at MikeLegal',
        'John Bendever Jr',
        'Creative Director at Local Marketing Pros',
        'Our team loved ruttl so much that we’re extending the license for a year beyond the event, to test it with other programs!',
        'Joshua Shepherd',
        'Sr. Marketing Manager at Atlassian',
        'Dan Peres',
        'Founder of Ceran Technologies',
        'I’m able to make edits to the code directly from the platform- it speeds up your projects by allowing clients to review real time, and note changes. If you’re a web designer or developer, it will definitely speed up your work.',
        'Kanesha Harper',
        'Founder at The Arch Effect',
        'It is an essential tool for any web agency- clients can just comment and get an idea of the rendering even before the work is done!',
        'Ludovic Clain',
        'Founder of PrakSite',
        'ruttl has been a blessing because it simplified our feedback process, no long emails just to figure out what clients are trying to talk about!',
        'Laurence Anthony',
        'Director of Pixallus',
        'ruttl has been a blessing because it simplified our feedback process, no long emails just to figure out what clients are trying to talk about!',
        'Laurence Anthony',
        'Director of Pixallus',
        'Life-changer- it saves me so much time! Clients don’t need to login to leave feedback. Do yourself a favor and get the tool. It will basically pay for itself with just one client!',
        'Felix Thompson',
        'Creator at Talentiz',
        'Powerful, easy, precious. Some small issues for me, but globally more than good! It will probably become a daily tool for me.',
        'Francois Jung',
        'Director at synAct',
        'I now spend less time trying to understand all the changes my clients want, passing on those comments and it’s super easy for my clients to share visual feedback.',
        'Francisco Oliden',
        'Client Relationship manager at Agencia Eremo',
        'If you know Project Huddle, you shouldn’t let it go! ruttl is fast at collecting, managing, and previewing design feedback on live websites. This is a gem, I really love it.',
        'Christiano Hans',
        'Founder at Hans Republic',
        'I really liked ruttl, easy to use, and I will be using it in the future, either for further developing the page or for other projects. Great product!',
        'Eric Halada',
        'Founder at Eric Halada',
        'ruttl is miles ahead in terms of features, ease of use, speed, and product innovation! It’s my go-to for collecting client feedback.',
        'Joe Fletcher',
        'Founder of Fletcher Digital',
        'Afton Negrea',
        'Digital Business Strategist, Aftonnegrea.com',
        'ruttl cut down my meetings with front-end devs, to explain to them all the issues on the website and made it simple to make changes as well as keep track of them. 10/10!',
        'Amit Arora',
        'UI/UX Designer at MikeLegal',
        'X',
        'ruttl integrates with your favorite software',
        'View all Integrations',
        'Website Feedback',
        'Comment on live websites, report bugs, and make real-time CSS edits for precise feedback',
        'Mobile App Feedback',
        'Mark issues directly on mobile application, organise feedback using our internal workflow',
        'Customer Feedback',
        'Chat with your website users in real time &amp; resolve their issues with your team',
        '© 2019-2023 Brucira Softwares Pvt. Ltd.',
        'ruttl was ranked at #1 Bootstrapped &amp; Crowdfunded for 2022',
        'pages',
        'Terms Of Service',
        'Privacy Policy',
        'Refund policy',
        'delivery policy',
        'about us',
        '',
        ''

 



                ]
];

$media =[
     "HomePage" => [
        '/assets/img/ruttl-logo.svg',
        '/assets/img/top-post-badge.svg',
        '/assets/img/top-post-badge.svg',
        '/assets/img/stars.svg',
        '/assets/img/logo/g2-crowd-full.png',
        '/assets/img/logo/capterra-full.png',
        '/assets/img/logo/get-app-full.png',
        '/assets/img/website-feedback-icon.svg',
        '/assets/img/mobile-app-feedback-icon.svg',
        '/assets/img/video-review.svg',
        '/assets/img/pdf-image.svg',
        '/assets/img/customer-feedback-icon.svg',
        '/assets/img/atlassian-logo-round.webp',
        '/assets/img/website-feedback-icon.svg',
        '/assets/img/comment-website.webp',
        '/assets/img/edit-content-home.webp',
        '/assets/ruttl-bug-tracking-demo.mp4',
        '/assets/img/guest-sharing.webp',
        '/assets/img/web-apps.webp',
        '/assets/img/pdfs-images.webp',
        '/assets/img/mobile-app-feedback-icon.svg',
        '/assets/img/report-bugs-mobile.webp',
        '/assets/img/workflow-mobile.webp',
        '/assets/img/assign-members-mobile.webp',
        '/assets/img/assign-due-date-mobile.webp',
        '/assets/img/android-app.webp',
        '/assets/img/customer-feedback-icon.svg',
        '/assets/img/report-issues.webp',
        '/assets/img/live-chat.webp',
        '/assets/img/feature-request.webp',
        '/assets/img/support-dashboard.webp',
        '/assets/img/customization.webp',
        '/assets/img/francisco-oliden.jpg',
        '/assets/img/app-sumo-rating.png',
        '/assets/img/app-sumo-full.png',
        '/assets/img/christiano-hans.png',
        '/assets/img/app-sumo-rating.png',
        '/assets/img/app-sumo-full.png',
        '/assets/img/eric-halada.jpeg',
        '/assets/img/app-sumo-rating.png',
        '/assets/img/app-sumo-full.png',
        '/assets/img/joe-fletcher.png',
        '/assets/img/stars.svg',
        '/assets/customer-success-story-afton.mp4',
        '/assets/img/afton-negrea.jpg',
        '/assets/img/stars.svg',
        '/assets/img/amit-arora.jpg',
        '/assets/img/stars.svg',
        '/assets/customer-success-story-john.mp4',
        '/assets/img/john-bendever-jr.jpg',
        '/assets/img/stars.svg',
        '/assets/img/avatar-1.svg',
        '/assets/img/stars.svg',
        '/assets/customer-success-story-dan.mp4',
        '/assets/img/dan-peres.jpg',
        '/assets/img/stars.svg',
        '/assets/img/kanesha-harper.jpg',
        '/assets/img/app-sumo-rating.png',
        '/assets/img/app-sumo-full.png',
        '/assets/img/ludovic-clain.png',
        '/assets/img/app-sumo-rating.png',
        '/assets/img/app-sumo-full.png',
        '/assets/img/laurence-anthony.jpg',
        '/assets/img/app-sumo-rating.png',
        '/assets/img/app-sumo-full.png',
        '/assets/img/laurence-anthony.jpg',
        '/assets/img/app-sumo-rating.png',
        '/assets/img/app-sumo-full.png',
        '/assets/img/felix-thompson.jpeg',
        '/assets/img/app-sumo-rating.png',
        '/assets/img/app-sumo-full.png',
        '/assets/img/francois-jung.jpeg',
        '/assets/img/app-sumo-rating.png',
        '/assets/img/app-sumo-full.png',
        '/assets/img/francisco-oliden.jpg',
        '/assets/img/app-sumo-rating.png',
        '/assets/img/app-sumo-full.png',
        '/assets/img/christiano-hans.png',
        '/assets/img/app-sumo-rating.png',
        '/assets/img/app-sumo-full.png',
        '/assets/img/eric-halada.jpeg',
        '/assets/img/app-sumo-rating.png',
        '/assets/img/app-sumo-full.png',
        '/assets/img/joe-fletcher.png',
        '/assets/img/stars.svg',
        '/assets/customer-success-story-afton.mp4',
        '/assets/img/afton-negrea.jpg',
        '/assets/img/stars.svg',
        '/assets/img/amit-arora.jpg',
        '/assets/img/stars.svg',
        '/assets/img/website-feedback-icon.svg',
        '/assets/img/mobile-app-feedback-icon.svg',
        '/assets/img/customer-feedback-icon.svg',
        '/assets/img/ruttl-logo.svg',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
       
       
 



        ]

];
