<?php
$content = [
     "HomePage" => [
        'Features',
        'Pricing',
        'Contact',
        'Award Winning',
        'Digital Marketing Agency',
        'We are passionate about',
        'content creation.',
        'challenging our clients.',
        'fostering creativity.',
        'conversion rate optimization.',
        'designing beautiful websites.',
        'Facebook Advertising.',
        'helping brands grow.',
        'innovation.',
        'branding.',
        'digital marketing.',
        'SEO.',
        'Google.',
        'learning new technologies.',
        'our clients success.',
        'Google Ads.',
        'thought leadership.',
        'a great cup of coffee.',
        'custom development.',
        'writing clean code.',
        'Full Name',
        '*',
        'Email Address',
        '*',
        'Phone Number',
        'Company',
        'Interested In',
        'Website Design &amp; Development',
        'Search Engine Optimization',
        'Pay Per Click Marketing',
        'Email &amp; SMS Marketing',
        'Social Media Management',
        'How Can We Help?',
        'Results-driven Marketing',
        'Web Design',
        'Create a brand and communicate your value.',
        'SEO',
        'Find new clients organically and grow a foundation for tomorrow.',
        'PPC',
        'Put your business in front of the right people today.',
        'Email & SMS',
        'Get more out of your current website visitors.',
        'Social Media',
        'Increase awareness by engaging with your audience.',
        'Our Story',
        'SmartSites was founded by brothers Alex and Michael Melen, who grew up with a passion for all things digital. With an innovative vision and a lot of hard work, SmartSites quickly became one of America’s fastest growing companies.',
        'Read More',
        'Our relentless focus on our clients has led us to over 100 5-star reviews since our inception in 2011. When Dun &amp; Bradstreet asked &#8220;How satisfied do you feel about the quality of service?&#8221;, we scored a phenomenal 97%. We keep our clients happy by delivering results that exceed their expectations.',
        'Our headquarters are located in Paramus, New Jersey, serving numerous clients worldwide. Come join our growing SmartSites family!',
        'Remarkable Results',
        'Home Services',
        'Medical',
        'Legal',
        'Automotive',
        'B2B',
        'Retail',
        'Industrial',
        'Small Business',
        'Home Services',
        'Medical',
        'Legal',
        'Automotive',
        'B2B',
        'Retail',
        'Industrial',
        'Small Business',
        'Intra Home Systems',
        '532%',
        'Increase in total site traffic',
        '510%',
        'Increase in referral traffic',
        'Air Duct Brothers',
        '375%',
        'Increase in leads',
        '244%',
        'Increase in organic search traffic',
        'Velocity Moving',
        '652%',
        'Increase in total site traffic',
        '28%',
        'Increase in average time on site',
        'Home Services Marketing',
        'Ethos Spa Skin and Laser',
        '436%',
        'Increase in total site traffic',
        '817%',
        'Increase in organic search traffic',
        'EnMed MicroAnalytics',
        '338%',
        'Increase in organic search traffic',
        '843% ',
        'Increase in conversions',
        'Newman Plastic Surgery',
        '47%',
        'Increase in total site traffic',
        '97%',
        'Increase in organic search traffic',
        'Medical & Healthcare Marketing',
        'Corradino &#038; Papa',
        '87%',
        'Increase in total site traffic',
        '96%',
        'Increase in organic search traffic',
        'The Shulman Law Group',
        '52%',
        'Increase in total site traffic',
        '70%',
        'Increase in average time on site',
        'Weber, Fabiyan &#038; Associates',
        '43%',
        'Increase in CTR',
        '40%',
        'Increase in paid clicks',
        'Legal Services Marketing',
        'Colt Exhaust',
        '2043%',
        'Increase in ROAS',
        '1491%',
        'Increase in RPC',
        'Springfield Hyundai',
        '34%',
        'Increase in organic search traffic',
        '614%',
        'Increase in conversions',
        'UPSW',
        '121%',
        'Increase in ROAS',
        '205%',
        'Increase in RPC',
        'Automotive Marketing',
        'Arcarius Funding',
        '458%',
        'Increase in total site traffic',
        '571%',
        'Increase in organic search traffic',
        'JoTo PR',
        '70%',
        'Increase in total site traffic',
        '1725%',
        'Increase in email traffic',
        'E-Valve Technologies',
        '1604%',
        'Increase in total site traffic',
        '2910%',
        'Increase in organic search traffic',
        'Business to Business Marketing',
        'Hat Heaven',
        '1883%',
        'Increase in organic search traffic',
        '1372%',
        'Increase in sales transactions',
        'Outdoor Gear',
        '833%',
        'Increase in total site traffic',
        '1659%',
        'Increase in organic search traffic',
        'MovingUp Garage Doors',
        '301%',
        'Increase in ROAS',
        '266%',
        'Increase in RPC',
        'Retail Marketing',
        'Clark Filters Direct',
        '633%',
        'Increase in RPC',
        '418%',
        'Increase in ROAS',
        'AGA Truck Parts',
        '1057%',
        'Increase in organic search traffic',
        '685%',
        'Increase in total site traffic',
        'Melfast',
        '177%',
        'Increase in total site traffic',
        '324%',
        'Increase in organic search traffic',
        'Industrial & Commercial Marketing',
        'NJ Lux Real Estate',
        '573%',
        'Increase in organic search traffic',
        '543%',
        'Increase in total site traffic',
        'Sports Medicine & Ortho',
        '667%',
        'Increase in total site traffic',
        '947%',
        'Increase in organic search traffic',
        'The Calendar Group',
        '60%',
        'Increase in total site traffic',
        '55%',
        'Decrease in bounce rate',
        'Small Business Marketing',
        'The team you need to succeed',
        'Fueled by passion and a commitment to our clients, our team of over 100 digital experts drives performance for small businesses and Fortune 500 companies alike.',
        'Discover SmartSites',
        'Get Started',
        'Name',
        '*',
        'Email Address',
        '*',
        'Phone Number',
        '*',
        'Company',
        'Services you are interested in*',
        '*',
        'Website Design &amp; Development',
        'Search Engine Optimization',
        'Pay Per Click Marketing',
        'Email &amp; SMS Marketing',
        'Social Media Management',
        'Other',
        'Other (Please Specify)',
        '*',
        'How can we help you?',
        'Ready to speak with a marketing expert?',
        'Give us a ring',
        '201-870-6000',
        'Leading',
        'Digital Marketing',
        'Agency',
        '900+',
        'Websites Launched',
        '$100M+',
        'Client Revenue Generated',
        'SmartSites helped to develop my website. They did a great job and I noticed the positive results almost immediately. They are very professional and very pleasant to work with. I am very happy with the services provided.',
        'New Jersey Mediation',
        'Maryana Kanda',
        'View 100+ More Testimonials',
        'After a nightmare experience with other marketing companies, I finally found a hard working group who actually know what they are doing. They handle all of my ads as and designed a website. Business has doubled since we started. Looking forward to more success.',
        'Agape Health Wellness Center',
        'Dr. Larry Bennett',
        'View 100+ More Testimonials',
        'They showed me great results fast. SmartSites manages the website and SEO initiatives. We recently expanded our location and continue to drive appointments through the digital marketing. I highly recommend SmartSites!',
        'Studio Esthetique',
        'Vladimir Byhovsky',
        'View 100+ More Testimonials',
        'Smartsites is a one stop shop to outsource your website, online marketing and also content. The staff is very knowledgeable and also responsive.',
        'Englewood Cliffs News',
        'William Woo',
        'View 100+ More Testimonials',
        'I had a great experience working with SmartSites and wouldn’t hesitate to recommend them. The level of customer service, marketing skills, and efficiency was beyond the scope of my expectations!',
        'Perfect Dashboard',
        'Bartek Jaz',
        'View 100+ More Testimonials',
        'Proved to be an invaluable resource. From the conception of an idea through implementation, SmartSites was there to ensure the final matched our vision. They take the time to learn their clients’ business inside and out.',
        'Sharemoney',
        'Steven Taylor',
        'View 100+ More Testimonials',
        'Follow us on',
        'Facebook',
        'Recent Posts',
        'Posted on September 24, 2023',
        'How to Save Money on Processing Fees: An Exclusive Offer for SmartSites Clients',
        'Read More',
        'Posted on September 7, 2023',
        'YouTube SEO: The Key to Video Success',
        'Read More',
        'Posted on September 6, 2023',
        'The One Thing Webinar: E-commerce Strategies To Enhance Customer Lifetime Value',
        'Read More',
        'Terms Of Service',
        'Privacy Policy',
        'Refund policy',
        'about us',
        'delivery policy',
        '2023',
        'SmartSites',
        '. All Rights Reserved.',
        'Privacy Policy',
        'Address: 45 Eisenhower Drive, Suite 520
        Paramus, NJ 07652',
        'Call',
        'Meet',
        'We’re here for you.',
        'Call 201-870-6000',
        'Click to Chat',
        'Schedule a Meeting',
        'We are aware of active scams in India using the SmartSites brand name. We are not associated with these scams. SmartSites does not solicit employment over Telegram. All SmartSites employment is done via @<?=$ihost?> emails. If you are being scammed over Telegram, please report it to abuse@telegram.org. The only website that represents the SmartSites brand is',
        '.',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',




 



                ]
];

$media =[
     "HomePage" => [
      '/wp-content/themes/smartsites/images/smartsites-logo.svg',
      '/media/inc-5000-seven-years.svg',
      '/media/google-premier-partner-2023.svg',
      '/media/microsoft-ads-partner-2023.svg',
      '/media/bbb-a-plus-rating-1.svg',
      '/media/meta-business-partner-2023.svg',
      '/media/amazon-ads-verified-partner-2023-1.svg',
      '/media/featured-services-bg.jpg',
      '/media/featured-services-bg-1536x708.jpg',
      '/media/featured-services-bg-1024x472.jpg',
      '/media/featured-services-bg-1007x464.jpg',
      '/media/featured-services-bg-768x354.jpg',
      '/media/featured-services-bg-755x348.jpg',
      '/media/featured-services-bg-687x317.jpg',
      '/media/featured-services-bg-570x263.jpg',
      '/media/featured-services-bg-546x252.jpg',
      '/media/featured-services-bg-408x188.jpg',
      '/media/featured-services-bg-300x138.jpg',
      '/media/featured-services-bg-75x35.jpg',
      '/media/featured-services-bg.jpg',
      '/media/smartsites-full-service-digital-agency.jpg',
      '/media/award-winning-web-design-company-1.webm',
      '/media/award-winning-web-design-company-1.mp4',
      '/media/forbes-badge.svg',
      '/media/bloomberg-badge.svg',
      '/media/inc-badge.svg',
      '/media/npr-badge.svg',
      '/media/business-week-badge.svg',
      '/work/home-services/intra-home-systems-marketing/',
      '/media/bg-intra-home-system.jpg',
      '/media/bg-intra-home-system-558x348.jpg',
      '/media/bg-intra-home-system-470x292.jpg',
      '/media/bg-intra-home-system-446x278.jpg',
      '/media/bg-intra-home-system-302x188.jpg',
      '/media/bg-intra-home-system-300x187.jpg',
      '/media/bg-intra-home-system-120x75.jpg',
      '/media/bg-intra-home-system-75x47.jpg',
      '/media/bg-intra-home-system.jpg',
      '/work/home-services/intra-home-systems-marketing/',
      '/media/img-intra-home-system.png',
      '/media/img-intra-home-system-529x348.png',
      '/media/img-intra-home-system-422x278.png',
      '/media/img-intra-home-system-300x198.png',
      '/media/img-intra-home-system-286x188.png',
      '/media/img-intra-home-system-75x49.png',
      '/media/img-intra-home-system.png',
      '/work/home-services/air-duct-brothers-marketing/',
      '/media/bg-air-duct-brothers-1.jpg',
      '/media/bg-air-duct-brothers-1-558x348.jpg',
      '/media/bg-air-duct-brothers-1-470x292.jpg',
      '/media/bg-air-duct-brothers-1-446x278.jpg',
      '/media/bg-air-duct-brothers-1-302x188.jpg',
      '/media/bg-air-duct-brothers-1-300x187.jpg',
      '/media/bg-air-duct-brothers-1-120x75.jpg',
      '/media/bg-air-duct-brothers-1-75x47.jpg',
      '/media/bg-air-duct-brothers-1.jpg',
      '/work/home-services/air-duct-brothers-marketing/',
      '/media/airduct-brothers.png',
      '/media/airduct-brothers-529x348.png',
      '/media/airduct-brothers-422x278.png',
      '/media/airduct-brothers-300x198.png',
      '/media/airduct-brothers-286x188.png',
      '/media/airduct-brothers-75x49.png',
      '/media/airduct-brothers.png',
      '/work/home-services/velocity-moving-marketing/',
      '/media/bg-velocity-moving.jpg',
      '/media/bg-velocity-moving-558x348.jpg',
      '/media/bg-velocity-moving-470x292.jpg',
      '/media/bg-velocity-moving-446x278.jpg',
      '/media/bg-velocity-moving-302x188.jpg',
      '/media/bg-velocity-moving-300x187.jpg',
      '/media/bg-velocity-moving-120x75.jpg',
      '/media/bg-velocity-moving-75x47.jpg',
      '/media/bg-velocity-moving.jpg',
      '/work/home-services/velocity-moving-marketing/',
      '/media/img-velocity-moving.png',
      '/media/img-velocity-moving-529x348.png',
      '/media/img-velocity-moving-422x278.png',
      '/media/img-velocity-moving-300x198.png',
      '/media/img-velocity-moving-286x188.png',
      '/media/img-velocity-moving-75x49.png',
      '/media/img-velocity-moving.png',
      '/work/medical-healthcare/ethos-spa-marketing/',
      '/media/bg-ethos-spa.jpg',
      '/media/bg-ethos-spa-558x348.jpg',
      '/media/bg-ethos-spa-470x292.jpg',
      '/media/bg-ethos-spa-446x278.jpg',
      '/media/bg-ethos-spa-302x188.jpg',
      '/media/bg-ethos-spa-300x187.jpg',
      '/media/bg-ethos-spa-120x75.jpg',
      '/media/bg-ethos-spa-75x47.jpg',
      '/media/bg-ethos-spa.jpg',
      '/work/medical-healthcare/ethos-spa-marketing/',
      '/media/ethos-spa-1.png',
      '/media/ethos-spa-1-529x348.png',
      '/media/ethos-spa-1-422x278.png',
      '/media/ethos-spa-1-300x198.png',
      '/media/ethos-spa-1-286x188.png',
      '/media/ethos-spa-1-75x49.png',
      '/media/ethos-spa-1.png',
      '/work/medical-healthcare/enmed-microanalytics/',
      '/media/bg-seo-medical-healthcare-enmed-micro-analytics.jpg',
      '/media/bg-seo-medical-healthcare-enmed-micro-analytics-558x348.jpg',
      '/media/bg-seo-medical-healthcare-enmed-micro-analytics-470x292.jpg',
      '/media/bg-seo-medical-healthcare-enmed-micro-analytics-446x278.jpg',
      '/media/bg-seo-medical-healthcare-enmed-micro-analytics-302x188.jpg',
      '/media/bg-seo-medical-healthcare-enmed-micro-analytics-300x187.jpg',
      '/media/bg-seo-medical-healthcare-enmed-micro-analytics-120x75.jpg',
      '/media/bg-seo-medical-healthcare-enmed-micro-analytics-75x47.jpg',
      '/media/bg-seo-medical-healthcare-enmed-micro-analytics.jpg',
      '/work/medical-healthcare/enmed-microanalytics/ ',
      '/media/seo-medical-healthcare-enmed-micro-analytics.png',
      '/media/seo-medical-healthcare-enmed-micro-analytics-529x348.png',
      '/media/seo-medical-healthcare-enmed-micro-analytics-422x278.png',
      '/media/seo-medical-healthcare-enmed-micro-analytics-300x198.png',
      '/media/seo-medical-healthcare-enmed-micro-analytics-286x188.png',
      '/media/seo-medical-healthcare-enmed-micro-analytics-75x49.png',
      '/media/seo-medical-healthcare-enmed-micro-analytics.png',
      '/work/medical-healthcare/newman-plastic-surgery-center-marketing/',
      '/media/bg-newman-plastic-surgery.jpg',
      '/media/bg-newman-plastic-surgery-558x348.jpg',
      '/media/bg-newman-plastic-surgery-470x292.jpg',
      '/media/bg-newman-plastic-surgery-446x278.jpg',
      '/media/bg-newman-plastic-surgery-302x188.jpg',
      '/media/bg-newman-plastic-surgery-300x187.jpg',
      '/media/bg-newman-plastic-surgery-120x75.jpg',
      '/media/bg-newman-plastic-surgery-75x47.jpg',
      '/media/bg-newman-plastic-surgery.jpg',
      '/work/medical-healthcare/newman-plastic-surgery-center-marketing/',
      '/media/img-newman-plastic-surgery.png',
      '/media/img-newman-plastic-surgery-529x348.png',
      '/media/img-newman-plastic-surgery-422x278.png',
      '/media/img-newman-plastic-surgery-300x198.png',
      '/media/img-newman-plastic-surgery-286x188.png',
      '/media/img-newman-plastic-surgery-75x49.png',
      '/media/img-newman-plastic-surgery.png',
      '/experts/medical-healthcare/',
      '/work/legal-services/corradino-papa/',
      '/media/bg-seo-ppc-legal-corradino-papa.jpg',
      '/media/bg-seo-ppc-legal-corradino-papa-558x348.jpg',
      '/media/bg-seo-ppc-legal-corradino-papa-470x292.jpg',
      '/media/bg-seo-ppc-legal-corradino-papa-446x278.jpg',
      '/media/bg-seo-ppc-legal-corradino-papa-302x188.jpg',     
      '/media/bg-seo-ppc-legal-corradino-papa-300x187.jpg',
      '/media/bg-seo-ppc-legal-corradino-papa-120x75.jpg',
      '/media/bg-seo-ppc-legal-corradino-papa-75x47.jpg',
      '/media/bg-seo-ppc-legal-corradino-papa.jpg',
      '/work/legal-services/corradino-papa/',
      '/media/seo-ppc-legal-corradino-papa.png',
      '/media/seo-ppc-legal-corradino-papa-529x348.png',
      '/media/seo-ppc-legal-corradino-papa-422x278.png',
      '/media/seo-ppc-legal-corradino-papa-300x198.png',
      '/media/seo-ppc-legal-corradino-papa-286x188.png',
      '/media/seo-ppc-legal-corradino-papa-75x49.png',
      '/media/seo-ppc-legal-corradino-papa.png',
      '/work/legal-services/the-shulman-law-group-marketing/',
      '/media/bg-shulman-law-group.jpg',
      '/media/bg-shulman-law-group-558x348.jpg',     
      '/media/bg-shulman-law-group-470x292.jpg',
      '/media/bg-shulman-law-group-446x278.jpg',
      '/media/bg-shulman-law-group-302x188.jpg',
      '/media/bg-shulman-law-group-300x187.jpg',
      '/media/bg-shulman-law-group-120x75.jpg',
      '/media/bg-shulman-law-group-75x47.jpg',
      '/media/bg-shulman-law-group.jpg',
      '/work/legal-services/the-shulman-law-group-marketing/',
      '/media/img-shulman-law.png',
      '/media/img-shulman-law-529x348.png',
      '/media/img-shulman-law-422x278.png',
      '/media/img-shulman-law-300x198.png',
      '/media/img-shulman-law-286x188.png',
      '/media/img-shulman-law-75x49.png',
      '/media/img-shulman-law.png',     
      '/work/legal-services/weber-fabiyan-associates/',
      '/media/bg-legal-ppc-weber-fabiyan-n-associates.jpg',
      '/media/bg-legal-ppc-weber-fabiyan-n-associates-558x348.jpg',
      '/media/bg-legal-ppc-weber-fabiyan-n-associates-470x292.jpg',
      '/media/bg-legal-ppc-weber-fabiyan-n-associates-446x278.jpg',
      '/media/bg-legal-ppc-weber-fabiyan-n-associates-302x188.jpg',
      '/media/bg-legal-ppc-weber-fabiyan-n-associates-300x187.jpg',
      '/media/bg-legal-ppc-weber-fabiyan-n-associates-120x75.jpg',
      '/media/bg-legal-ppc-weber-fabiyan-n-associates-75x47.jpg',
      '/media/bg-legal-ppc-weber-fabiyan-n-associates.jpg',
      '/work/legal-services/weber-fabiyan-associates/',
      '/media/ppc-legal-weber-fabiyan-n-associates-1.png',
      '/media/ppc-legal-weber-fabiyan-n-associates-1-529x348.png',
      '/media/ppc-legal-weber-fabiyan-n-associates-1-422x278.png',
      '/media/ppc-legal-weber-fabiyan-n-associates-1-300x198.png',     
      '/media/ppc-legal-weber-fabiyan-n-associates-1-286x188.png',
      '/media/ppc-legal-weber-fabiyan-n-associates-1-75x49.png',
      '/media/ppc-legal-weber-fabiyan-n-associates-1.png',
      '/media/colt-exhaust-ppc-automotive-bg.jpg',
      '/media/colt-exhaust-ppc-automotive-bg-558x348.jpg',
      '/media/colt-exhaust-ppc-automotive-bg-470x292.jpg',
      '/media/colt-exhaust-ppc-automotive-bg-446x278.jpg',
      '/media/colt-exhaust-ppc-automotive-bg-302x188.jpg',
      '/media/colt-exhaust-ppc-automotive-bg-300x187.jpg',
      '/media/colt-exhaust-ppc-automotive-bg-120x75.jpg',
      '/media/colt-exhaust-ppc-automotive-bg-75x47.jpg',
      '/media/colt-exhaust-ppc-automotive-bg.jpg',
      '/work/automotive/colt-exhaust/',
      '/media/ppc-automotive-colt-exhaust.png',
      '/media/ppc-automotive-colt-exhaust-529x348.png',     
      '/media/ppc-automotive-colt-exhaust-422x278.png',
      '/media/ppc-automotive-colt-exhaust-300x198.png',
      '/media/ppc-automotive-colt-exhaust-286x188.png',
      '/media/ppc-automotive-colt-exhaust-75x49.png',
      '/media/ppc-automotive-colt-exhaust.png',
      '/work/automotive/springfield-hyundai-marketing/',
      '/media/bg-spring-field.jpg',
      '/media/bg-spring-field-558x348.jpg',
      '/media/bg-spring-field-470x292.jpg',
      '/media/bg-spring-field-446x278.jpg',
      '/media/bg-spring-field-302x188.jpg',
      '/media/bg-spring-field-300x187.jpg',
      '/media/bg-spring-field-120x75.jpg',
      '/media/bg-spring-field-75x47.jpg',
      '/media/bg-spring-field.jpg',     
      '/work/automotive/springfield-hyundai-marketing/',
      '/media/img-spring-field.png',
      '/media/img-spring-field-529x348.png',
      '/media/img-spring-field-422x278.png',
      '/media/img-spring-field-300x198.png',
      '/media/img-spring-field-286x188.png',
      '/media/img-spring-field-75x49.png',
      '/media/img-spring-field.png',
      '/media/bg-ppc-automotive-upsw.jpg',
      '/media/bg-ppc-automotive-upsw-558x348.jpg',
      '/media/bg-ppc-automotive-upsw-470x292.jpg',
      '/media/bg-ppc-automotive-upsw-446x278.jpg',
      '/media/bg-ppc-automotive-upsw-302x188.jpg',
      '/media/bg-ppc-automotive-upsw-300x187.jpg',
      '/media/bg-ppc-automotive-upsw-120x75.jpg',     
      '/media/bg-ppc-automotive-upsw-75x47.jpg',
      '/media/bg-ppc-automotive-upsw.jpg',
      '/media/ppc-automotive-upsw.png',
      '/media/ppc-automotive-upsw-529x348.png',
      '/media/ppc-automotive-upsw-422x278.png',
      '/media/ppc-automotive-upsw-300x198.png',
      '/media/ppc-automotive-upsw-75x49.png',
      '/media/ppc-automotive-upsw.png ',
      '/media/bg-arcarius-funding.jpg',
      '/media/bg-arcarius-funding-558x348.jpg',
      '/media/bg-arcarius-funding-470x292.jpg',
      '/media/bg-arcarius-funding-446x278.jpg',
      '/media/bg-arcarius-funding-302x188.jpg',
      '/media/bg-arcarius-funding-300x187.jpg',
      '/media/bg-arcarius-funding-120x75.jpg',     
      '/media/bg-arcarius-funding-75x47.jpg',
      '/media/bg-arcarius-funding.jpg',
      '/work/b2b/arcarius-funding-marketing/',
      '/media/img-arcarius-funding.png',
      '/media/img-arcarius-funding-529x348.png',
      '/media/img-arcarius-funding-422x278.png',
      '/media/img-arcarius-funding-300x198.png',
      '/media/img-arcarius-funding-286x188.png',
      '/media/img-arcarius-funding-75x49.png',
      '/media/img-arcarius-funding.png',
      '/media/bg-seo-ppc-business-to-business-joto-ventures.jpg',
      '/media/bg-seo-ppc-business-to-business-joto-ventures-558x348.jpg ',
      '/media/bg-seo-ppc-business-to-business-joto-ventures-470x292.jpg',
      '/media/bg-seo-ppc-business-to-business-joto-ventures-446x278.jpg',
      '/media/bg-seo-ppc-business-to-business-joto-ventures-302x188.jpg',
      '/media/bg-seo-ppc-business-to-business-joto-ventures-300x187.jpg',
      '/media/bg-seo-ppc-business-to-business-joto-ventures-120x75.jpg',
      '/media/bg-seo-ppc-business-to-business-joto-ventures-75x47.jpg',
      '/media/bg-seo-ppc-business-to-business-joto-ventures.jpg',
      '/media/seo-ppc-business-to-business-joto-ventures.png',
      '/media/seo-ppc-business-to-business-joto-ventures-529x348.png',
      '/media/seo-ppc-business-to-business-joto-ventures-422x278.png',
      '/media/seo-ppc-business-to-business-joto-ventures-300x198.png',
      '/media/seo-ppc-business-to-business-joto-ventures-286x188.png',
      '/media/seo-ppc-business-to-business-joto-ventures-75x49.png',
      '/media/seo-ppc-business-to-business-joto-ventures.png',
      '/work/b2b/e-valve-technologies-marketing/',
      '/media/bg-e-value-technologies.jpg',
      '/media/bg-e-value-technologies-558x348.jpg',
      '/media/bg-e-value-technologies-470x292.jpg',
      '/media/bg-e-value-technologies-446x278.jpg',
      '/media/bg-e-value-technologies-302x188.jpg',
      '/media/bg-e-value-technologies-300x187.jpg',
      '/media/bg-e-value-technologies-120x75.jpg',
      '/media/bg-e-value-technologies-75x47.jpg',
      '/media/bg-e-value-technologies.jpg',
      '/work/b2b/e-valve-technologies-marketing/',
      '/media/img-e-value-technologies.png',
      '/media/img-e-value-technologies-529x348.png',
      '/media/img-e-value-technologies-422x278.png',
      '/media/img-e-value-technologies-300x198.png ',
      '/media/img-e-value-technologies-286x188.png',
      '/media/img-e-value-technologies-75x49.png',
      '/media/img-e-value-technologies.png',
      '/media/bg-seo-ppc-retail-hat-heaven.jpg',
      '/media/bg-seo-ppc-retail-hat-heaven-558x348.jpg',
      '/media/bg-seo-ppc-retail-hat-heaven-470x292.jpg',
      '/media/bg-seo-ppc-retail-hat-heaven-446x278.jpg',
      '/media/bg-seo-ppc-retail-hat-heaven-302x188.jpg',
      '/media/bg-seo-ppc-retail-hat-heaven-300x187.jpg',
      '/media/bg-seo-ppc-retail-hat-heaven-120x75.jpg',
      '/media/bg-seo-ppc-retail-hat-heaven-75x47.jpg',
      '/media/bg-seo-ppc-retail-hat-heaven.jpg',
      '/media/seo-ppc-retail-hat-heaven.png',
      '/media/seo-ppc-retail-hat-heaven-529x348.png',
      '/media/seo-ppc-retail-hat-heaven-422x278.png',
      '/media/seo-ppc-retail-hat-heaven-300x198.png',
      '/media/seo-ppc-retail-hat-heaven-286x188.png',
      '/media/seo-ppc-retail-hat-heaven-75x49.png',
      '/media/seo-ppc-retail-hat-heaven.png',
      '/work/retail/outdoor-gear-marketing/',
      '/media/bg-outdoor-gear.jpg',
      '/media/bg-outdoor-gear-558x348.jpg',
      '/media/bg-outdoor-gear-470x292.jpg',
      '/media/bg-outdoor-gear-446x278.jpg',
      '/media/bg-outdoor-gear-302x188.jpg',
      '/media/bg-outdoor-gear-300x187.jpg',
      '/media/bg-outdoor-gear-120x75.jpg',
      '/media/bg-outdoor-gear-75x47.jpg',
      '/media/bg-outdoor-gear.jpg',
      '/work/retail/outdoor-gear-marketing/',
      '/media/img-outdoor-gear.png',
      '/media/img-outdoor-gear-529x348.png',
      '/media/img-outdoor-gear-422x278.png',
      '/media/img-outdoor-gear-300x198.png',
      '/media/img-outdoor-gear-286x188.png',
      '/media/img-outdoor-gear-75x49.png',
      '/media/img-outdoor-gear.png',
      '/media/bg-ppc-retail-movingup-garage.jpg',
      '/media/bg-ppc-retail-movingup-garage-558x348.jpg',
      '/media/bg-ppc-retail-movingup-garage-470x292.jpg',
      '/media/bg-ppc-retail-movingup-garage-446x278.jpg',
      '/media/bg-ppc-retail-movingup-garage-302x188.jpg',
      '/media/bg-ppc-retail-movingup-garage-300x187.jpg',
      '/media/bg-ppc-retail-movingup-garage-120x75.jpg',
      '/media/bg-ppc-retail-movingup-garage-75x47.jpg',
      '/media/bg-ppc-retail-movingup-garage.jpg',
      '/media/ppc-retail-movingup-garage.png',
      '/media/ppc-retail-movingup-garage-529x348.png',
      '/media/ppc-retail-movingup-garage-422x278.png',
      '/media/ppc-retail-movingup-garage-300x198.png',
      '/media/ppc-retail-movingup-garage-286x188.png',
      '/media/ppc-retail-movingup-garage-75x49.png',
      '/media/ppc-retail-movingup-garage.png',
      '/media/bg-clark-filters.jpg',
      '/media/bg-clark-filters-558x348.jpg',
      '/media/bg-clark-filters-470x292.jpg',
      '/media/bg-clark-filters-446x278.jpg',
      '/media/bg-clark-filters-302x188.jpg',
      '/media/bg-clark-filters-300x187.jpg',
      '/media/bg-clark-filters-120x75.jpg',
      '/media/bg-clark-filters-75x47.jpg',
      '/media/bg-clark-filters.jpg',
      '/media/img-clark-filter.png',
      '/media/img-clark-filter-529x348.png',
      '/media/img-clark-filter-422x278.png',
      '/media/img-clark-filter-300x198.png',
      '/media/img-clark-filter-286x188.png',
      '/media/img-clark-filter-75x49.png',
      '/media/img-clark-filter.png',
      '/media/bg-aga-parts.jpg ',
      '/media/bg-aga-parts-558x348.jpg',
      '/media/bg-aga-parts-470x292.jpg',
      '/media/bg-aga-parts-446x278.jpg',
      '/media/bg-aga-parts-302x188.jpg',
      '/media/bg-aga-parts-300x187.jpg',
      '/media/bg-aga-parts-120x75.jpg',
      '/media/bg-aga-parts-75x47.jpg',
      '/media/bg-aga-parts.jpg',
      '/work/industrial-commercial/aga-truck-parts-marketing/',
      '/media/img-aga-parts.png',
      '/media/img-aga-parts-529x348.png',
      '/media/img-aga-parts-422x278.png',
      '/media/img-aga-parts-300x198.png',
      '/media/img-aga-parts-286x188.png',
      '/media/img-aga-parts-75x49.png',
      '/media/img-aga-parts.png',
      '/media/bg-melfast.jpg',
      '/media/bg-melfast-558x348.jpg',
      '/media/bg-melfast-470x292.jpg',
      '/media/bg-melfast-446x278.jpg',
      '/media/bg-melfast-302x188.jpg',
      '/media/bg-melfast-300x187.jpg',
      '/media/bg-melfast-120x75.jpg',
      '/media/bg-melfast-75x47.jpg',
      '/media/bg-melfast.jpg',
      '/media/ppc-seo-melfast-industrial-commercial-marketing.png',
      '/media/ppc-seo-melfast-industrial-commercial-marketing-529x348.png',
      '/media/ppc-seo-melfast-industrial-commercial-marketing-422x278.png',
      '/media/ppc-seo-melfast-industrial-commercial-marketing-300x198.png',
      '/media/ppc-seo-melfast-industrial-commercial-marketing-286x188.png',
      '/media/ppc-seo-melfast-industrial-commercial-marketing-75x49.png',
      '/media/ppc-seo-melfast-industrial-commercial-marketing.png',
      '/media/bg-nj-lux-real-estate-1.jpg',
      '/media/bg-nj-lux-real-estate-1-558x348.jpg',
      '/media/bg-nj-lux-real-estate-1-470x292.jpg',
      '/media/bg-nj-lux-real-estate-1-446x278.jpg',
      '/media/bg-nj-lux-real-estate-1-302x188.jpg',
      '/media/bg-nj-lux-real-estate-1-300x187.jpg',
      '/media/bg-nj-lux-real-estate-1-120x75.jpg',
      '/media/bg-nj-lux-real-estate-1-75x47.jpg',
      '/media/bg-nj-lux-real-estate-1.jpg',
      '/media/nj-lux.png',
      '/media/nj-lux-529x348.png',
      '/media/nj-lux-422x278.png',
      '/media/nj-lux-300x198.png',
      '/media/nj-lux-286x188.png',
      '/media/nj-lux-75x49.png',
      '/media/nj-lux.png',
      '/media/bg-sports-medicine-and-orthopaedic-center.jpg',
      '/media/bg-sports-medicine-and-orthopaedic-center-558x348.jpg',
      '/media/bg-sports-medicine-and-orthopaedic-center-470x292.jpg',
      '/media/bg-sports-medicine-and-orthopaedic-center-446x278.jpg',
      '/media/bg-sports-medicine-and-orthopaedic-center-302x188.jpg',
      '/media/bg-sports-medicine-and-orthopaedic-center-300x187.jpg',
      '/media/bg-sports-medicine-and-orthopaedic-center-120x75.jpg',
      '/media/bg-sports-medicine-and-orthopaedic-center-75x47.jpg',
      '/media/bg-sports-medicine-and-orthopaedic-center.jpg',
      '/media/img-sports-medicine-and-orthopaedic-center.png',
      '/media/img-sports-medicine-and-orthopaedic-center-529x348.png',
      '/media/img-sports-medicine-and-orthopaedic-center-422x278.png',
      '/media/img-sports-medicine-and-orthopaedic-center-300x198.png',
      '/media/img-sports-medicine-and-orthopaedic-center-286x188.png',
      '/media/img-sports-medicine-and-orthopaedic-center-75x49.png',
      '/media/img-sports-medicine-and-orthopaedic-center.png',
      '/media/bg-the-calendar-group.jpg',
      '/media/bg-the-calendar-group-558x348.jpg',
      '/media/bg-the-calendar-group-470x292.jpg',
      '/media/bg-the-calendar-group-446x278.jpg',
      '/media/bg-the-calendar-group-302x188.jpg',
      '/media/bg-the-calendar-group-300x187.jpg',
      '/media/bg-the-calendar-group-120x75.jpg',
      '/media/bg-the-calendar-group-75x47.jpg',
      '/media/bg-the-calendar-group.jpg',
      '/media/the-calendar-group-1.png',
      '/media/the-calendar-group-1-529x348.png',
      '/media/the-calendar-group-1-422x278.png',
      '/media/the-calendar-group-1-300x198.png',
      '/media/the-calendar-group-1-286x188.png',
      '/media/the-calendar-group-1-75x49.png',
      '/media/the-calendar-group-1.png',
      '/media/smartsites-digital-experts.jpg',
      '/media/smartsites-digital-experts-1024x816.jpg',
      '/media/smartsites-digital-experts-768x612.jpg',
      '/media/smartsites-digital-experts-582x464.jpg',
      '/media/smartsites-digital-experts-543x433.jpg',
      '/media/smartsites-digital-experts-528x421.jpg',
      '/media/smartsites-digital-experts-436x348.jpg',
      '/media/smartsites-digital-experts-349x278.jpg',
      '/media/smartsites-digital-experts-300x239.jpg',
      '/media/smartsites-digital-experts-236x188.jpg',
      '/media/smartsites-digital-experts-75x60.jpg',
      '/media/smartsites-digital-experts.jpg',
      '/media/nationwide-merchant-solutions-1.png',
      '/media/nationwide-merchant-solutions-1-75x23.png',
      '/media/nationwide-merchant-solutions-1.png',
      '/media/poker-stars.png',
      '/media/poker-stars-75x44.png',
      '/media/poker-stars.png',
      '/media/rolls-royce.png',
      '/media/rolls-royce-75x26.png',
      '/media/rolls-royce.png',
      '/media/njit-1.png ',
      '/media/njit-1-75x23.png',
      '/media/njit-1.png',
      '/media/a-absolute-1.png',
      '/media/a-absolute-1-75x23.png', 
      '/media/a-absolute-1.png',
      '/media/rockville-interiors-badge.png', 
      '/media/rockville-interiors-badge-75x35.png',
      '/media/rockville-interiors-badge.png', 
      '/media/logo-rackuten.png',
      '/media/logo-rackuten-75x13.png', 
      '/media/logo-rackuten.png',
      '/media/proxy-key-logo.png', 
      '/media/proxy-key-logo-75x31.png',
      '/media/proxy-key-logo.png', 
      '/media/newman-plastic-surgery-logo.png',
      '/media/newman-plastic-surgery-logo-75x26.png',
      '/media/newman-plastic-surgery-logo.png',
      '/media/micky-bodies-logo.png', 
      '/media/micky-bodies-logo-75x37.png',
      '/media/micky-bodies-logo.png', 
      '/media/dralex-nyc-logo.png',
      '/media/a-and-a-coatings-logo.png', 
      '/media/a-and-a-coatings-logo-75x22.png',
      '/media/a-and-a-coatings-logo.png',
      '/media/air-duct-brothers-logo.png', 
      '/media/air-duct-brothers-logo-75x47.png',
      '/media/air-duct-brothers-logo.png',
      '/media/classic-audi-logo.png', 
      '/media/classic-audi-logo-75x21.png',
      '/media/classic-audi-logo.png',
      '/media/shulman-law-group-logo.png',
      '/media/shulman-law-group-logo-75x38.png', 
      '/media/shulman-law-group-logo.png',
      '', 
      '',
      '', 
      '',
      '',
      '', 
      '',
      '',
       
       
       
 



        ]

];
