<?php
$content = [
     "HomePage" => [
      'Contact us',
      'creating a resume&nbsp;<span>has never been easier',
      'Create an excellent resume in minutes.',
      'No more manual formatting. Fast, easy, flexible.',
      'CREATE RESUME FOR FREE',
      'Why should you use<span>FREE RESUME BUILDER?',
      'Save time and energy',
      'Leave behind all attempts to create a good resume in Microsoft Word. It has never produced a proper outcome. Build an awesome and free resume quickly and effortlessly, and spend more time preparing to interviews.',
      'Be professional',
      'Make your resume look neat and well-structured. Resume templates will help you organize all the information in your CV logically. You can even fine-tune the text of your job description to emphasise the most important details.',
      'Impress employers',
      'Make the employer choose your resume among all others. Increase your chances to pass the initial recruitment stage and get hired. Yes, it is possible with our free resume generator.',
      'A GOOD RESUME IS A KEY<span>TO YOUR DREAM JOB',
      'If you are a highly qualified specialist with the years of experience in the field or a recently graduated A-student, it does not mean you will get hired at once.',
      'A resume is your ticket to pass the selection process. Our online resume builder helps you receive this ticket and get the job you have always dreamt about.',
      'Easily and quickly generate a unique and effective print-ready resume and customize it for any vacancy you apply for. Get ready to choose from all interview invitations you’ll get thanks to a great resume you have created for free.',
      'How to create a resume with<span>OUR ONLINE EDITOR?',
      'No sign up is needed. Start creating a resume in our free resume editor. Choose the sections you want to include in your resume template and type all the needed information. Adjust fonts and colors. Don’t forget to preview your resume before downloading.',
      'If you like the way your it looks, simply download PDF version to your laptop or computer. And yes, you can modify your CV as much as you want it.',
      'Now, you can send your resume to potential employers and be sure it will make the correct first impression.',
      'Ready to create</span> the best CV!',
      'Get started with the best online job cv/resume maker and make job winning resumes in no time!',
      'CREATE RESUME FOR FREE',
      'Terms Of Service',
      'Privacy Policy',
      'Refund policy',
      'delivery policy',
      'about us',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',

                ]
];

$media =[
     "HomePage" => [
   '/static/media/logo.1a1245bf.svg',
   '/static/media/landing-resume.537d844c.svg',
   '/static/media/background.df615c87.svg',
   '/static/media/icon-1.ebb5588c.svg',
   '/static/media/icon-2.d2eab4a2.svg',
   '/static/media/icon-3.04354141.svg',
   '/static/media/template_1.0a5d9c00.jpg',
   '/static/media/template_3.d17d1d35.jpg',
   '/static/media/template_2.6f35a2bd.jpg',
   '/static/media/template_3.d17d1d35.jpg',
   '/static/media/template_1.0a5d9c00.jpg',
   '/static/media/template_3.d17d1d35.jpg',
   '/static/media/template_2.6f35a2bd.jpg',
   '/static/media/template_3.d17d1d35.jpg',
   '/static/media/template_1.0a5d9c00.jpg',
   '/static/media/step-1.d09711ab.svg',
   '/static/media/step-number-1.f2db00fa.svg',
   '/static/media/step-2.b768b738.svg',
   '/static/media/step-number-2.22432789.svg',
   '/static/media/step-3.7c7ae45a.svg',
   '/static/media/step-number-3.5caef08c.svg',
   '/static/media/arrow.3060b2b9.svg',
   '/static/media/logo.1a1245bf.svg',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',
   '',


     ]

];
