<?php
$content = [
     "HomePage" => [
      'Toggle navigation',
      'Features',
      'Pricing',
      'Contact Us',
      'The',
      'All-In-One',
      'AI Marketing Calendar For Content, Social, And Beyond',
      'Don’t let your marketing get messy. With',
      'Calendars, you can finally organize everything all in one place.',
      'Get Started Free',
      'Why not? It&#x27;s free forever.',
      '30,000 marketers start their day with',
      'Our Products',
      'Social Calendar',
      'Create, schedule, publish, &amp; measure your social in a single, AI-powered Social Calendar.',
      'Get total visibility of your social media',
      'Fill your social calendar with AI writing assistant',
      'Create the perfect social publishing schedule',
      'Explore More',
      'Content Calendar',
      'Get total visibility of all your tasks, projects, &amp; campaigns in a single Marketing Calendar.',
      'Seamlessly plan your entire marketing schedule',
      'Coordinate and execute multi-project campaigns',
      'See your high-level strategy at a glance',
      'Explore More',
      'Marketing Suite',
      'A family of agile marketing products to coordinate your team, projects, and process.',
      'Manage marketing requests',
      'Eliminate content bottlenecks',
      'Maximize resources to increase output',
      'Explore More',
      'Headline Studio',
      'Write better headlines that will boost your traffic.',
      'Score your headlines based on proven data',
      'Improve headlines with smart suggestions',
      'Find the high-scoring words instantly',
      'Explore More',
      'Actionable Marketing Institute',
      'Develop new marketing skills in 30 minutes (or less).',
      'Improve your marketing with fluff-free training',
      'Spend less time learning &amp; more time doing',
      'Learn from industry pros you trust',
      'Explore More',
      'The fastest growing marketing work management software',
      'is trusted by 30,000 marketers in 100+ countries.',
      'Gartner',
      'Magic Quadrant',
      'The Gartner Magic Quadrant™ for Content Marketing Platforms 2023',
      'One Of The Fastest-Growing Marketing Platforms 3 Years In a Row',
      'Awarded High Performer in Several Product Categories',
      'Pick Your All-In-One Marketing&nbsp;Calendar',
      'Create your calendar free today! No credit card required.',
      'Free Calendar',
      'For individuals looking for basic social&nbsp;publishing.',
      '$0',
      'Free Forever',
      'Get Started Free',
      'Up to 1 user',
      'Team collaboration features are unavailable in free&nbsp;Calendars.',
      'Connect 2 Social Profiles',
      'Connect up to 2 social profiles to schedule and publish messages to Facebook, LinkedIn, Pinterest, &amp;&nbsp;Instagram.',
      'Up to 15 Scheduled Social Messages',
      'Free Calendar includes:',
      'AI Social Assistant',
      'Instantly write social messages via AI that meet social network best&nbsp;practices.',
      'Drag &amp; Drop Calendar',
      'Move projects to new publish dates to automatically reschedule projects, tasks, &amp; social&nbsp;messages.',
      'Best Time Social Publishing',
      'Best Time Scheduling publishes social messages at the best time for engagement &amp; reach for each social&nbsp;network.',
      'Personal Project Management',
      'Add personal tasks &amp; deadlines for projects, social campaigns, &amp;&nbsp;events.',
      'Basic Support',
      'Email &amp; Live Chat Support from',
      '’s Support Team. Available M-F, 7:00 am - 6:00 pm&nbsp;CST.',
      'Social Calendar',
      'For individuals and teams looking for limitless social&nbsp;publishing.',
      '$19',
      'USD',
      'Per User/Month',
      'Billed Annually',
      'Switch to Monthly',
      'Get Started Free',
      'Up to 3 users',
      'Collaborate in teams of up to 3 team&nbsp;members.',
      'Connect 5 Social Profiles',
      'Connect up to 5 social profiles to schedule and publish messages to Facebook, LinkedIn, Pinterest, Twitter &amp;&nbsp;Instagram.',
      '$5/mo for each additional profile',
      'Free Features, plus:',
      'Unlimited Social Media Publishing',
      'Create &amp; schedule an unlimited number of social messages to Facebook, LinkedIn, Pinterest, Instagram, &amp;&nbsp;Twitter.',
      'AI Project Assistant',
      'Chat with',
      '’s AI-bot to generate ideas, draft copy, &amp;&nbsp;more!',
      'Bulk Social Media Scheduling',
      'Upload &amp; schedule bulk social messages with a CSV file&nbsp;import.',
      'Social Media Automation',
      'Automate recurring promotions &amp; reshare your best social&nbsp;messages.',
      'Recurring Tasks &amp; Events',
      'Automatically assign repeating tasks &amp; events to your&nbsp;Calendar.',
      'Social Analytics &amp; Reports',
      'Visualize &amp; share social performance in easy-to-understand&nbsp;reports.',
      'Learn more about Social Calendar',
      'Content Calendar',
      'For teams that want all of their content and social on one&nbsp;calendar.',
      'Call',
      'We’re nice to talk to!',
      'Talk To Sales',
      'Up to 5 users',
      'Collaborate in teams of up to 5 team&nbsp;members.',
      'Connect 10 Social Profiles',
      'Connect up to 10 social profiles to schedule and publish messages to Facebook, Twitter, LinkedIn, Pinterest, &amp;&nbsp;Instagram.',
      'Additional profiles can be added',
      'Social Features, plus:',
      'Kanban Project View',
      'Manage work through each stage of the process with customizable Kanban&nbsp;Board.',
      'Table View',
      'See, share, or sort all your projects &amp; campaigns in a spreadsheet-style&nbsp;list.',
      'Marketing Campaigns',
      'Group related projects together in a single, focused campaign&nbsp;timeline.',
      'Custom Fields',
      'Create unlimited custom fields to document specific project details for more context &amp;&nbsp;organization.',
      'Custom Project Types',
      'Create &amp; customize unique project types your team regularly&nbsp;completes.',
      'Project &amp; Campaign Reports',
      'Prove the value &amp; productivity of your team with easy-to-export&nbsp;reports.',
      'Guest User Access',
      'Guest seats for external contributors, vendors, or&nbsp;freelancers.',
      'Learn more about Content Calendar',
      'Marketing Suite',
      'For marketing teams looking to coordinate their marketing process, projects, and&nbsp;teams',
      'Call',
      'We’re nice to talk to!',
      'Talk To Sales',
      'Custom User Limits',
      'Invite your entire team to collaborate on your&nbsp;Calendar.',
      'Custom Social Profile Limits',
      'Connect all of your social&nbsp;profiles.',
      'Content Features, plus:',
      'Sub-Calendars',
      'Custom Calendar Views for departments, product lines, &amp;&nbsp;more.',
      'Approval Workflows',
      'Create &amp; implement required approvals to ensure work meets brand&nbsp;standards.',
      'Intake Request Forms',
      'Create shareable project intake forms to field &amp; prioritize incoming&nbsp;requests.',
      'Team Management Dashboard',
      'Easily review, delegate, &amp; assign work to effectively manage your team’s&nbsp;priorities.',
      'Digital Asset Management',
      'Store, index, &amp; share your content to maintain control over brand&nbsp;assets.',
      'Advanced Audience Targeting For Social Publishing',
      'Send Facebook &amp; LinkedIn messages to specific user groups based on geographical &amp; demographic&nbsp;parameters.',
      'Custom Permissions',
      'Customize publishing, project, &amp; dashboard access per&nbsp;user.',
      'Manager Visibility &amp; Reporting',
      'Review updates on employee productivity to demonstrate hiring needs &amp; eliminate&nbsp;blockers.',
      'Single Sign-On (SSO)',
      'Log in with your SSO credentials. No need to memorize&nbsp;passwords.',
      'Dedicated Account Manager',
      'Get personalized onboarding, training, &amp; support from your',
      '&nbsp;expert.',
      'Complete Feature List',
      'Free Calendar',
      'Social Calendar',
      'Content Calendar',
      'Marketing Suite',
      'Billed Annually',
      'Save 20%',
      '$0',
      '$19 per user/month',
      'Call',
      'Call',
      'Billed Monthly',
      '$0',
      '$29 per user/month',
      'Maximum Users',
      'The maximum number of users per&nbsp;account.',
      'Up to 1 user',
      'Up to 3 users',
      'Up to 5 users',
      'Custom User Limits',
      'iOS and Android Apps',
      'Review tasks &amp; schedule social messages anywhere via the mobile&nbsp;app.',
      'Unlimited Free Viewers',
      'Free Viewers have read-only access via link-sharing &amp; cannot make changes or&nbsp;edit.',
      'Calendar',
      'Drag and Drop Content Calendar',
      'Adjust timelines for projects, tasks, &amp; social messages with drag &amp; drop&nbsp;rescheduling.',
      'Customizable Color Coding',
      'Visually categorize content on your calendar using color labels for departments, teams, products, &amp;&nbsp;more.',
      'Project Tag Management',
      'Use tags to label &amp; organize related posts, messages, &amp; projects&nbsp;together.',
      'Filtered &amp; Saved Calendars',
      'Create saved calendars for email, social, sales projects, &amp; other segmented&nbsp;views.',
      'Custom Project Types',
      'Add custom project types for any content or projects your team&nbsp;creates.',
      'Custom Fields',
      'Add specific metadata &amp; details to projects (examples include, project deadlines, quantity, URL, budget, &amp;&nbsp;more).',
      'Marketing Campaigns',
      'See campaign timelines on your Calendar. Campaigns group all camapign-specific projects in a focused Calendar&nbsp;View.',
      'Kanban Dashboard',
      'Manage work through every stage of the process using a customizable Kanban&nbsp;View.',
      'Table View',
      'See all your scheduled &amp; unscheduled projects in a scannable spreadsheet-style&nbsp;list.',
      'Custom Sub-Calendars',
      'Pre-built calendar views for specific color&nbsp;labels.',
      'Social Media Management',
      'Social Calendar',
      'Plan &amp; execute your perfect social publishing schedule in one calendar&nbsp;view.',
      'Social Sync',
      'Syncs messages published outside your',
      '&nbsp;Calendar.',
      'Social Publishing',
      'Social Profiles',
      'Connect your social profiles to create, schedule, &amp; publish&nbsp;mesages.',
      'Connect 2 Social Profiles',
      'Connect 5 Social Profiles',
      '$5/mo for each additional profile',
      'Connect 10 Social Profiles',
      'Additional profiles can be added',
      'Custom Social Profile Limits',
      'Social Message Limits',
      'This includes the number of messages you can schedule &amp; publish via your Calendar at one&nbsp;time.',
      'Up to 15',
      'Unlimited',
      'Unlimited',
      'Unlimited',
      'Social Campaigns',
      'Create social campaigns to view all the social messages that promote events, new content, &amp;&nbsp;more.',
      'Best Time Scheduling',
      'Automatically publish messages at the best time for engagement across each social&nbsp;platform.',
      'AI Social Assistant',
      'AI-powered social message writer. Writes messages for you (so you don’t have&nbsp;to).',
      'Social Message Optimizer',
      'Optimize social messages for each network to maximize&nbsp;engagement.',
      'Reusable Social Templates',
      'Create reusable social sharing schedules to promote new blog posts, podcasts, &amp;&nbsp;more.',
      'Social Media Analytics &amp; Reports',
      'Create actionable, data-driven performance reports for campaigns, social profiles, &amp;&nbsp;more.',
      'Social Media Automation - ReQueue',
      'Automatically fill gaps in your social schedule with top messages or automate promotions with&nbsp;ReQueue.',
      'Bulk Social Media Scheduling',
      'Add up to 365 social messages to your Calendar at once using Bulk&nbsp;Import.',
      'Advanced Audience Targeting',
      'Send Facebook &amp; LinkedIn messages to specific user groups based on geographical &amp; demographic&nbsp;parameters.',
      'Content Marketing',
      'Email Subject Line Tester',
      'Plan &amp; execute your perfect social publishing schedule in one calendar&nbsp;view.',
      'Headline Studio Integration',
      'Get suggestions to improve &amp; optimize your&nbsp;headlines.',
      'Content Ideation - AI Project Assistant',
      'Use AI Project Assistant to instantly generate project&nbsp;ideas.',
      'Content Creation - AI Project Assistant',
      'Use AI Project Assistant to draft first-draft copy in&nbsp;seconds.',
      'Project Intake Request Forms',
      'Create custom project intake forms to make it easy for others to request&nbsp;work.',
      'Marketing Work Management',
      'Marketing Projects',
      'Use Projects to organize your drafts, files, tasks, &amp;&nbsp;more.',
      'Personal Tasks',
      'Assign tasks with due dates to keep work on&nbsp;track.',
      'Project Attachments',
      'Attach images, videos, files, social campaigns, &amp; other assets to your&nbsp;project.',
      'Recurring Task Automation',
      'Automatically add recurring tasks to your&nbsp;Calendar.',
      'Recurring Event Automation',
      'Automatically add recurring events to your&nbsp;Calendar.',
      'Reusable Task Templates',
      'Create reusable task templates to standardize your team’s&nbsp;workflows.',
      'Discussions &amp; Team Collaboration',
      'Add comments to collaborate with your team. Add feedback, context, &amp;&nbsp;more.',
      'Project &amp; Task Contributors',
      'Keep project contributors up to date with progress via&nbsp;notifications.',
      'Project Observer Views',
      'Share real-time updates via read-only views. Observer Views give visibility without access to make&nbsp;changes.',
      'Reusable Project Templates',
      'Add projects in seconds. Create project templates to standardize required details like project owners, tasks, attachments, custom fields, &amp;&nbsp;more.',
      'Reusable Campaign Templates',
      'Add new campaigns to your Calendar in seconds to get work into production&nbsp;quickly.',
      'Approval Workflows',
      'Add required approvals to your team’s workflows, so everyone knows what tasks need approval &amp;&nbsp;when.',
      'Team Management Dashboard',
      'Dashboard to review &amp; delegate priority projects and tasks for your entire&nbsp;team.',
      'Team Performance Report',
      'Run reports to visualize your team’s productivity &amp;&nbsp;output.',
      'Digital Asset Management',
      'File Storage',
      '1TB of storage. Need more? Talk to&nbsp;Sales.',
      'Asset Storage',
      'Store all your brand assets, photos, videos, logos, &amp; more in Asset&nbsp;Organizer.',
      'Limited',
      'Limited',
      'Limited',
      '20GB - 1TB',
      'File Preview',
      'Preview files before opening&nbsp;them.',
      'File Types',
      'Supports all major file types for video, image, &amp; design&nbsp;files.',
      'Google Drive Integration',
      'Integrate with Google Drive to access files you need&nbsp;fast.',
      'Dropbox Integration',
      'Integrate with your current Dropbox account to access files you need&nbsp;fast.',
      'OneDrive Integration',
      'Integrate with your current OneDrive account to access files you need&nbsp;fast.',
      'Version History',
      'Get historical record of all past versions of a specific file or&nbsp;asset.',
      'File Sharing',
      'Easily share files &amp; assets via sharable&nbsp;links.',
      'Digital Asset Management Dashboard',
      'Organize, store, index, &amp; share your content in a dedicated DAM&nbsp;solution.',
      'Security &amp; Privacy',
      'User Roles',
      'User roles for managers, team members, freelancers, &amp;&nbsp;stakeholders.',
      'Custom Permissions',
      'Limit &amp; customize user access to tabs, social profiles, &amp; other&nbsp;content.',
      'Single Sign-On (SSO)',
      'Login with Service Provider Initiated SAML Account. No passwords&nbsp;required.',
      'Security &amp; Access Logs',
      'Track all changes inside of <?=$namehost?> with security &amp; access&nbsp;logs.',
      'Support &amp; Training',
      'Basic Support',
      'Email &amp; Live Chat Support from',
      '’s Support Team. Available M-F, 7:00 am - 6:00 pm&nbsp;CST.',
      'Self-Serve Knowledge Base &amp; Guides',
      'Access',
      '’s comprehensive user guides, video tutorials, &amp;&nbsp;more.',
      'Priority Support',
      'Email response within 90&nbsp;minutes.',
      'Calendar Setup + Onboarding',
      'Personalized one-hour training session so that you’re setup to be&nbsp;successful',
      'Dedicated Customer Success Manager (CSM)',
      'Receive personalized support from a',
      '&nbsp;expert.',
      'Add-Ons',
      'Actionable Marketing Institute',
      '$50 per month/team',
      '$100 per month/team',
      '$100 per month/team',
      'Headline Studio Pro',
      'Get Headline Studio Pro to unlock SEO tools, AI, &amp;&nbsp;more.',
      'Get Started Free',
      'Get Started Free',
      'Talk To Sales',
      'Talk To Sales',
      'Organize all of your marketing in one place',
      'Get Started Free',
      'Terms Of Service',
      'Privacy Policy',
      'Refund policy',
      'delivery policy',
      'about us',
      '© Copyright',
      '2023',
      ', all rights reserved',
      '',



                ]
];

$media =[
     "HomePage" => [
        '/img/s.png',
        '/img/home/home-calendar-2.png',
        '/img/home/home-calendar-2.png',
        '/img/testimonials/forbes-logo.webp',
        '/img/testimonials/yamaha-logo.webp',
        '/img/testimonials/unicef-logo.webp',
        '/img/testimonials/vericast-logo2.webp',
        '/img/testimonials/walgreens-logo.webp',
        '/img/testimonials/dictionary-com-logo.webp',
        '/img/testimonials/p-and-g-logo.webp',
        '/img/testimonials/schwans-logo.webp',
        '/img/home/sc-product-background.png',
        '/img/product/social-cal-icon-dark.svg',
        '/img/home/cc-product-background.png',
        '/img/product/content-cal-icon-dark.svg',
        '/img/home/suite-product-background.png',
        '/img/product/marketing-suite-product-icon.png',
        '/img/home/hs-product-background.png',
        '/img/home/ami-product-background.png',
        '/img/testimonials/inc-5000-logo.png',
        '/img/testimonials/crowd-badge-spring2023.png',
        '/img/product/free-cal-icon-light.png',
        '/img/product/social-cal-icon-light.png',
        '/img/product/content-cal-icon-light.png',
        '/img/product/marketing-suite-icon-light.png',
        'img/testimonials/g2crowd-badge-spring2023.png',
        '/img/testimonials/gartner-badge.png',
        '/img/testimonials/forbes-badge.png',
        '',


        ]

];
