<?php
$content = [
     "HomePage" => [
       'Pricing',
       'About',
       'MaxCustomer',
       'Easy',
       'Customer',
       'Relationship Management',
       'READ MORE',
       'MaxCustomer',
       'Easy-to-use',
       'CRM System',
       'READ MORE',
       'Easy Customer Relationship Management',
       'What is MAXCUSTOMER?',
       'MaxCustomer is an easy-to-use Customer Relationship Management (CRM) system that provides businesses the ability to analyze and increase their sales by effective management of revenue opportunities, customer relationship, and sales growth.',
       'Increase in Sales',
       'Track your sales, leads and provide you with real-time reports so you can monitor the status at any given day and time.',
       'Effective Lead Management',
       'Provide your reps the ability to add, follow-up and convert good leads to new customers.',
       'Read More',
       'Why Choose MaxCustomer?',
       'MaxCustomer is focused on giving our clients the ability to manage the complete customer relationship process from a single page. We ensure that our clients get the best of the below benefits at all times to improve their businesses:',
       'Single page ability to manage the customer relationship',
       'Ability to manage an opportunity from lead to close',
       'Useful tracking of opportunities for all management',
       'Access to the application for all sales people anywhere in the world!',
       'Best pricing for a CRM solution of its capabilities.',
       'We are more excited to improve your business in the following areas:',
       'Choosing our MaxCustomer for your CRM needs means that you choose to take your business to the next level.',
       'Increase in Sales',
       'Track your sales, leads and provide you with real-time reports so you can monitor the status at any given day and time..',
       'Effective Lead Management',
       'Provide your reps the ability to add, follow-up and convert good leads to new customers.',
       'Improve Customer Retention',
       'Help you identify and prioritize customers that require further attention to avoid losing them.',
       'Improve Team Performance',
       'Guide team members to pull customer information fast which gives them the ability to respond to customer queries.',
       'Role Based Security',
       'Delegate security levels within your organization by assigning credentials that match specific roles.',
       'Collaboration',
       'Interact and engage with team members to enhance workflow and productivity.',
       'Price Plans and Packages',
       'MaxCustomer CRM is offered in following price plans: Pro, Premier and Enterprise. Choose which one works best for your company.',
       'Subscription Rate Per User',
       'No. of Users-Reps',
       'Pro',
       'Premier',
       'Enterprise',
       'Up to 20',
       '$9.95',
       '$14.95',
       '$24.95',
       'Up to 50',
       '$8.46',
       '$12.71',
       '$21.21',
       'Up to 100',
       '$7.19',
       '$10.80',
       '$18.03',
       'Up to 200',
       '$6.11',
       '$9.18',
       '$15.32',
       'Up to 300',
       '$5.19',
       '$7.80',
       '$13.02',
       'Up to 400',
       '$4.41',
       '$6.63',
       '$11.07',
       'Up to 500',
       '$3.75',
       '$5.64',
       '$9.41',
       'Up to 600',
       '$3.19',
       '$4.79',
       '$8.00',
       'Up to 700',
       '$2.71',
       '$4.07',
       '$6.80',
       'Up to 800',
       '$2.30',
       '$3.46',
       '$5.78',
       'Up to 900',
       '$1.96',
       '$2.94',
       '$4.91',
       'Up tp 1000',
       '$1.67',
       '$2.50',
       '$4.18',
       'Up to 10000',
       '$0.83',
       '$0.63',
       '$2.09',
       'Up to 100000',
       '$0.42',
       '$0.31',
       '$1.04',
       'Price Plans and Features',
       'Features',
       'Economy',
       'Premium',
       'Use Own Logo',
       'No',
       'Yes',
       'Visitor Tracking',
       'Yes',
       'Yes',
       'Mobility',
       'No',
       'Yes',
       'Leads Management',
       'Yes',
       'Yes',
       'Reports',
       'Yes',
       'Yes',
       'Dashboard',
       'Yes',
       'Yes',
       'Import/Export',
       'Yes',
       'Yes',
       'Email',
       'Yes',
       'Yes',
       'Manage Customer Account',
       'Yes',
       'Yes',
       'Google Apps Integration via Single Sign-On',
       'Yes',
       'Yes',
       'User-Reps',
       '5 to 200',
       '2 and above',
       'Role Based Security',
       'No',
       'Yes',
       'Collaboration',
       'Yes',
       'Yes',
       'Volume Discount',
       'down to $2.23',
       'down to $3.74',
       'Want to learn more about MaxCustomer? Contact us and we will provide you with a FREE consultation!',
       'Read More',
       'About Us',
       'MaxCustomer is an easy-to-use Customer Relationship Management (CRM) system.',
       'Useful Links',
       'Privacy Policy',
       'Terms Of Service',
       'Refund policy',
       'delivery policy',
       'Copyright @ 2023 CellarStone Inc. All Rights Reserved.',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',

  

   














                ]
];

$media =[
     "HomePage" => [
        'https://www.maxcustomer.com//images/banners/mc-banner6.png',
        'https://www.maxcustomer.com//images/banners/mc-banner7.png',
        '/images/2023/02/17/promo-banner-bg.jpg',
        '/images/maxcustomer-logo.png',
        '/images/banners/mc-banner6.png',
        '/images/banners/mc-banner7.png',
        '/images/about/mc-about-bg.png',
        '/images/2023/02/17/about-thumb-3.jpg',
        '/images/2023/02/17/about-thumb-4.jpg',
        '/images/banners/what-is-maxcustomer.jpg',
        '/images/banners/home-why-crm.jpg',    
        '/images/icon/circle-arrow-right-solid.svg',
        '/images/icon/circle-arrow-right-solid.svg',
        '/images/icon/circle-arrow-right-solid.svg',
        '/images/icon/circle-arrow-right-solid.svg',
        '/images/icon/circle-arrow-right-solid.svg',
        '/images/2023/02/17/footer-bg.jpg',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
 



        ]

];
