<?php
$content = [
     "HomePage" => [
       'Features',
       'Pricing',
       'Menu',
       'Features',
       'Pricing',
       'Contact Us',
       'Contact Us',
       'The fast, easy',
       '& affordable social',
       'is a simple, easy-to-learn tool that helps small teams, content creators and entrepreneurs create, schedule, share and automate content daily.',
       'Try for FREE',
       'Book a DEMO',
       'Never run out of stuff to post on social media.',
       'Refresh',
       'Give your evergreen posts a second life with Edgar’s content repurposing so you always have something to say.',
       'Schedule',
       'Add time slots so Edgar can automatically publish the updates your audience always looks forward to.',
       'Track',
       'Monitor and A/B test variations to see what resonates best with your audience across multiple social networks.',
       'Grow',
       'Watch your business grow as Edgar engages your audience, and drives new followers, leads, and sales.',
       'THE easiest way to share your evergreen content on social media',
       'is a new kind of social media management tool for all-sized businesses and solopreneurs, helping you create, schedule, share, and automate content daily.',
       'View the  Features',
       'Refresh your social.',
       'The only social media scheduler that lets you create your content and keep it too. Other schedulers delete your content right after posting, but not',
       '. Edgar keeps your content in a limitless library. Anytime you run out of content to post, Edgar can draw from your library and repurpose older content with content resharing so you never have to worry about running out of ideas.',
       'Try for FREE',
       'Schedule your posts.',
       'Manually posting content is time-consuming so let',
       'do the work for you. Schedule content in advance and manage your social media accounts from one dashboard. Take control of your online presence before it controls you.',
       'Try for FREE',
       'Track your impact.',
       'See what posts perform best, and why. View your social media account&#8217;s performance metrics in real-time so you can make informed decisions about what content to plan, produce, and publish for your audience.',
       'Try for FREE',
       'Grow your audience.',
       'Grow your audience like never before. By posting consistently, Edgar engages your audience and drives new followers, leads, and sales.',
       'Try for FREE',
       'Never run out of stuff to post',
       'Want to promote a special offer every other day? Share a blog post once a week? Edgar automates your recurring tasks, so you can kiss your to-do list goodbye.',
       'Edgar&nbsp;',
       'builds a bottomless library of evergreen updates',
       '&nbsp;organized by category, so you control what types of content get shared and when. If he runs out of new updates, he’ll re-share older ones, so your social is always on – even when you’re focused on other things.',
       'Learn more&nbsp;',
       'Add weekly automation time slots',
       'for Edgar to automatically repurpose and republish your evergreen updates',
       'Keep your audience engaged',
       '– Edgar will keep posting even when you don’t have time to manually schedule updates',
       'Build a bottomless library of evergreen content</b> for Edgar to choose from over time',
       'Pick the plan that works best for you.',
       'Edgar helps manage your social media accounts, regardless of your experience level.',
       'Annual',
       'Monthly',
       'Eddie Annual Plan',
       '$',
       '24.91',
       'month',
       'For side hustlers, and those just getting started',
       '$299/year',
       '5',
       'social accounts',
       'Additional Social Accounts - $3.99',
       'Unlimited',
       'scheduled posts',
       '10',
       'weekly automations',
       '4',
       'content categories',
       '20',
       'team members',
       'Buy Now',
       'Edgar Annual Plan',
       '$',
       '41.58',
       'month',
       'For entrepreneurs and small businesses',
       '$499/year',
       '25',
       'social accounts',
       'Additional Social Accounts - $1.99',
       'Unlimited',
       'scheduled posts',
       '1,000',
       'weekly automations',
       'Unlimited',
       'customizable content categories',
       '20',
       'team members',
       'Buy Now',
       'Eddie Monthly Plan',
       '$',
       '29.99',
       'month',
       'For side hustlers, and those just getting started',
       '5',
       'social accounts',
       'Additional Social Accounts - $4.99',
       'Unlimited',
       'scheduled posts',
       '10',
       'weekly automations',
       '4',
       'content categories',
       '20',
       'team members',
       'Buy Now',
       'Edgar Monthly Plan',
       '$',
       '49.99',
       'month',
       'For entrepreneurs and small businesses',
       '25',
       'social accounts',
       'Additional Social Accounts - $2.99',
       'Unlimited',
       'scheduled posts',
       '1,000',
       'weekly automations',
       'Unlimited',
       'customizable content categories',
       '20',
       'team members',
       'Buy Now',
       'Why',
       '?',
       'Why is Edgar different from other scheduling tools?',
       'We&#8217;re female-founded and bootstrapped.',
       'Our plans are designed for freelancers, side hustlers, and small businesses.',
       'Edgar never runs out of content. We&#8217;ll keep pulling from your bottomless library of evergreen content.&nbsp;',
       '0',
       'Happy Clients',
       '1',
       'Years in Business',
       'Ready Try Edgar?',
       'Create an account now and generate more leads',
       'Get Started for Free',
       'What customer say',
       'Recent Reviews!',
       'Take a moment to read what customers say about using',
       'to schedule their social media.',
       'Darren Rowse, Founder',
       '“I was immediately struck by how powerful the tool was.”',
       'Jana Tolman, Author',
       '“I love that I can set aside an hour each week to add more to my library and then I don’t have to think about social media again!”',
       'Stu McLaren, Entrepreneur',
       '“Edgar freakin’ rocks. It’s shaved hundreds of hours off my workload. I honestly don’t know what I’d do without it now.”',
       'Join 10,000+ entrepreneurs who let Edgar handle their social media calendar for them.',
       'Ready to get started?',
       'Try Edgar Free',
       'is the fast, easy &amp; affordable social media management tool.',
       'Facebook',
       'Twitter',
       'Instagram',
       'Pinterest',
       'Linkedin',
       'Youtube',
       'Icon-threads-app-logo-1',
       'Other',
       'Terms Of Service',
       'Privacy Policy',
       'Refund policy',
       'delivery policy',
       'about us',
       '© 2023 SureSwift Capital',
       '',
       '',
       '',


  

   














                ]
];

$media =[
     "HomePage" => [
        '/wp-content/uploads/2022/04/meetedgar-color-horizontal.png',
        '/wp-content/uploads/2022/11/bigger.png',
        '/wp-content/uploads/2022/10/logos-3-768x154.png',
        '/wp-content/uploads/elementor/thumbs/meetedgar-color-stacked-1-q932shtzle3qr5ij9odwom7khiyracvosmo3kej1cg.png',
        '/wp-content/uploads/2022/10/meet-edgar-icon.png',
        '/wp-content/uploads/2022/10/meet-edgar-icon.png',
        '/wp-content/uploads/2022/10/meet-edgar-icon.png',
        '/wp-content/uploads/2022/10/01-Refresh-your-social-1-1024x683.png',
        '/wp-content/uploads/2022/10/02-Schedule-your-posts-1024x683.png',
        '/wp-content/uploads/2022/10/03-Track-your-impact-1024x683.png',
        '/wp-content/uploads/2022/10/04_Grow-your-audience-1024x683.png',
        '/wp-content/uploads/2022/10/Never-Run-Out-Of-Stuff-To-Post.png',
        '/wp-content/uploads/2022/10/meet-edgar-icon-5.png',
        '/wp-content/uploads/2022/10/meet-edgar-icon-5.png',
        '/wp-content/uploads/2022/10/meet-edgar-icon-5.png',
        '/wp-content/uploads/2022/10/meet-edgar-icon-5.png',
        '/wp-content/uploads/2022/05/meetedgar-social-media-tool-1024x715.png',
        '/wp-content/uploads/2022/05/social-media-scheduler-tool-1.png',
        '/wp-content/uploads/2022/05/social-media-scheduler-tool-2.png',
        '/wp-content/uploads/2022/05/social-media-scheduler-tool-3.png',
        '/wp-content/uploads/2019/10/emaus_cta_circle_1.png',
        '/wp-content/uploads/2022/05/sm6.png',
        '/wp-content/uploads/2022/05/sm3.png',
        '/wp-content/uploads/2022/05/sm2.png',
        '/wp-content/uploads/2022/05/sm5.png',
        '/wp-content/uploads/2022/05/sm4.png',
        '/wp-content/uploads/2022/04/meetedgar-white-horizontal-1024x299.png',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
       
       
 



        ]

];
