<?php
$content = [
     "HomePage" => [
        'Pricing',
        'Connect',
        'about us',
        'One platform.',
        'Endless possibilities',
        'Drive engagement at every customer touch point and manage your unique marketing process confidently with',
        'Start for Free',
        'Our client portfolio',
        'Discover the unique benefits today!',
        'Smarter and faster',
        'CRM solution',
        'Personalized reports and dashboards',
        'Customizable view of all your sales details',
        'Identify key contacts',
        'Streamlined path to your business’s success',
        'Automatic email/call/meeting tracking',
        'Customer 360 to deliver seamless customer experiences',
        'Know your customer, their interactions and provide personalized experiences',
        'Important KPIs to monitor',
        'Find B2B data quickly',
        'Easy access to B2B Data discovery',
        'Search 15 M+ Business profiles in one click.',
        'Extension',
        'With a LinkedIn plugin, the',
        'Extension',
        'imports the email addresses of your prospective',
        'clients directly into an email marketing database.',
        'LEARN MORE',
        'Target marketing',
        'Build',
        '-&nbsp;From a single location, create personalized emails, social ads, landing sites, postcards, and more.',
        'LEARN MORE &nbsp;',
        'With intelligent automation, you can sell more',
        'Organize',
        '- Using intelligent automation, manage work pipelines, update deals, and follow up on leads while organizing customer data.',
        'LEARN MORE &nbsp;',
        'Our numbers will answer you!',
        '25M+',
        'Business Profiles',
        '15M+',
        'Company Profiles',
        '20M+',
        'Email Ids',
        '10M+',
        'Direct Dials',
        'Choose a',
        'plan',
        'that is right for your business!',
        'Marketing',
        'CRM',
        'USD',
        'INR',
        'Basic',
        'Free',
        '7 days trial',
        '3,000 contacts',
        '1,000 Emails per month',
        'get started',
        'Starter',
        '$',
        '62',
        '/month (billed annually)',
        '10,000 contacts',
        '10,000 Emails per month',
        '1,000 Data Credits per month',
        '24 Hrs Email Support',
        'White label domain ',
        'Buy Now',
        'Most Popular Plan',
        'Advanced',
        '$',
        '122',
        '/month ( billed annually )',
        'Unlimited contacts',
        'FUP',
        '50,000 Emails per month',
        '2,500 Data Credits per month',
        '12 Hrs Chat &amp; Email Support',
        'White label domain',
        'Buy Now',
        'Professional',
        '$',
        '305',
        '/month (billed annually )',
        'Unlimited contacts',
        '*',
        'FUP',
        '150,000 Emails per month',
        '15,000 Data Credits per month',
        'Chat, Email &amp; Dedicated A/C Manager',
        'White label domain',
        'Buy Now',
        '*',
        'Fair Usage Policy (FUP): It is essential for all clients to comply with our fair usage policy.',
        '*Prices are exclusive of GST.',
        'View All Features In Detail',
        'Talk with Sales Expert',
        'Monthly',
        'Yearly',
        '( Save 20% )',
        'USD',
        'INR',
        'Lite',
        '$',
        '8',
        '/month billed',
        'annually',
        'Lead Management',
        'Account Management',
        'Pipeline Management',
        'Reports and Analytics',
        'Conversion Scoring',
        'Task Management',
        'Contact us',
        'Basic',
        '$',
        '16',
        '/month billed',
        'annually',
        'Custom Fields',
        'Custom Layout',
        'Marketing Automation',
        'Document Management',
        'Web-to-Lead',
        'Auto Assignment Leads',
        'Contact us',
        'Most Popular Plan',
        'Professional',
        '$',
        '39',
        '/month billed',
        'annually',
        'Workflow Automation',
        'Field level Security/History',
        'Custom Event Triggers',
        'Integrations',
        'Multi Currency',
        'Contact us',
        'Custom Package',
        'Get Quote',
        'Need custom requirements? Contact sales',
        'Contact us',
        '*Prices are exclusive of GST.',
        'View All Features In Detail',
        'Talk with Sales Expert',
        'Take a look at what our clients have to say',
        'We really appreciate the contribution of',
        'Connect in helping us to become ‘automated’ in our marketing initiatives. The workflow automations are well-versed and replaced my 5 other existing tools for being connected with both customers and new leads.',
        'CMO',
        'Real Estate Company',
        'Using',
        'Connect+ as our campaign platform was a game-changer for us. With',
        '’s user-friendly interface and powerful features, we saw a remarkable increase in our campaign’s reach and engagement. It allowed us to target the right audience effectively, resulting in a 30% boost in lead generation and a 20% increase in conversion rates.',
        'Chayanika Bhattacharya',
        'Co-Founder - 1HR.market',
        ' We were facing several challenges in our marketing efforts, from acquiring a targeted industry-specific database to finding a user-friendly email marketing solution.',
        'stepped in as the solution to all these challenges, providing us with the tools and expertise needed to streamline our sales and marketing endeavours.',
        'Navin Khaware',
        'AVP-Sales at Check An Invoice',
        'I have had exceptional service from ',
        'Connect after struggling with the complex &amp; expensive marketing tool for 10 months. I have experienced handhold support at every step of my usage journey. I would highly recommend them to everyone.',
        'Sr. Marketing Manager',
        'Legal Services',
        'Connect is intuitive to use, and well laid out. Their support system is available 24/7 on mail, calls &amp; chat. The easy accessibility of tracking engaged visitors, new leads and clients is a blessing for us to serve our customers more efficiently.',
        'Sales Head',
        'Travel &amp; Tourism',
        'The tool is indeed simplest and fabulous to use. It makes our communication look professional and at the same time provides detailed analysis and reports that assist us in tracking the engagement.',
        'Content Strategist',
        'Digital Agency',
        'We really appreciate the contribution of',
        'Connect in helping us to become ‘automated’ in our marketing initiatives. The workflow automations are well-versed and replaced my 5 other existing tools for being connected with both customers and new leads.',
        'CMO',
        'Real Estate Company',
        'Using',
        'Connect+ as our campaign platform was a game-changer for us. With',
        '’s user-friendly interface and powerful features, we saw a remarkable increase in our campaign’s reach and engagement. It allowed us to target the right audience effectively, resulting in a 30% boost in lead generation and a 20% increase in conversion rates.',
        'Chayanika Bhattacharya',
        'Co-Founder - 1HR.market',
        'We were facing several challenges in our marketing efforts, from acquiring a targeted industry-specific database to finding a user-friendly email marketing solution.',
        'stepped in as the solution to all these challenges, providing us with the tools and expertise needed to streamline our sales and marketing endeavours.',
        'Navin Khaware',
        'AVP-Sales at Check An Invoice',
        'I have had exceptional service from',
        'Connect after struggling with the complex &amp; expensive marketing tool for 10 months. I have experienced handhold support at every step of my usage journey. I would highly recommend them to everyone.',
        'Sr. Marketing Manager',
        'Legal Services',
        'Connect is intuitive to use, and well laid out. Their support system is available 24/7 on mail, calls &amp; chat. The easy accessibility of tracking engaged visitors, new leads and clients is a blessing for us to serve our customers more efficiently.',
        'Sales Head',
        'Travel &amp; Tourism',
        'The tool is indeed simplest and fabulous to use. It makes our communication look professional and at the same time provides detailed analysis and reports that assist us in tracking the engagement.',
        'Content Strategist',
        'Digital Agency',
        'We really appreciate the contribution of',
        'Connect in helping us to become ‘automated’ in our marketing initiatives. The workflow automations are well-versed and replaced my 5 other existing tools for being connected with both customers and new leads.',
        'CMO',
        'Real Estate Company',
        'Company',
        'Terms Of Service',
        'Privacy Policy',
        'Refund policy',
        'delivery policy',
        'Contact Us',
        'Software India Pvt. LTD.',
        'India: 105, First Floor, Chiranjiv Tower, Nehru Place, Delhi - 110019',
        'U.S.A.: 9893 Georgetown Pike, Ste 531, Great Falls VA 22066',
        '© 2023',
        '. All rights reserved.',
        '',
        '',
        '',
        '',
        '',


 



                ]
];

$media =[
     "HomePage" => [
        'assets/images/SalezShark-logo.svg',
        'assets/images/homePage/G2Logos.png',
        'assets/images/homePage/BoostOutput.webp',
        'assets/images/product/bmw.png',
        'assets/images/customer-logos/canon.png',
        'assets/images/customer-logos/swiggy.png',
        'assets/images/customer-logos/tata.png',
        'assets/images/customer-logos/audi.png',
        'assets/images/customer-logos/mahindra-logo.png',
        'assets/images/customer-logos/bharti-logo.png',
        'assets/images/homePage/smarter.webp',
        'assets/images/homePage/CustomisedView.webp',
        'assets/images/homePage/StreamLinedpath.webp',
        'assets/images/homePage/Customer360.webp',
        'assets/images/homePage/DiscoverB2B.webp',
        'assets/images/homePage/SalezsharkExtension.webp',
        'assets/images/ic_arrow-right.svg',
        'assets/images/ic_arrow-right.svg',
        'assets/images/homePage/Build.webp',
        'assets/images/homePage/Organize.webp',
        'assets/images/ic_arrow-right.svg',
        'assets/images/homePage/twent-five-mill.png',
        'assets/images/homePage/comp-prof.png',
        'assets/images/homePage/email-ids.png',
        'assets/images/homePage/direct-calls.png',
        'assets/images/homePage/right-arrow-pink.png',
        'assets/images/homePage/right-arrow-pink.png',
        'assets/images/homePage/right-arrow-pink.png',
        'assets/images/homePage/right-arrow-pink.png',
        'assets/images/homePage/Semicolon.png',
        'assets/images/homePage/clients-testi-four.webp',
        'assets/images/homePage/Semicolon.png',
        'assets/images/homePage/ChayanikaBhattacharya_cl.png',
        'assets/images/homePage/Semicolon.png',
        'assets/images/homePage/Navin_Khaware.png',
        'assets/images/homePage/Semicolon.png',
        'assets/images/homePage/clients-testi-one.webp',
        'assets/images/homePage/Semicolon.png',
        'assets/images/homePage/clients-testi-two.webp',
        'assets/images/homePage/Semicolon.png',
        'assets/images/homePage/clients-testi-three.webp',
        'assets/images/homePage/Semicolon.png',
        'assets/images/homePage/clients-testi-four.webp',
        'assets/images/homePage/Semicolon.png',
        'assets/images/integrations/case-studies/one-hr/ChayanikaBhattacharya_cl.png',
        'assets/images/homePage/Semicolon.png',
        'assets/images/integrations/case-studies/checkAnInvoice/Navin_Khaware.png',
        'assets/images/homePage/Semicolon.png',
        'assets/images/homePage/clients-testi-one.webp',
        'assets/images/homePage/Semicolon.png',
        'assets/images/homePage/clients-testi-two.webp',
        'assets/images/homePage/Semicolon.png',
        'assets/images/homePage/clients-testi-three.webp',
        'assets/images/homePage/Semicolon.png',
        'assets/images/homePage/clients-testi-four.webp',
        'assets/images/homePage/salezshark_color_logo.png',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
       
       
 



        ]

];
