<?php
$content = [
     "HomePage" => [
        'menu',
      'Features',
      'Pricing',
      'Contact Us',
      'Imagine Better.',
      'WE CREATE SMART, BEAUTIFUL, AND EFFECTIVE',
      'BRANDS',
      'WEBSITES',
      ', and',
      'MARKETING CAMPAIGNS',
      'FOR TODAY’S VISIONARIES WITH TOMORROW’S IDEAS.',
      'Calling All: Free Thinkers.',
      'Fear Vanquishers.',
      'Cosmic Dreamers.',
      'Bringing your idea into the world is no small feat. It needs to be',
      'properly understood',
      'carefully nurtured',
      'and given consistent positive energy in order to flourish. At Ivio Agency we’re committed to giving each idea we work the best possible chance to succeed.',
      'what',
      'we do',
      'Services',
      'Branding',
      'Your business or idea holds a unique and impactful story demanding to be told to the world. Our detailed and unique process makes sure your brand radiates authenticity and intention in your competitive space.',
      'Go Deeper',
      'Strategy',
      'Realize your potential. It’s not enough to have an amazing idea, you need to plan and execute your way to success. We’ll support from the beginning to help you break through the noise and stay on track.',
      'Go Deeper',
      'Content',
      'Your brand needs powerful and consistent content to captivate your audience. We craft world class content that’s compelling, engaging and thoughtfully on-brand.',
      'Go Deeper',
      'Web & Digital',
      'Been there, done that. Our digital marketing expertise is rooted in a long history in website design and development. With over 15 years and well over 250+ web projects of all complexity levels, there is nothing we cannot do.',
      'Go Deeper',
      'Our Process Is Our Promise',
      'Better means, better ends. You’ll always get our very best work because we’re radically dedicated to the creative process, both as individuals and a team. We apply the knowledge and wisdom we glean from our journey to your project.',
      'About Us',
      'View Case Study',
      '01 ',
      'The McKinley Club ',
      'View Case Study',
      '02 ',
      'Lizy Hoeffer ',
      '03',
      'Murphy Cordier PLC ',
      '04',
      'Storytellers Brand Studio',
      'View Case Study ',
      '05 ',
      'Fetch! Pet Care ',
      'View Case Study ',
      '06 ',
      'Sky Crossing ',
      'Our Work',
      'View Our Work ',
      'Trusted By Many',
      'Work With Us',
      'Ready To Bring Your Ideas Into the World?',
      'Give Us A Call',
      '602-316-1204',
      'Find Us',
      '734 W Polk St. Suite #8',
      'Phoenix, Arizona 85007',
      'Follow Along',
      'Explore',
      'Terms Of Service',
      'Privacy Policy',
      'Refund policy',
      'delivery policy',
      'about us',
      'Drop us a note and we’ll get back to you soon.',
      'Name',
      '*',
      'Email',
      '*',
      'Phone Number',
      '*',
      'Company',
      'Message',
      '*',
      '21896',
      'Ivio proudly services our clients from our office in downtown Phoenix where we call home.',
      '©2023 Ivio Agency',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',







                ]
];

$media =[
     "HomePage" => [
        '/wp-content/themes/bones_3.0/library/images/ivio-text-logo.svg',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/plugins/revslider/public/assets/assets/transparent.png',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/09/icon-tmc.png',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/09/icon-lh.png',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/09/icon-if.png',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/09/icon-of.png',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/09/icon-fpc.png',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/09/icon-rpa.png',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/10/MKC.jpg',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/10/STBS.jpg',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/10/SC.jpg',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/10/FPC.jpg',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/10/LH.jpg',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/10/TMC.jpg',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/10/TMC.jpg',
        '/wp-content/plugins/revslider/public/assets/assets/dummy.png',
        '/wp-content/uploads/2020/10/laptop-black-screen.png',
        '/wp-content/uploads/2021/07/Walgreens_Logo.svg',
        '/wp-content/uploads/2021/07/USA_Today.svg',
        '/wp-content/uploads/2021/07/gannett.svg',
        '/wp-content/uploads/2021/07/logo-yellowtail.svg',
        '/wp-content/uploads/2021/07/asu-logo.svg',
        '/wp-content/uploads/2021/07/pulte-homes-1.svg',
        '/wp-content/uploads/2021/07/Taylor-Morrison-Logo.svg',
        '/wp-content/uploads/2021/07/aar-logo.svg',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',



        ]

];
